### ISSUE TITLE
key-bindings.bash: No such file or directory

### ISSUE THREAD

**Issue by garytyler** [WhitewaterFoundry/WLinux#100]
**Describe the bug**
`-bash: /tmp/tmp.TPShXECZCd/fzf/shell/key-bindings.bash: No such file or directory` reported on launch after running setup

**To Reproduce**
1. Run `/etc/setup` and add keybindings, fuzzy autocomplete
2. Close WLinux
2. Launch WLinux

**Expected behavior**
No `No such file or directory` message

**What other troubleshooting have you attempted?**
Reboot

**WLinux Version**
1.1.20.0

**Windows Build**
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17134 N/A Build 17134
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation

**Comment by sirredbeard** [comment]
This was a side effect of running the fzf installer in a temp folder.

I ran into it too.

The updated script works around this problem with fzf by running fzf directly in ~.

If you ran it the old way, fzf saved keybindings in a temporary folder and referenced them, and you need to delete the reference to them.

**Comment by garytyler** [comment]
I reset WLinux which cleared the error, then ran the setup script update, then ran setup again. The error returned.

**Comment by garytyler** [comment]
Where is the "reference to them"?

**Comment by sirredbeard** [comment]
Whoops, that patch is in testing, not in master yet, sorry, my mistake.

Probably in ~/.zshrc.

I would nuke .zshrc and then re-run oh-my-zsh install from ~.

I do not know why oh-my-zsh isn't context-aware about where it is being run from but we will look at their install script and might suggest some upstream patches.

**Comment by garytyler** [comment]
I never installed oh-my-zsh, so it's probably not in ~/.zshrc.

**Comment by garytyler** [comment]
(I never installed zsh either)

**Comment by sirredbeard** [comment]
Then wherever your shell stores keybindings.
