### ISSUE TITLE
Do not install nodejs with yarn

### ISSUE THREAD

**Issue by khuongduybui** [WhitewaterFoundry/WLinux#101]
Now that we have decided to install `node` with `n`, our current `yarn` installation script will also install the legacy `nodejs` version 4 package.

According to official Yarn docs (https://yarnpkg.com/lang/en/docs/install/#debian-stable) we can install `yarn` without `nodejs` with the flag:

```bash
sudo apt-get install --no-install-recommends yarn
```

EDITED: I just tested that with a fresh installation of WLinux using the latest install script. NO issues found.

**Comment by sirredbeard** [comment]
Added with commit https://github.com/WhitewaterFoundry/WLinux/pull/102/commits/2f3c3fbcd10e70e3691b02b7bd526b5c4a4fe0f4.

Thank you for your help with this.
