### ISSUE TITLE
Open with WLinux not working on folders with space

### ISSUE THREAD

**Issue by Andreas-Ntonas** [WhitewaterFoundry/WLinux#104]
**Describe the bug**
When trying to open a folder which has a space in its name with the shift-right click explorer shortcut Open with WLinux it fails.

**To Reproduce**
1. Shift+righ click on a directory where folder name has a space in it (e.g. C:\bug\not working)
2. Open with WLinux
3. WLinux opens and terminated immediately 

[x] I have confirmed WSL is enabled: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[x] I have searched Google for the error message.
[x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[x] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[x] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**WLinux Version**
1.1.21.0

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              American Megatrends Inc. 3802, 15/3/2018

**Comment by sirredbeard** [comment]
Thank you for reporting this. We will take a look at it.

**Comment by patrick330602** [comment]
The issue have been identified. I will update the .reg file later today.
