### ISSUE TITLE
Font setting is canceled after opening tmux new session, starting vim, etc.

### ISSUE THREAD

**Issue by mmyoji** [WhitewaterFoundry/WLinux#107]
**Describe the bug**
As I mentioned on the title, the font setting of the terminal is canceled after opening tmux new session, starting vim(neovim), or I can say, re-rendering the screen.

This didn't happen Ubuntu(v16.04) on WSL.

**To Reproduce**
1. Open 'Property' of the terminal app and change the font whatever (In my case, 'Consolas')
2. Then run `tmux` (I installed through `apt`)
3. The font is set as `MS Gothic` (default one)

I currently use JP version WLinux (also Windows10), so there might be term difference.

**Expected behavior**
Selected font must appear whenever a page is re-rendered.

**Basic Troubleshooting Checklist**

* [x] I have confirmed WSL is enabled: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
* [x] I have searched Google for the error message.
* [x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
* [x] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
* [x] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
* [x] I have disabled and re-enabled WSL in Windows Features.
* [x] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**WLinux Version**

Find: Settings->Apps->Apps & features->WLinux->Advanced Options->Version.

Insert here: 1.1.21.0

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here: 

```
OS 名:                  Microsoft Windows 10 Home
OS バージョン:          10.0.17134 N/A ビルド 17134
OS 製造元:              Microsoft Corporation
OS 構成:                スタンドアロン ワークステーション (Standalone workstation)
OS ビルドの種類:        Multiprocessor Free
BIOS バージョン:        LENOVO M16KT41A, 2017/10/20
```

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by mmyoji** [comment]
Start tmux session -> Open 'Property' and change font setting -> Run vim inside the session or open new tmux window, the font setting is not changed.

Then it's ok for my situation now.

**Comment by patrick330602** [comment]
it seems to be a upstream issue: https://github.com/Microsoft/console/issues/177

**Comment by mmyoji** [comment]
ok, thank you. I close this.
