### ISSUE TITLE
Dependency error when installing npm

### ISSUE THREAD

**Issue by Kalaschnik** [WhitewaterFoundry/WLinux#108]
**Describe the bug**
sudo apt-get install npm creates an error

**To Reproduce**
1. sudo apt-get install nodejs
2. sudo apt-get install npm

**Expected behavior**
npm is installed

**Screenshots**
![image](https://user-images.githubusercontent.com/9831678/46855934-5f126700-ce05-11e8-91a2-6c3e2558ccf6.png)

**Comment by patrick330602** [comment]
Thanks for the feedback. What version of WLinux are you using?

**Comment by sirredbeard** [comment]
I would recommend getting a more recent version of npm:

> $ sudo apt -t testing install npm
