### ISSUE TITLE
build error in DistroLauncher-Appx\DistroLauncher-Appx.vcxproj (missing wlinux.exe) [fix included]

### ISSUE THREAD

**Issue by n3rd4i** [WhitewaterFoundry/WLinux#114]
**Describe the bug**
When building the project the file `wlinux.exe` is not copied where is expected to be copied but somewhere else because of a bug in the DistroLauncher-Appx project file. Also the comment which explains what is the custom build step actually explains the correct path, but different action happens, with wrong path.

**To Reproduce**
1. Open `DistroLauncher-Appx\DistroLauncher-Appx.vcxproj`
2. Go to: `<CustomBuild Include="$(targetname)">`
3. Scroll down to: `<Command>copy $(SolutionDir)$(platform)\$(Configuration)\launcher.exe $(SolutionDir)$(platform)\$(Configuration)\$(targetname).exe</Command>`

**Expected behavior**
- Expected path is: `<Command>copy $(SolutionDir)$(platform)\$(Configuration)\launcher.exe $(SolutionDir)$(platform)\$(Configuration)\$(ProjectName)\$(targetname).exe</Command>`

**Basic Troubleshooting Checklist**

[x] I have confirmed WSL is enabled: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[x] I have searched Google for the error message.
[x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[x] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[x] I have disabled and re-enabled WSL in Windows Features.
[x] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**WLinux Version**

Find: Settings->Apps->Apps & features->WLinux->Advanced Options->Version.

Insert here: 1.1.21

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:
OS Name:                   Microsoft Windows 10 Pro Insider Preview
OS Version:                10.0.18252 N/A Build 18252
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by ThatWeirdAndrew** [comment]
Pushed a fix #127
