### ISSUE TITLE
Windows path is not included after running Go installer in wlinux-setup

### ISSUE THREAD

**Issue by crramirez** [WhitewaterFoundry/WLinux#117]
Hello,

I have WLinux 1.1.20, and in my PATH the Windows PATH is not included. Recently in another machine I installed WLinux 1.1.21 and it does includes the Windows PATH. I think it is an improvement over the 1.1.20 version. My question is how I can fix this or how I can upgrade the version without wipe everything and install all over again?

Regards

**Comment by ThatWeirdAndrew** [comment]
Are you using the windows store version, or did you build it yourself?

**Comment by crramirez** [comment]
Hello,

I use Windows Store version

**Comment by ThatWeirdAndrew** [comment]
You can follow this guide to update it.

https://support.microsoft.com/en-ca/help/4026259/microsoft-store-check-updates-for-apps-and-games

**Comment by ThatWeirdAndrew** [comment]
Let me know if this fixes it.

**Comment by sirredbeard** [comment]
@ThatWeirdAndrew Updating the Windows Store app, e.g. 1.1.20 to 1.1.21 does not update the existing WLinux environment, we do not touch and existing installation as a matter of policy. That is why we introduced a self-updating wlinux-setup. Eventually wlinux-setup will be in it own's package in an apt repo that handles the upgrades consistently across builds. That is work going into 1.2 and 1.5 on the roadmap.

@crramirez So you're saying the PATH variable in Bash is not being appended automagically like WSL does with your Windows PATH settings?

**Comment by crramirez** [comment]
@sirredbeard "So you're saying the PATH variable in Bash is not being appended automagically like WSL does with your Windows PATH settings?" Exactly: echo $PATH 
/home/cramirez/bin:/bin:/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

oh.. ok I recognize this pattern. This is the result of the export added to profile by the Go installer:

export GOROOT=/usr/local/go
export GOPATH=/root/go/
export PATH=/bin:/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

In fact if I comment the last line I receive the Windows PATH again. 

I said that I will upload a fix for this weird output, but now I know that this change is urgent.

Ok so, this issus can be reproduced installing Go via wlinux-setup

**Comment by crramirez** [comment]
This pull request fix the problem:
