### ISSUE TITLE
Add a Java Development Environment Option to wlinux-setup

### ISSUE THREAD

**Issue by sirredbeard** [WhitewaterFoundry/WLinux#119]
See https://github.com/WhitewaterFoundry/WLinux/blob/master/CONTRIBUTING.md#grantsbounties for guidelines on submitting a grant proposal.

It needs to have a popular SDK, necessary command line tools, and optional GUI IDE.

See [wlinux-setup](https://github.com/WhitewaterFoundry/WLinux/blob/master/linux_files/setup).

**Comment by ThatWeirdAndrew** [comment]
Added java with #124

**Comment by sirredbeard** [comment]
@ThatWeirdAndrew  I recommend following the procedure in https://github.com/WhitewaterFoundry/WLinux/blob/master/CONTRIBUTING.md#grantsbounties if you would like a bounty. I have to have a formal procedure for fairness and transparency.

**Comment by ThatWeirdAndrew** [comment]
I don't really need a bounty. This only took me 30 minutes to do and I just copied parts of the script and edited them.
