### ISSUE TITLE
Add a bridge to Docker on Windows 10 to wlinux-setup

### ISSUE THREAD

**Issue by sirredbeard** [WhitewaterFoundry/WLinux#120]
See https://github.com/WhitewaterFoundry/WLinux/blob/master/CONTRIBUTING.md#grantsbounties for guidelines on submitting a grant proposal.

See [wlinux-setup](https://github.com/WhitewaterFoundry/WLinux/blob/master/linux_files/setup).

**Comment by sirredbeard** [comment]
I know, that is why I created this, but I need you to go through the process in CONTRIBUTING.md if you would like grant funds for it, to ensure some fairness and transparency in the process.

**Comment by sirredbeard** [comment]
@crramirez is working on this project for us and expects to have a PR by October 31.

**Comment by LemonAndroid** [comment]
@crramirez Any update? Will this be compatible with Docker Toolbox or just the new Docker Toolchain that is only compatible with Windows 10 Professional?

**Comment by crramirez** [comment]
Hello,

The feature is in testing right now. Look for a branch called docker.

Really I didn't think about Docker Toolbox. It should work if the tls is
disabled for TCP connections in docker machine . It should be a good
feature to be added in the next version.

Regards
