### ISSUE TITLE
A stupid question: how to update to latest release

### ISSUE THREAD

**Issue by aborruso** [WhitewaterFoundry/WLinux#122]
Hi all,
I have the 1.1.20 version, how to update to the 1.1.21 version?

Thank you

**Comment by sirredbeard** [comment]
The UWP wrapper around WLinux updates automatically via the Microsoft Store.

The internal WLinux environment, e.g. /, is not altered (for a handful of technical, security, and good code reasons), it must be updated by updating wlinux-setup and/or via apt.

That is why we created wlinux-setup.

Eventually wlinux-setup will be updated itself via apt.
