### ISSUE TITLE
BUILDING.md confusing

### ISSUE THREAD

**Issue by ThatWeirdAndrew** [WhitewaterFoundry/WLinux#123]
I was reading through the BUILDING.md file and I found something that might need changing. Step 1 tells you to open the solution in visual studio but Step 3 tells you to clone it from github. Shouldn't the cloning be the first thing that you do? Sorry if this is in the wrong place. I didn't know where to put it.

Andrew

**Comment by sirredbeard** [comment]
Well first you do not need to clone WLinux to start the building process at step 1, you could just as easily download a ZIP file from the GitHub page.

Second the steps given in step 3 are to clone the repo specifically to run the latest version of create-targz-x64.sh on an existing WLinux or Debian install. This is the easiest way to ensure this in the build instructions.

**Comment by ThatWeirdAndrew** [comment]
Thanks. Just wasn't clear.

**Comment by SpencerDawson** [comment]
Alternatively, users can be directed to open WSL, and cd to a directory under their windows user directory, and then clone the repo.
