### ISSUE TITLE
How to install firefox

### ISSUE THREAD

**Issue by rdmueller** [WhitewaterFoundry/WLinux#138]
I hoped it would be as easy as `sudo apt-get install firefox` but it isn't.

Can you help with some hints in the readme?

**Comment by sirredbeard** [comment]
WLinux is based on Debian stretch and some selected dev configurations are upgraded to Debian testing.

Debian stretch and testing both include firefox-esr, the extended support release version of Firefox, which you can easily get with sudo apt install firefox-esr.

The bleeding edge Firefox is only available in Debian unstable. If you want to install it via Debian repos you will need to add unstable to /etc/apt/sources.list and pin unstable in /etc/preferences.

You could also install from the tar on the Firefox website.

**Comment by rdmueller** [comment]
thanx. this seems to work!

**Comment by sirredbeard** [comment]
Glad. Let us know if you need anything else!
