### ISSUE TITLE
How do you update WLinux?

### ISSUE THREAD

**Issue by dbec** [WhitewaterFoundry/WLinux#139]
**Describe the bug**
I hate to open a bug report for this. What I really need is just a brief 'readme' on how WLinux is intended to work. I tried to run 'sudo apt-get dist-upgrade' (which I'm in the habit of doing on any new Debian installation) and got lots of dependency errors. What is the correct way to update WLinux? 

**To Reproduce**
sudo apt-get update && sudo apt-get dist-upgrade
(Answer 'y' when prompted.)

**Expected behavior**
Packages are upgraded as in a normal Debian system

**Screenshots**
dbec@DESKTOP-8AQUF13:~$ sudo apt-get update && sudo apt-get dist-upgrade
Hit:1 http://security.debian.org/debian-security stable/updates InRelease
Hit:2 https://dl.yarnpkg.com/debian stable InRelease
Hit:3 https://packages.microsoft.com/repos/azure-cli stretch InRelease
Hit:4 https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch InRelease
Hit:5 https://apt.patrickwu.ml stable InRelease
Ign:6 https://cdn-aws.deb.debian.org/debian stable InRelease
Hit:7 https://cdn-aws.deb.debian.org/debian stable-updates InRelease
Hit:8 https://cdn-aws.deb.debian.org/debian stretch-backports InRelease
Hit:9 https://cdn-aws.deb.debian.org/debian testing InRelease
Hit:10 https://cdn-aws.deb.debian.org/debian stable Release
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  libperl5.24 perl-modules-5.24
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
24 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up fontconfig (2.11.0-6.7+b1) ...
Regenerating fonts cache... failed.
See /var/log/fontconfig.log for more information.
dpkg: error processing package fontconfig (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of libpango-1.0-0:amd64:
 libpango-1.0-0:amd64 depends on fontconfig (>= 2.1.91); however:
  Package fontconfig is not configured yet.

dpkg: error processing package libpango-1.0-0:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of gtk2-engines-pixbuf:amd64:
 gtk2-engines-pixbuf:amd64 depends on libpango-1.0-0 (>= 1.28.3); however:
  Package libpango-1.0-0:amd64 is not configured yet.

dpkg: error processing package gtk2-engines-pixbuf:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libgtk2.0-0:amd64:
 libgtk2.0-0:amd64 depends on libpango-1.0-0 (>= 1.28.3); however:
  Package libpango-1.0-0:amd64 is not configured yet.

dpkg: error processing package libgtk2.0-0:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of gtk2-engines-murrine:amd64:
 gtk2-engines-murrine:amd64 depends on libgtk2.0-0 (>= 2.24.5-4); however:
  Package libgtk2.0-0:amd64 is not configured yet.
 gtk2-engines-murrine:amd64 depends on libpango-1.0-0 (>= 1.14.0); however:
  Package libpango-1.0-0:amd64 is not configured yet.

dpkg: error processing package gtk2-engines-murrine:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libgail18:amd64:
 libgail18:amd64 depends on libgtk2.0-0 (= 2.24.31-2); however:
  Package libgtk2.0-0:amd64 is not configured yet.
 libgail18:amd64 depends on libpango-1.0-0 (>= 1.28.3); however:
  Package libpango-1.0-0:amd64 is not configured yet.

dpkg: error processing package libgail18:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of librsvg2-2:amd64:
 librsvg2-2:amd64 depends on libpango-1.0-0 (>= 1.36.0); however:
  Package libpango-1.0-0:amd64 is not configured yet.

dpkg: error processing package librsvg2-2:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of murrine-themes:
 murrine-themes depends on gtk2-engines-murrine (>= 0.98); however:
  Package gtk2-engines-murrine:amd64 is not configured yet.

dpkg: error processing package murrine-themes (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of albatross-gtk-theme:
 albatross-gtk-theme depends on gtk2-engines-murrine (>= 0.98); however:
  Package gtk2-engines-murrine:amd64 is not configured yet.

dpkg: error processing package albatross-gtk-theme (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of greybird-gtk-theme:
 greybird-gtk-theme depends on gtk2-engines-murrine (>= 0.98); however:
  Package gtk2-engines-murrine:amd64 is not configured yet.

dpkg: error processing package greybird-gtk-theme (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libgail-common:amd64:
 libgail-common:amd64 depends on libgail18 (= 2.24.31-2); however:
  Package libgail18:amd64 is not configured yet.
 libgail-common:amd64 depends on libgtk2.0-0 (>= 2.24.0); however:
  Package libgtk2.0-0:amd64 is not configured yet.
 libgail-common:amd64 depends on libpango-1.0-0 (>= 1.28.3); however:
  Package libpango-1.0-0:amd64 is not configured yet.

dpkg: error processing package libgail-common:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bluebird-gtk-theme:
 bluebird-gtk-theme depends on gtk2-engines-murrine (>= 0.98); however:
  Package gtk2-engines-murrine:amd64 is not configured yet.

dpkg: error processing package bluebird-gtk-theme (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libpangocairo-1.0-0:amd64:
 libpangocairo-1.0-0:amd64 depends on libpango-1.0-0 (>= 1.37.5); however:
  Package libpango-1.0-0:amd64 is not configured yet.

dpkg: error processing package libpangocairo-1.0-0:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libgtk-3-0:amd64:
 libgtk-3-0:amd64 depends on libpango-1.0-0 (>= 1.37.5); however:
  Package libpango-1.0-0:amd64 is not configured yet.
 libgtk-3-0:amd64 depends on libpangocairo-1.0-0 (>= 1.37.3); however:
  Package libpangocairo-1.0-0:amd64 is not configured yet.

dpkg: error processing package libgtk-3-0:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of librsvg2-common:amd64:
 librsvg2-common:amd64 depends on librsvg2-2 (= 2.40.16-1+b1); however:
  Package librsvg2-2:amd64 is not configured yet.

dpkg: error processing package librsvg2-common:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libpangoft2-1.0-0:amd64:
 libpangoft2-1.0-0:amd64 depends on libpango-1.0-0 (>= 1.37.2); however:
  Package libpango-1.0-0:amd64 is not configured yet.

dpkg: error processing package libpangoft2-1.0-0:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libgtk-3-bin:
 libgtk-3-bin depends on libgtk-3-0 (>= 3.22.11-1); however:
  Package libgtk-3-0:amd64 is not configured yet.
 libgtk-3-bin depends on libpango-1.0-0 (>= 1.37.3); however:
  Package libpango-1.0-0:amd64 is not configured yet.
 libgtk-3-bin depends on libpangocairo-1.0-0 (>= 1.37.3); however:
  Package libpangocairo-1.0-0:amd64 is not configured yet.
 libgtk-3-bin depends on libpangoft2-1.0-0 (>= 1.37.3); however:
  Package libpangoft2-1.0-0:amd64 is not configured yet.

dpkg: error processing package libgtk-3-bin (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of openjdk-8-jre:amd64:
 openjdk-8-jre:amd64 depends on libgtk-3-0; however:
  Package libgtk-3-0:amd64 is not configured yet.

dpkg: error processing package openjdk-8-jre:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libatk-wrapper-java-jni:amd64:
 libatk-wrapper-java-jni:amd64 depends on libgtk-3-0 (>= 3.0.0); however:
  Package libgtk-3-0:amd64 is not configured yet.
 libatk-wrapper-java-jni:amd64 depends on libgtk2.0-0 (>= 2.8.0); however:
  Package libgtk2.0-0:amd64 is not configured yet.
 libatk-wrapper-java-jni:amd64 depends on libpango-1.0-0 (>= 1.14.0); however:
  Package libpango-1.0-0:amd64 is not configured yet.
 libatk-wrapper-java-jni:amd64 depends on libpangocairo-1.0-0 (>= 1.14.0); however:
  Package libpangocairo-1.0-0:amd64 is not configured yet.

dpkg: error processing package libatk-wrapper-java-jni:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of blackbird-gtk-theme:
 blackbird-gtk-theme depends on gtk2-engines-murrine (>= 0.98); however:
  Package gtk2-engines-murrine:amd64 is not configured yet.

dpkg: error processing package blackbird-gtk-theme (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of adwaita-icon-theme:
 adwaita-icon-theme depends on librsvg2-common; however:
  Package librsvg2-common:amd64 is not configured yet.

dpkg: error processing package adwaita-icon-theme (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libgtk2.0-bin:
 libgtk2.0-bin depends on libgtk2.0-0 (= 2.24.31-2); however:
  Package libgtk2.0-0:amd64 is not configured yet.

dpkg: error processing package libgtk2.0-bin (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of gnome-themes-standard:amd64:
 gnome-themes-standard:amd64 depends on libgtk2.0-0 (>= 2.24.15); however:
  Package libgtk2.0-0:amd64 is not configured yet.

dpkg: error processing package gnome-themes-standard:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of openjdk-8-jdk:amd64:
 openjdk-8-jdk:amd64 depends on openjdk-8-jre (= 8u181-b13-2~deb9u1); however:
  Package openjdk-8-jre:amd64 is not configured yet.

dpkg: error processing package openjdk-8-jdk:amd64 (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 fontconfig
 libpango-1.0-0:amd64
 gtk2-engines-pixbuf:amd64
 libgtk2.0-0:amd64
 gtk2-engines-murrine:amd64
 libgail18:amd64
 librsvg2-2:amd64
 murrine-themes
 albatross-gtk-theme
 greybird-gtk-theme
 libgail-common:amd64
 bluebird-gtk-theme
 libpangocairo-1.0-0:amd64
 libgtk-3-0:amd64
 librsvg2-common:amd64
 libpangoft2-1.0-0:amd64
 libgtk-3-bin
 openjdk-8-jre:amd64
 libatk-wrapper-java-jni:amd64
 blackbird-gtk-theme
 adwaita-icon-theme
 libgtk2.0-bin
 gnome-themes-standard:amd64
 openjdk-8-jdk:amd64
E: Sub-process /usr/bin/dpkg returned an error code (1)
dbec@DESKTOP-8AQUF13:~$

![2018-11-02 4](https://user-images.githubusercontent.com/10676646/47928403-3b868d80-de94-11e8-92c9-90304a40c44e.png)
![2018-11-02 3](https://user-images.githubusercontent.com/10676646/47928404-3b868d80-de94-11e8-843f-921741501b41.png)
![2018-11-02 2](https://user-images.githubusercontent.com/10676646/47928407-3b868d80-de94-11e8-8b65-2d6d937a0af9.png)
![2018-11-02 1](https://user-images.githubusercontent.com/10676646/47928408-3b868d80-de94-11e8-98cc-fd088c87431d.png)
![2018-11-02](https://user-images.githubusercontent.com/10676646/47928409-3b868d80-de94-11e8-8d72-af25423f2a85.png)

**Additional context**
This may or may not be related, but when I initially ran WLinux for the first time and ran setup, it asked me if I wanted to download and install the latest version of setup. I said 'yes' and it flashed a terminal screen that ostensibly installed the latest version (it was too fast to see for sure), then I proceeded with the setup - and was once again prompted to download/install the latest version of setup. This continued in a loop until I finally answered 'no' and continued running setup. 

**Basic Troubleshooting Checklist**

[X ] I have confirmed WSL is enabled: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[X ] I have searched Google for the error message.
[X ] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[X ] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[ ] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[ ] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**WLinux Version**

Find: Settings->Apps->Apps & features->WLinux->Advanced Options->Version.

Insert here:
1.1.23.0

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:
Microsoft Windows [Version 10.0.17134.345]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>systeminfo | findstr /C:"OS"
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17134 N/A Build 17134
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              American Megatrends Inc. F20, 11/11/2016

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by patrick330602** [comment]
Can you post your /var/log/fontconfig.log? Also, this is already mentioned in #109 and it seems to be a upstream issue. This do occur to people but this is really hard to reproduce and trace.

**Comment by patrick330602** [comment]
@dbec do you still have the problem?

**Comment by dbec** [comment]
@patrick330602 Sorry for delay -- still have the problem. I've attached /var/log/fontconfig.log. 

[fontconfig.log](https://github.com/WhitewaterFoundry/WLinux/files/2554043/fontconfig.log)

Any last things I should try before blowing away WSL and re-installing?

**Comment by patrick330602** [comment]
can you complete these steps? https://github.com/WhitewaterFoundry/WLinux/issues/109#issuecomment-429884954 Also in #109 people mentions they solve the problem some times after the issue occur.

**Comment by dbec** [comment]
OK, I followed this step:
 I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset.
Confusingly, under the heading Reset there is a Repair button and a Reset button. The Repair sounded less drastic (preserving data) so I chose that. I went back into WLinux and run 'apt-get update' and 'apt-get dist-upgrade' and everything proceeded without error:
root@C1BWPFDJMVD201:~# apt-get update && apt-get dist-upgrade
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://security.ubuntu.com/ubuntu bionic-security InRelease [83.2 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:5 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [193 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [424 kB]
Get:7 http://security.ubuntu.com/ubuntu bionic-security/main Translation-en [76.3 kB]
Get:8 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [93.3 kB]
Get:9 http://security.ubuntu.com/ubuntu bionic-security/universe Translation-en [51.3 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic-updates/main Translation-en [160 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [572 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic-updates/universe Translation-en [153 kB]
Fetched 1969 kB in 9s (227 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following NEW packages will be installed:
  libuv1
The following packages will be upgraded:
  kmod libkmod2 libnss-systemd libpam-systemd libsystemd0 libudev1 lxd lxd-client openssh-client openssh-server openssh-sftp-server python3-distupgrade systemd systemd-sysv
  ubuntu-release-upgrader-core udev
16 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 13.9 MB of archives.
After this operation, 360 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libnss-systemd amd64 237-3ubuntu10.4 [105 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libsystemd0 amd64 237-3ubuntu10.4 [204 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libpam-systemd amd64 237-3ubuntu10.4 [108 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 systemd amd64 237-3ubuntu10.4 [2897 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 udev amd64 237-3ubuntu10.4 [1100 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libudev1 amd64 237-3ubuntu10.4 [53.8 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 kmod amd64 24-1ubuntu3.1 [88.7 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libkmod2 amd64 24-1ubuntu3.1 [40.0 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 systemd-sysv amd64 237-3ubuntu10.4 [11.7 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 openssh-sftp-server amd64 1:7.6p1-4ubuntu0.1 [45.5 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 openssh-server amd64 1:7.6p1-4ubuntu0.1 [332 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 openssh-client amd64 1:7.6p1-4ubuntu0.1 [612 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 ubuntu-release-upgrader-core all 1:18.04.28 [24.6 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 python3-distupgrade all 1:18.04.28 [106 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic/main amd64 libuv1 amd64 1.18.0-3 [64.4 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 lxd amd64 3.0.2-0ubuntu1~18.04.1 [5109 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 lxd-client amd64 3.0.2-0ubuntu1~18.04.1 [3004 kB]
Fetched 13.9 MB in 1min 32s (151 kB/s)
Preconfiguring packages ...
(Reading database ... 28567 files and directories currently installed.)
Preparing to unpack .../libnss-systemd_237-3ubuntu10.4_amd64.deb ...
Unpacking libnss-systemd:amd64 (237-3ubuntu10.4) over (237-3ubuntu10.3) ...
Preparing to unpack .../libsystemd0_237-3ubuntu10.4_amd64.deb ...
Unpacking libsystemd0:amd64 (237-3ubuntu10.4) over (237-3ubuntu10.3) ...
Setting up libsystemd0:amd64 (237-3ubuntu10.4) ...
(Reading database ... 28567 files and directories currently installed.)
Preparing to unpack .../libpam-systemd_237-3ubuntu10.4_amd64.deb ...
Unpacking libpam-systemd:amd64 (237-3ubuntu10.4) over (237-3ubuntu10.3) ...
Preparing to unpack .../systemd_237-3ubuntu10.4_amd64.deb ...
Unpacking systemd (237-3ubuntu10.4) over (237-3ubuntu10.3) ...
Preparing to unpack .../udev_237-3ubuntu10.4_amd64.deb ...
Unpacking udev (237-3ubuntu10.4) over (237-3ubuntu10.3) ...
Preparing to unpack .../libudev1_237-3ubuntu10.4_amd64.deb ...
Unpacking libudev1:amd64 (237-3ubuntu10.4) over (237-3ubuntu10.3) ...
Setting up libudev1:amd64 (237-3ubuntu10.4) ...
(Reading database ... 28567 files and directories currently installed.)
Preparing to unpack .../kmod_24-1ubuntu3.1_amd64.deb ...
Unpacking kmod (24-1ubuntu3.1) over (24-1ubuntu3) ...
Preparing to unpack .../libkmod2_24-1ubuntu3.1_amd64.deb ...
Unpacking libkmod2:amd64 (24-1ubuntu3.1) over (24-1ubuntu3) ...
Setting up libkmod2:amd64 (24-1ubuntu3.1) ...
Setting up systemd (237-3ubuntu10.4) ...
Initializing machine ID from random generator.
(Reading database ... 28567 files and directories currently installed.)
Preparing to unpack .../0-systemd-sysv_237-3ubuntu10.4_amd64.deb ...
Unpacking systemd-sysv (237-3ubuntu10.4) over (237-3ubuntu10.3) ...
Preparing to unpack .../1-openssh-sftp-server_1%3a7.6p1-4ubuntu0.1_amd64.deb ...
Unpacking openssh-sftp-server (1:7.6p1-4ubuntu0.1) over (1:7.6p1-4) ...
Preparing to unpack .../2-openssh-server_1%3a7.6p1-4ubuntu0.1_amd64.deb ...
Unpacking openssh-server (1:7.6p1-4ubuntu0.1) over (1:7.6p1-4) ...
Preparing to unpack .../3-openssh-client_1%3a7.6p1-4ubuntu0.1_amd64.deb ...
Unpacking openssh-client (1:7.6p1-4ubuntu0.1) over (1:7.6p1-4) ...
Preparing to unpack .../4-ubuntu-release-upgrader-core_1%3a18.04.28_all.deb ...
Unpacking ubuntu-release-upgrader-core (1:18.04.28) over (1:18.04.27) ...
Preparing to unpack .../5-python3-distupgrade_1%3a18.04.28_all.deb ...
Unpacking python3-distupgrade (1:18.04.28) over (1:18.04.27) ...
Selecting previously unselected package libuv1:amd64.
Preparing to unpack .../6-libuv1_1.18.0-3_amd64.deb ...
Unpacking libuv1:amd64 (1.18.0-3) ...
Preparing to unpack .../7-lxd_3.0.2-0ubuntu1~18.04.1_amd64.deb ...
invoke-rc.d: could not determine current runlevel
Stopping Container hypervisor based on LXC: (not running).
Unpacking lxd (3.0.2-0ubuntu1~18.04.1) over (3.0.1-0ubuntu1~18.04.1) ...
Preparing to unpack .../8-lxd-client_3.0.2-0ubuntu1~18.04.1_amd64.deb ...
Unpacking lxd-client (3.0.2-0ubuntu1~18.04.1) over (3.0.1-0ubuntu1~18.04.1) ...
Setting up libnss-systemd:amd64 (237-3ubuntu10.4) ...
Processing triggers for ufw (0.35-5) ...
Setting up kmod (24-1ubuntu3.1) ...
Installing new version of config file /etc/modprobe.d/blacklist.conf ...
Processing triggers for ureadahead (0.100.0-20) ...
Setting up libuv1:amd64 (1.18.0-3) ...
Setting up systemd-sysv (237-3ubuntu10.4) ...
Setting up lxd-client (3.0.2-0ubuntu1~18.04.1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Setting up udev (237-3ubuntu10.4) ...
invoke-rc.d: could not determine current runlevel
update-initramfs: deferring update (trigger activated)
Processing triggers for systemd (237-3ubuntu10.4) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for dbus (1.12.2-1ubuntu1) ...
Setting up openssh-client (1:7.6p1-4ubuntu0.1) ...
Setting up python3-distupgrade (1:18.04.28) ...
Setting up libpam-systemd:amd64 (237-3ubuntu10.4) ...
Setting up lxd (3.0.2-0ubuntu1~18.04.1) ...
invoke-rc.d: could not determine current runlevel
Setting up ubuntu-release-upgrader-core (1:18.04.28) ...
Setting up openssh-sftp-server (1:7.6p1-4ubuntu0.1) ...
Setting up openssh-server (1:7.6p1-4ubuntu0.1) ...
Creating SSH2 RSA key; this may take some time ...
2048 SHA256:SytBOMmDm+m6LoMkQOY9R6vMlu3CutPBZIsYUBF1it0 root@C1BWPFDJMVD201 (RSA)
Creating SSH2 ECDSA key; this may take some time ...
256 SHA256:pdyguN+6mMMwtgeupaI3MmChaExkHLqmY795N6LApu4 root@C1BWPFDJMVD201 (ECDSA)
Creating SSH2 ED25519 key; this may take some time ...
256 SHA256:xQx1h+YbgPxsI8gyC5Y3H/TgQ9oguLSbwBSJikQqUhY root@C1BWPFDJMVD201 (ED25519)
invoke-rc.d: could not determine current runlevel
Processing triggers for initramfs-tools (0.130ubuntu3.5) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...

**Comment by dbec** [comment]
@patrick330602  Thanks for your help!
