### ISSUE TITLE
Add fzf

### ISSUE THREAD

**Issue by LemonAndroid** [WhitewaterFoundry/WLinux#14]
The `ctrl+r` replacement w/ fuzzy search is especially useful.

**Comment by LemonAndroid** [comment]
Sorry to be so blatant, but: It's of no use. it's easier to remember to google and install the fzf with the one liner they provide than remembering how to use this script.

**Comment by sirredbeard** [comment]
Well it is just here for testing for a bit and if it checks out then we will move into the main build image, just like with pip.

I really do appreciate your feedback, these packages will likely get included because of you, I am just going to do some testing on them for a couple days first.

**Comment by LemonAndroid** [comment]
I imagine the script to not fully instsall it, since it asks for `y` confirmation several times. I didn't test it yet though. Have to uninstall WLinux again first.

**Comment by sirredbeard** [comment]
The fsf is still in optional scripts and will probably not be shipped in default install **but** we are including it in the new OOBE setup to enable, see #36.

**Comment by LemonAndroid** [comment]
I feel like i wasted 10$. Not that big of a deal, I waste money on a regular basis but not having this stuff directly accessible puts a huge damper on the fun of using WLinux.

**Comment by sirredbeard** [comment]
I am sorry you feel that way.

If I recall correctly you filed 4 package requests.

Within a couple hours one, neovim, had been pushed into the main image.

One was not available in an apt anywhere, but @patrick330602 made one for you on his personal apt.

Two more package requests, also not made available by developers in an apt anywhere, have been in testing in scripts for a couple days.

We are fleshing out our new OOBE specifically to address some concerns you raised, while also navigating this package issues.

Sadly we have not been able to solve packaging issues in Linux, to my knowledge no single distro has.

Please forward your purchase confirmation e-mail from Microsoft Store to hayden @ whitewaterfoundry.com and your PayPal or Zelle details I will see that you are refunded personally.

**Comment by LemonAndroid** [comment]
@sirredbeard I don't care about a refund, but I would've bought it again on my other machine now. As I understand, it can be integrated in the default image, but you choose not to. 

Also, you see how the pov of me getting all these packages is not the whole picture?
