### ISSUE TITLE
Can not change keyboard layout in gnome-terminal

### ISSUE THREAD

**Issue by davidwincent** [WhitewaterFoundry/WLinux#141]
**Describe the bug**
Windows input locale = sv (Swedish)
Wlinux bash input locale = sv (Swedish)
gnome-terminal input locale = English, i want to change this to swedish

**To Reproduce**
1. Start Xming with parameters " :0 -clipboard -multiwindow -xkblayout sv"
2. Start WLinux bash
3. `sudo apt update && sudo apt install gnome-terminal`
4. `gnome-terminal`
5. see that the input locale is English only 

**Expected behavior**
Input locale should match system default

**Basic Troubleshooting Checklist**

[X] I have confirmed WSL is enabled: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[X] I have searched Google for the error message.
[X] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[X] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[X] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[X] I have disabled and re-enabled WSL in Windows Features.
[X] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?
Tried changing gnome input sources with:
`gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'sv')]"`

Tried installing gnome-control-center with:
`sudo apt install gnome-control-center`
Got
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gnome-control-center : Depends: libcheese-gtk25 (>= 3.18.0) but it is not going to be installed
                        Depends: libcheese8 (>= 3.18.0) but it is not going to be installed
                        Depends: libgoa-backend-1.0-1 (>= 3.10.0) but it is not going to be installed
                        Recommends: gnome-online-accounts but it is not going to be installed
                        Recommends: gnome-user-guide but it is not going to be installed
                        Recommends: system-config-printer-common (>= 1.4) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Insert here:

WLinux version: 1.1.23.0

Insert here:

Windows version: Windows 10 Pro 1803

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:
```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17134 N/A Build 17134
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              AMI 80.07, 12/26/2014
```

**Comment by davidwincent** [comment]
Problem solved.
If I change xkblayout to fi (finnish) it works!

See https://superuser.com/questions/377586/why-is-my-keyboard-mapping-wrong-with-xming-lubuntu-in-virtualbox-and-putty

**Comment by sirredbeard** [comment]
Interesting bug. Even if you fixed it, it is good to know, thank you for reporting.

**Comment by sirredbeard** [comment]
This actually gives me some ideas, thank you again.
