### ISSUE TITLE
Add "n" node version manager to default image

### ISSUE THREAD

**Issue by LemonAndroid** [WhitewaterFoundry/WLinux#15]

**Comment by LemonAndroid** [comment]
Is it not possible to add it via the git based `make install` script?

**Comment by sirredbeard** [comment]
It probably is possible but right now the build system has been kept simple enough to avoid that level of complexity. I am very keen on maintaining simplicity. When you introduce make scripts we will have to introduce new layers for error handling, tracking build dependencies, and we will probably get there, but I want to find the simplest solution. Right now that tends to be letting apt hande things, even if we have to rely on custom apt servers. Providing an apt repo might also actually be a nice way to give back to the larger Linux community beyond WLinux.

**Comment by patrick330602** [comment]
@sirredbeard is right. The point to make a deb package is to keep it simple and can easily be updated. using git script is possible, but it is not clean and easily fell into the permission hole. We can still provide a install script if you want.

**Comment by patrick330602** [comment]
![image](https://user-images.githubusercontent.com/15316889/45935331-f80b4a80-bfdc-11e8-8181-71bfb8477043.png)

n is now live in apt.patrickwu.ml. you can install now if you use WLinux, i will create a PR for pre-installation.

**Comment by sirredbeard** [comment]
I am closing this for now.

Please re-open if there are any problems in the future.
