### ISSUE TITLE
'No such interface supported' error

### ISSUE THREAD

**Issue by Bodup** [WhitewaterFoundry/WLinux#150]
**Describe the bug**
On initial setup, while configuring the username, any input resulted in "No such interface supported"
I tried relaunching the app but it closes instantly. Running it from the command line gives me the same "No such interface supported" error again.

**To Reproduce**
- Fresh install on Windows 10 Pro
- Open Wlinux

**Expected behavior**
A WLinux bash prompt

**Screenshot**

https://imgur.com/a/GCI00Mq

**Additional context**
Hypervisor-Code integrity seems to have encountered some errors but I can't reproduce the error by launching Wlinux. Might be related.
`Code Integrity was unable to verify a page for a module verified using hypervisor enforcement. Status 0xC0000022.`

**Basic Troubleshooting Checklist**

[x ] I have confirmed WSL is enabled: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[x] I have searched Google for the error message.
[x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[x] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[x] I have disabled and re-enabled WSL in Windows Features.
[x] I have run Windows 10 updates and restarted.

**WLinux Version**

1.1.23.0

**Windows Build**

18272.1000

**Comment by sirredbeard** [comment]
This is a [known bug](https://github.com/Microsoft/WSL/issues/3645) in Windows 10 build 18272.

It affects all WSL distros.

The solution is to update to build 18277 which came out today.

**Comment by Bodup** [comment]
Oops. I've looked for it on the open issues list but apparently I missed it.

**Comment by sirredbeard** [comment]
That is fine, it happens. Let us know if you need help with anything else.
