### ISSUE TITLE
Upon running build.bat get error: "master\x64\install.tar.gz' does not exist."

### ISSUE THREAD

**Issue by stcobb** [WhitewaterFoundry/WLinux#151]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(2753,5): error APPX0702: Payload file 'c:\WLinux-master\WLinux-
       master\x64\install.tar.gz' does not exist. [c:\WLinux-master\WLinux-master\DistroLauncher-Appx\DistroLauncher-Appx.vcxproj]

**To Reproduce**
1. Run build.bat
2. See error

**Expected behavior**
Build to run cleanly.

**Additional context**
Before this I had to manually provide temporary PFX file. Also had to copy wlinux.exe to C:\WLinux-master\WLinux-master\x64\Debug\DistroLauncher-Appx folder to correct a different error.

**Basic Troubleshooting Checklist**

[ X] I have searched Google for the error message.
[ X] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[ X] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.

**WLinux Version**

1.1.22 - Submission 6

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17134 N/A Build 17134
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              Dell Inc. 1.8.0, 7/18/2018
For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by sirredbeard** [comment]
Did you run create-targz-x64.sh on an existing Debian or WLinux install to create your base image and then copy it over? See step 3 in [BUILDING.md](https://github.com/WhitewaterFoundry/WLinux/blob/master/BUILDING.md#build-process).

**Comment by sirredbeard** [comment]
Closed for lack of response. If you are still encountering issues, please reply and we can re-open.
