### ISSUE TITLE
wlinux-setup loops upgrade prompt unnecessarily

### ISSUE THREAD

**Issue by doubleyewdee** [WhitewaterFoundry/WLinux#152]
The "upgrade first" prompt in wlinux-setup appears after you've already taken the step to upgrade it. Should probably not do that.

After you run the upgrade it should relaunch itself with some flag (command line or env var maybe?) that bypasses the upgrade prompt. This is a very small usability/polish thing but it'd be nice.

**Comment by sirredbeard** [comment]
I like that idea. We should think of an elegant way to implement it.

**Comment by pkmorrison** [comment]
I encountered the same problem this AM. No setup was displayed. I perceived a
flash from console output that was posssibly? a permissions problem.
Tried to run with sudo, but it could not find the wlinux-setup command.
I searched with find and could not locate wlinux-setup - where does it reside?

**Comment by sirredbeard** [comment]
wlinux-setup is /etc/setup.

Which shell are you using by chance?

**Comment by pkmorrison** [comment]
dash

**Comment by pkmorrison** [comment]
I poked around a little more and found this by redirecting stderr to a file:

Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/home/pete/.wget-hsts'. HSTS will be disabled.
--2018-11-10 04:39:48--  https://raw.githubusercontent.com/WhitewaterFoundry/WLinux/master/linux_files/setup
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 29564 (29K) [text/plain]
Saving to: ‘setup’

     0K .......... .......... ........                        100% 2.12M=0.01s

2018-11-10 04:39:48 (2.12 MB/s) - ‘setup’ saved [29564/29564]

rm: cannot remove '/home/pete/.firstrun': No such file or directory

**Comment by pkmorrison** [comment]
"Never mind!" says Rosanne Rosannadanna.
I got it to work by exiting out of the root account.
It is now busily downloading and installing stuff.
Sorry for the noise.

**Comment by ThatWeirdAndrew** [comment]
How about if the script sets a variable after an update and when the script is first run it checks for that variable. If it's 1, it skips the update prompt, but if it's 0, it prompts to update the script. Before the script closes, it resets the variable back to 0.

**Comment by sirredbeard** [comment]
So we did do this early on but I pulled it before we pushed wlinux-setup as default. We passed a command-line variable to the re-launch of wlinux-setup. It was very unreliable though. I think it's a good idea and I am open to reconsidering now that rest of wlinux-setup has stabilized and we can test this one feature without worrying too much about getting distracted by other bugs in the process, which was a factor last time we tackled this. We could try the command line argument again or just the existence of a .update file in ~ could be the flag to wlinux-setup we just got updated and to jump straight to wlinux-setup, that has proven reliable in handling the wlinux-setup first run message.

**Comment by sirredbeard** [comment]
I found maintaining environmental variables across wlinux-setup instances to make troubleshooting more difficult, even if it is technically more advanced or more correct than using files.

I also tend to have multiple instances of bash open and having to exec bash on all of them to be sure the variables auto-populate before I re-run a script is a pain.

My proposal:

Right now the absence of .firstrun prompts a message and touches .firstrun in /etc/profile and the file exists persistently.

In wlinux-setup the absence of .updated would prompt the current do you want to upgrade? message. If the user chose to update, updated script would be downloaded and installed, .updated would be touched, and wlinux-setup re-run.

In wlinux-setup the then presence of .updated would skip the do you want to upgrade? message, rm .updated, and go straight to main menu.

**Comment by RodriguesCosta** [comment]
I think checking this through arguments would be ideal.

Follow my proposal.

[setup.sh.txt](https://github.com/WhitewaterFoundry/WLinux/files/2574177/setup.sh.txt)

**Comment by chenjuntong** [comment]
> I poked around a little more and found this by redirecting stderr to a file:
> 
> Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
> ERROR: could not open HSTS store at '/home/pete/.wget-hsts'. HSTS will be disabled.
> --2018-11-10 04:39:48-- https://raw.githubusercontent.com/WhitewaterFoundry/WLinux/master/linux_files/setup
> Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
> Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 29564 (29K) [text/plain]
> Saving to: ‘setup’
> 
> ```
>  0K .......... .......... ........                        100% 2.12M=0.01s
> ```
> 2018-11-10 04:39:48 (2.12 MB/s) - ‘setup’ saved [29564/29564]
> 
> rm: cannot remove '/home/pete/.firstrun': No such file or directory

I have the same problem. How can I escape the loop? Thank you!

Starting wlinux-setup.
Saving current directory as $CURDIR
Going to $TMPDIR: /tmp/tmp.B9bbG1KxEK
Backing up old /etc/setup to /etc/setup.old
Getting fresh setup from GitHub
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/home/chenjuntong/.wget-hsts'. HSTS will be disabled.
--2018-11-14 22:34:02--  https://raw.githubusercontent.com/WhitewaterFoundry/WLinux/master/linux_files/setup
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.228.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.228.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 30065 (29K) [text/plain]
Saving to: ‘setup’

setup                                 100%[=========================================================================>]  29.36K   107KB/s    in 0.3s

2018-11-14 22:34:03 (107 KB/s) - ‘setup’ saved [30065/30065]

Running updated wlinux-setup
Starting wlinux-setup.
Saving current directory as $CURDIR
Going to $TMPDIR: /tmp/tmp.PTbjI1q9L1

**Comment by ThatWeirdAndrew** [comment]
> > I poked around a little more and found this by redirecting stderr to a file:
> > Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
> > ERROR: could not open HSTS store at '/home/pete/.wget-hsts'. HSTS will be disabled.
> > --2018-11-10 04:39:48-- [/linux_files/setup@`master` (raw)](https://raw.githubusercontent.com/WhitewaterFoundry/WLinux/master/linux_files/setup)
> > Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
> > Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
> > HTTP request sent, awaiting response... 200 OK
> > Length: 29564 (29K) [text/plain]
> > Saving to: ‘setup’
> > ```
> >  0K .......... .......... ........                        100% 2.12M=0.01s
> > ```
> > 2018-11-10 04:39:48 (2.12 MB/s) - ‘setup’ saved [29564/29564]
> > rm: cannot remove '/home/pete/.firstrun': No such file or directory
> 
> I have the same problem. How can I escape the loop? Thank you!
> 
> Starting wlinux-setup.
> Saving current directory as $CURDIR
> Going to $TMPDIR: /tmp/tmp.B9bbG1KxEK
> Backing up old /etc/setup to /etc/setup.old
> Getting fresh setup from GitHub
> Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
> ERROR: could not open HSTS store at '/home/chenjuntong/.wget-hsts'. HSTS will be disabled.
> --2018-11-14 22:34:02-- [/linux_files/setup@`master` (raw)](https://raw.githubusercontent.com/WhitewaterFoundry/WLinux/master/linux_files/setup)
> Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.228.133
> Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.228.133|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 30065 (29K) [text/plain]
> Saving to: ‘setup’
> 
> setup 100%[=========================================================================>] 29.36K 107KB/s in 0.3s
> 
> 2018-11-14 22:34:03 (107 KB/s) - ‘setup’ saved [30065/30065]
> 
> Running updated wlinux-setup
> Starting wlinux-setup.
> Saving current directory as $CURDIR
> Going to $TMPDIR: /tmp/tmp.PTbjI1q9L1

This is a known issue with the wlinux-setup program and we're looking for a way to fix it.

**Comment by sirredbeard** [comment]
I think the HSTS issue when wlinux-setup is updated and the proposal to have wlinux-setup skip the update prompt (via variables or files) are two different issues, right?

**Comment by ThatWeirdAndrew** [comment]
When I looked over it, it seemed to me like he was asking about both issues.
