### ISSUE TITLE
gnutls_handshake() failed: Error in the push function.

### ISSUE THREAD

**Issue by vitor-adonai** [WhitewaterFoundry/WLinux#153]
**Describe the bug**
When I'm going to install any apt-get package, I get error:
gnutls_handshake() failed: Error in the push function.
With this error code, I only encounter problems related to Git.
Some solutions (Google result) ask me to install other dependencies to fix this error.
 But I can not use sudo apt-get install appname

**To Reproduce**
sudo apt-get install apache2

**Expected behavior**
When I'm going to install any apt-get package, I get error:
gnutls_handshake() failed: Error in the push function.

**Screenshots**
![image](https://user-images.githubusercontent.com/3422808/48175938-2925ad00-e2f5-11e8-9a05-becb6122a49f.png)

**Basic Troubleshooting Checklist**

[Y] I have confirmed WSL is enabled: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[Y] I have searched Google for the error message.
[Y] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[Y] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[Y] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[Y] I have disabled and re-enabled WSL in Windows Features.
[Y] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**WLinux Version**
1.1.23.0

**Comment by sirredbeard** [comment]
Are you behind some kind of firewall or proxy?

**Comment by vitor-adonai** [comment]
Kaspersky Total Security.
 You reminded me that I had problems with Docker, Kaspersky blocked the operation (without any alerts).
 I'm going to open a support ticket, I'll get back as soon as possible.
 Thank u!

**Comment by vitor-adonai** [comment]
Hi.
I was informed by the Kaspersky team that this is not a Kaspersky lock problem.
"We verified and analyzed the image with the information forwarded, and said that Kaspersky is not blocking the communication because the problem is related to GNU itself."

I also did tests disabling and removing Kaspersky from my machine. The error persists.

**Comment by sirredbeard** [comment]
You are sure you are not behind a proxy, firewall, or on an ISP that messes with TLS traffic?

Have you tried connecting to another network/ISP to see if you can duplicate it there?

Have you tried running `$ sudo apt update `and `$ sudo apt upgrade -y`?

Would you try `$ sudo apt -t testing install libgnutls-openssl git -y` ?

One alternative would be rebuilding gnutls with openssl but that seems drastic.

**Comment by vitor-adonai** [comment]
You're absolutely right.
I ended up uninstalling Kaspersky (again, lol). I tried again and was able to run the apache2 installation.
 I installed Kaspersky and the problem came back.

 Thanks for the support, maybe I have tested Wlinux before restarting Windows to complete the uninstallation of Kaspersky.

**Comment by haratmalli** [comment]
It may cause by internet issue

**Comment by biggy970** [comment]
> .

it is not working
