### ISSUE TITLE
Icon location

### ISSUE THREAD

**Issue by Morgy93** [WhitewaterFoundry/WLinux#156]
Hello,

this is not your usual issue, but since I paid for it and couldn't find another way to get support I thought it would be okay.

Basically I'd like to know where the program icon is stored, since I want to use it as tab icon within ConEmu. (`conemu.exe […] -icon "path-to-tab-icon"`)

Hope to get some answer.

**Comment by sirredbeard** [comment]
Great! See https://github.com/WhitewaterFoundry/WLinux/tree/master/DistroLauncher/images and https://github.com/WhitewaterFoundry/WLinux/tree/master/DistroLauncher-Appx/Assets for various visual assets you can re-use.

**Comment by Morgy93** [comment]
@sirredbeard Thanks for your reply.
Just to be clear - is this stored anywhere on my disk already, so I can use it right away?
