### ISSUE TITLE
Installing the latest R (3.5.1) on WLinux

### ISSUE THREAD

**Issue by transcriptomics** [WhitewaterFoundry/WLinux#157]
**Describe the bug**
Using "apt install r-base" I get the older R version 3.3.3 installed from Debian default repository. I tried to install latest R (3.5.1) using instructions for Debian (URLs below) but I got error listed below in the comment.
https://cloud.r-project.org/bin/linux/debian/#general-information
https://www.digitalocean.com/community/tutorials/how-to-install-r-on-debian-9
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Basic Troubleshooting Checklist**

[x ] I have confirmed WSL is enabled: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[x ] I have searched Google for the error message.
[x ] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x ] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[ ] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[ ] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**WLinux Version**

Find: Settings->Apps->Apps & features->WLinux->Advanced Options->Version.

Insert here:
1.1.23.0
**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17134 N/A Build 17134
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              LENOVO S02KT61A, 9/28/2018
For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by sirredbeard** [comment]
WLinux ships on Debian stable (stretch) but comes with buster (testing) enabled but pinned lower in apt priority.

The easiest way to get 3.5.1 is to install it from testing:

`$ sudo apt -t testing install r-base r-base-dev`

Let me know if this helps.

add-apt-repository and apt-key seem to give up a lot on WSL, it is almost always easier to echo the deb repo into /etc/apt/sources.list.d/reponame.list and then curl and dearmor the key into /etc/apt/trusted.d/repokey.gpg. 

This is the first time we have a request for R though and we will put it on the list to easy deploy from wlinux-setup.

**Comment by nvrgrwld** [comment]
Maybe this needs its own issue, but I was attempting to install Terminator and got the same error.

Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for WLinux/stretch
$


Could you unpack your answer a little bit please.  "it is almost always easier to echo the deb repo into /etc/apt/sources.list.d/reponame.list and then curl and dearmor the key into /etc/apt/trusted.d/repokey.gpg."

**Comment by sirredbeard** [comment]
add-apt-repository doesn't currently recognize WLinux as Debian-compatible, so it gives up.

You can edit /etc/os-release to change it to Debian but we have to modify /etc/os-release to comply with Debian deriviative standards.

apt-key also has some odd dependencies that break easily, issues related to dirmngr and gpg we have been working with WSL team on to fix for all the Debian/Ubuntu-based distros.

So the way we work around these in wlinux-setup is by writing the apt repo configuration directly and manually installing the applicable gpg key.

Take a look at how this is done in wlinux-setup for .net [here](https://github.com/WhitewaterFoundry/WLinux/blob/master/linux_files/setup#L591).

First we download and unpack the Microsoft apt repo key:
`curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg`

Then we copy the key into the apt trusted key folder:
`sudo cp microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg`

We can delete our local copy:
`rm microsoft.gpg`

Then we use echo to write the apt repo configuration to a sources.list file in the apt sources folder:
`sudo echo "deb https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch main" > /etc/apt/sources.list.d/microsoft.list `

Then we update everything and install:
`sudo apt update
sudo apt upgrade -y
sudo apt install dotnet-sdk-2.1 -y`
```

**Comment by transcriptomics** [comment]
I tried the "testing" instead of "stretch" as suggested above:
```
$ sudo apt -t testing install r-base r-base-dev
$
```

Everything installs fine with all the dependencies and I can launch latest R:
```
$ R

R version 3.5.1 (2018-07-02) -- "Feather Spray"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> q()
Save workspace image? [y/n/c]: n
$
```
However, right after when I tried `apt update` I found that now `apt` is broken-- probably a runtime version dependency. I am just guessing. Please see below:
```
$ sudo apt update
apt: relocation error: /usr/lib/x86_64-linux-gnu/libapt-private.so.0.0: symbol _ZN3URIcvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEB5cxx11Ev version APTPKG_5.0 not defined in file libapt-pkg.so.5.0 with link time reference
$
```

**Comment by sirredbeard** [comment]
Yeah, mixing distros is like crossing the streams in Ghostbusters, it can cause problems. We have debated moving everything up to testing but testing does not get the same level of security updates that stable does. So we are stuck with dealing with some of the edge cases but most users get the stablity and security of Debian stable.

The error is an issue with the libstdc++6 package, a version mismatch. 

What is the output of:
`$ apt-cache policy  libstdc++6`

You could try upgrading it:
`$ sudo apt -t testing install libstdc++6`

If it already upgraded then we may need to purge it manually install the package from the .deb file directly from stretch repos.

Sorry about this.

**Comment by transcriptomics** [comment]
Nothing related to any `apt` command works. They all throw the same error. 
I had already tried `sudo apt -t testing update` with the same error. Please see below. 
```
$ apt-cache policy libstdc++6
apt-cache: relocation error: /usr/lib/x86_64-linux-gnu/libapt-private.so.0.0: symbol _ZN3URIcvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEB5cxx11Ev version APTPKG_5.0 not defined in file libapt-pkg.so.5.0 with link time reference
$ sudo apt -t testing install libstdc++6
[sudo] password for xxxxx:
apt: relocation error: /usr/lib/x86_64-linux-gnu/libapt-private.so.0.0: symbol _ZN3URIcvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEB5cxx11Ev version APTPKG_5.0 not defined in file libapt-pkg.so.5.0 with link time reference
$
```

**Comment by sirredbeard** [comment]
Try:
```
wget http://ftp.us.debian.org/debian/pool/main/g/gcc-6/libstdc++6_6.3.0-18+deb9u1_amd64.deb
sudo dpkg -i libstdc++6_6.3.0-18+deb9u1_amd64.deb
```

**Comment by transcriptomics** [comment]
No luck. I agree totally that mixing distros is a bad idea. 

```
$ wget http://ftp.us.debian.org/debian/pool/main/g/gcc-6/libstdc++6_6.3.0-18+deb9u1_amd64.deb
--2018-11-09 09:08:01--  http://ftp.us.debian.org/debian/pool/main/g/gcc-6/libstdc++6_6.3.0-18+deb9u1_amd64.deb
Resolving ftp.us.debian.org (ftp.us.debian.org)... 64.50.236.52, 128.61.240.89, 64.50.233.100, ...
Connecting to ftp.us.debian.org (ftp.us.debian.org)|64.50.236.52|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 396196 (387K) [application/x-troff-man]
Saving to: ‘libstdc++6_6.3.0-18+deb9u1_amd64.deb’

libstdc++6_6.3.0-18+deb9u1_am 100%[=================================================>] 386.91K  1.15MB/s    in 0.3s

2018-11-09 09:08:02 (1.15 MB/s) - ‘libstdc++6_6.3.0-18+deb9u1_amd64.deb’ saved [396196/396196]

$ sudo dpkg -i libstdc++6_6.3.0-18+deb9u1_amd64.deb
(Reading database ... 33143 files and directories currently installed.)
Preparing to unpack libstdc++6_6.3.0-18+deb9u1_amd64.deb ...
Unpacking libstdc++6:amd64 (6.3.0-18+deb9u1) over (6.3.0-18+deb9u1) ...
Setting up libstdc++6:amd64 (6.3.0-18+deb9u1) ...
Processing triggers for libc-bin (2.27-8) ...
$ sudo apt update
apt: relocation error: /usr/lib/x86_64-linux-gnu/libapt-private.so.0.0: symbol _ZN3URIcvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEB5cxx11Ev version APTPKG_5.0 not defined in file libapt-pkg.so.5.0 with link time reference
$ sudo apt -t testing update
apt: relocation error: /usr/lib/x86_64-linux-gnu/libapt-private.so.0.0: symbol _ZN3URIcvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEB5cxx11Ev version APTPKG_5.0 not defined in file libapt-pkg.so.5.0 with link time reference
$ 
```

**Comment by sirredbeard** [comment]
I have put this on my list to go attempt to duplicate.

There are seem to be a number of causes for this error, release mixing could be just one.

I know it sucks that you have a had a problem but the very conservative approach we take to crossing releases has been okay, while still providing a high level of stability and security, and we are looking at more ways to reduce or eliminate that further.

I would like to solve this though because we should have an R dev environment option.

Did you install any packages from a PPA?

**Comment by transcriptomics** [comment]
I did not specifically install any package from PPA.
steps:
1. I installed Wlinux
2. ran `sudo apt update && sudo apt upgrade`
3. tried installing `r-base` and `r-base-dev`
4. saw that installed version was R-3.3.3
5. so I started looking into how I could get the latest R-3.5.1 installed after purging `r-base` and `r-base-dev` completely.
6. After getting error while adding repository as mentioned above, I opened this thread.

My goal was to test if R would perform faster on WSL/Wlinux than on the WSL/Ubuntu in our real world scenarios.

**Comment by sirredbeard** [comment]
I didn't know if you tried to install from PPA earlier, sometimes PPAs can install Ubuntu-specific packages.

Please give me a chance to work on this. I am going to loop in some help too.

We should have to way to get R up and running.

Again, I am very sorry for the inconvenience.

**Comment by sirredbeard** [comment]
This in part prompted #164.
