### ISSUE TITLE
Remmina remote desktop client

### ISSUE THREAD

**Issue by JeroenDronkers** [WhitewaterFoundry/WLinux#160]
**Is your feature request related to a problem? 
No. I would love to be able to use Remmina for remote desktop connections since it is much more stable than windows remote desktop.

**Describe the solution you'd like**
I would love to be able to use Remmina for remote desktop connections since it is much more stable than windows remote desktop.

**Describe alternatives you've considered**
Windows remote desktop isn't user friendly

**Comment by sirredbeard** [comment]
Remmina is available in Debian stretch backports.

Here are the install instructions from the Remmina website:

To install Remmina from Debian Backports, just copy and paste the following lines on a terminal window:
```
echo 'deb http://ftp.debian.org/debian stretch-backports main' | sudo tee --append /etc/apt/sources.list.d/stretch-backports.list >> /dev/null
sudo apt update`
sudo apt install -t stretch-backports remmina remmina-plugin-rdp remmina-plugin-secret
```

https://remmina.org/how-to-install-remmina/

I have not tested Remmina on WLinux personally, waiting on a bunch of dependencies to download now to test, but Remmina team has and they say it is supported.

https://remmina.org/remmina-on-windows/

**Comment by JeroenDronkers** [comment]
Hello Haydon

Thanks a lot for your reply!

After following the instructions I get however still the same error when trying to install remmina. (one of my favourite linux tools actually…)


sudo apt-get install remmina
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
remmina : Depends: libgcrypt20 (>= 1.8.0) but 1.7.6-2+deb9u3 is to be installed
           Depends: libvte-2.91-0 (>= 0.49.92) but 0.46.1-1 is to be installed
E: Unable to correct problems, you have held broken packages.

Kind regards

--
Jeroen Dronkers

Support Escal Eng
Eq-Uk Gtsc Bizapps Server
Customer Services and Support

Office: +44 (118) 9095507
jedronke@microsoft.com<mailto:jedronke@microsoft.com>

[Microsoft Logo]
Team Manager | Frances Early (francese@microsoft.com<mailto:francese@microsoft.com>) +44 (20) 34251539

**Comment by sirredbeard** [comment]
It seems like you may need to install a more recent version of libgcrypt20 and libvte than is available in Debian stable.

You can install them from testing using `$ sudo apt -t testing install libgcrypt20 libvte`

**Comment by sirredbeard** [comment]
I didn't run into that dependency issue. Weird.

![capture](https://user-images.githubusercontent.com/33820650/48280001-4a36ec80-e420-11e8-9ca9-7f34b846afea.PNG)

**Comment by sirredbeard** [comment]
This in part prompted #164.

**Comment by AceHack** [comment]
RDP Manager is a good windows alternative.

https://www.microsoft.com/en-us/download/details.aspx?id=44989

**Comment by JeroenDronkers** [comment]
Hello Aaron,

Yes, I will use that from now on.


Thanks


Kind regards

--
Jeroen Dronkers

Support Escal Eng
Eq-Uk Gtsc Bizapps Server
Customer Services and Support

Office: +44 (118) 9095507
jedronke@microsoft.com<mailto:jedronke@microsoft.com>

[Microsoft Logo]
Team Manager | Frances Early (francese@microsoft.com<mailto:francese@microsoft.com>) +44 (20) 34251539
