### ISSUE TITLE
The zsh prompt is a character like "question mark"

### ISSUE THREAD

**Issue by simomo** [WhitewaterFoundry/WLinux#162]
**Describe the bug**
The terminal prompt is like a question mark:
![image](https://user-images.githubusercontent.com/1251601/48278011-49857100-e487-11e8-9e2f-f7415c6c56f2.png). 
If I copy&paste it here, it's "➜  ~"

And bash works well.

**To Reproduce**
Just finish the install and start the wlinux terminal...

**Expected behavior**
A readable prompt

**Screenshots**

**Additional context**
I'm at China.
I'm using zsh.

**Basic Troubleshooting Checklist**

[ ] I have confirmed WSL is enabled: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[ ] I have searched Google for the error message.
[ ] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[ ] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[ ] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[ ] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**WLinux Version**

Find: Settings->Apps->Apps & features->WLinux->Advanced Options->Version.

Insert here:1.1.23.0

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17134 N/A Build 17134
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              LENOVO N27ET29W (1.15 ), 8/8/2018

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by aohmusi** [comment]
I think the problem is from terminal emulator (Windows command prompt). If WLinux support other terminal emulator such as mintty/wsltty you can use special fonts.

**Comment by kbrock84** [comment]
This looks like it may be a duplicate of #132. I think @aohmusi is correct about the terminal emulator. Looks fine in Hyper and ConEmu especially with InconsolataGo as the font.

**Comment by simomo** [comment]
I resolved the issue by changing the front to "Dejavu Sans Mono" :)

Steps:

1. Right click on the title bar
1. Select `Properties`
1. Go to the tab `Font`
1. Select "Dejavu Sans Mono" in the `Font` section
1. Click the `OK`

**Comment by aborruso** [comment]
This @simomo solution should be put in a sort of FAQ or in an alert during installation.

Because everytime I install Pengwin with ZSH I have this kind of chars.

Thank you

**Comment by jturi** [comment]
> I resolved the issue by changing the front to "Dejavu Sans Mono" :)
> 
> Steps:
> 
> 1. Right click on the title bar
> 2. Select `Properties`
> 3. Go to the tab `Font`
> 4. Select "Dejavu Sans Mono" in the `Font` section
> 5. Click the `OK`

There is no "Dejavu Sans Mono" font option on some WSL versions, but NsimSun font worked. Thx!

**Comment by crramirez** [comment]
Cascadia Code PL should work pretty well also: https://github.com/microsoft/cascadia-code/releases

**Comment by wildman777** [comment]
I just want to add that the font SimSun-ExtB on windows 10 also work. It allow the character to appear again

![image](https://user-images.githubusercontent.com/22399745/198167116-00f5218b-ef54-4008-bf72-d211a6773346.png)
![image](https://user-images.githubusercontent.com/22399745/198167145-aa3d1aaa-2a0d-464a-9906-7559fcbaa201.png)
![image](https://user-images.githubusercontent.com/22399745/198167173-8cbf20c6-dd92-4c91-b66c-c36558f68137.png)

**Comment by wildman777** [comment]
I also want to add that the font SimSun-ExtB in Windows 10 also work to rfix the weird character on wsl with ubuntu 20.04.5 LTS terminal.
![image](https://user-images.githubusercontent.com/22399745/198167513-9b2b5424-48f1-484f-b492-f64e81dd9c28.png)
![image](https://user-images.githubusercontent.com/22399745/198167670-e3638431-f58a-4b40-ad28-e385a9accd23.png)
![image](https://user-images.githubusercontent.com/22399745/198167819-eaff6f3a-4e22-4ea3-9299-3b40e5c7ce99.png)

**Comment by wildman777** [comment]
If you guy are like me and don't find the font mentionned in this post or none of the font in properties worked, then there is a great chance that just like me, you don't have the font for the powerline in Windows for your terminal in  WSL 2. You need to download the font needed for the powerline  and install it throught powershell.

1. _Clone the powerline repository on Windows_

```zsh
git clone https://github.com/powerline/fonts.git
```

2. _Open an admin PowerShell, navigate to the root of the repo and run this:_

```zsh
.\install.ps1
```

_This will install all the fonts on your Windows. You might get an error from PowerShell blocking you from running the script. Check [this out](https://stackoverflow.com/questions/4037939/powershell-says-execution-of-scripts-is-disabled-on-this-system) if it happens with you. Make sure to reverse the policy after._

After that, you just need to select "Dejavu Sans Mono" in the `Font` section in the tab `Font` in the terminal `propertie`s as say in this post by @jturi.

I have found this solution through this link: https://blog.joaograssi.com/windows-subsystem-for-linux-with-oh-my-zsh-conemu/ 
It also include the complete ways to install zsh for WSL.
