### ISSUE TITLE
docker bg process died?

### ISSUE THREAD

**Issue by cicorias** [WhitewaterFoundry/WLinux#165]
**Describe the bug**
after a fresh install the docker support via bridge stopped working. 
**To Reproduce**
essentially it died just after I installed and used TMUX via apt install.  
1. install tmux
2. open tmux and open up a four windows (ctrl-b + shift ", ctrl-b + shift %)
3. exit one, then another
**Expected behavior**

**Screenshots**
after attempting to run docker I see the following:
```
cicorias@cicoria-razer:~$ docker ps
2018/11/11 16:58:05 socat[110] E execvp("npiperelay.exe", "npiperelay.exe", "-ep", "-s", ...): No such file or directory
2018/11/11 16:58:05 socat[111] E execvp("npiperelay.exe", "npiperelay.exe", "-ep", "-s", ...): No such file or directory
error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.38/containers/json: EOF
```
![image](https://user-images.githubusercontent.com/1080406/48318930-2ff23f80-e5d5-11e8-8e1b-182dde2020e6.png)

**Additional context**

**Basic Troubleshooting Checklist**

[x] I have confirmed WSL is enabled: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[x] I have searched Google for the error message.
[x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[x] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[x] I have disabled and re-enabled WSL in Windows Features.
[x] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:
I've tried to run npiperelay directly or the sh script `docker-relay` after seeing the bg process exit.

I've reran wlinux-setup for just the docker step too.
**WLinux Version**

Find: Settings->Apps->Apps & features->WLinux->Advanced Options->Version.
![image](https://user-images.githubusercontent.com/1080406/48318964-9d05d500-e5d5-11e8-8b59-e65f691ca6a4.png)

Insert here:

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:
```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17134 N/A Build 17134
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              American Megatrends Inc. 5.11, 2/23/2018
```
For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by sirredbeard** [comment]
I have asked Carlos come take a look at this. Spoke to him about it this morning.

**Comment by cicorias** [comment]
It’s probably tmux and npiperelay interaction. I tried nohup on the /profile script that starts the bg job but didn’t help.  An alternative to tmux called byobu is working fine.

**Comment by crramirez** [comment]
Hello,

I am looking the best way to solve it. Meanwhile as a workaround run:

` sudo docker-relay &`

Regards

**Comment by sirredbeard** [comment]
@cicorias 

Please update wlinux-setup and give changes in #171 a try. Thank you.

**Comment by sirredbeard** [comment]
@cicorias 

We are working on those changes in #171. 

I saw your feedback over there.

Thank you for your patience.

**Comment by cicorias** [comment]
yea, i removed those comments as they were premature. :) it. I'll update the script and see the results. tx.

**Comment by sirredbeard** [comment]
@cicorias 

I got nervous and had to pull some back but we will address those issues and the concerns you raised.

Carlos is helping me on with this project and his day is otherwise busy. I am sure he will get to us when he can.

**Comment by cicorias** [comment]
sure - easy workaround to tmux is boybu
