### ISSUE TITLE
I can not use vs code on wlinux + x410

### ISSUE THREAD

**Issue by liujiaxing325** [WhitewaterFoundry/WLinux#166]
in x410 i click the vs code launch and nothing hapen; but the code command is useful 
![image](https://user-images.githubusercontent.com/10149187/48328509-42c14e80-e67f-11e8-8631-0071cacf09d7.png)

**Comment by kbrock84** [comment]
@liujiaxing325 I had a similar issue. I did the following which resolved it:

update apt-get
```bash
sudo apt-get update
```
Run the install again using
```bash
wlinux-setup
```
be sure the DISPLAY variable is set for X410
```bash
export DISPLAY=127.0.0.1:0.0
```

This worked for me. Hope it helps.

**Comment by sirredbeard** [comment]
Thanks for that input @kbrock84.

Sorry you ran into that issue.

Running the Code install again might be useful.

The DISPLAY variable should already set system-wide.

**Comment by patrick330602** [comment]
Are you on insider build? I personally have similar issue in insider build

**Comment by sirredbeard** [comment]
@patrick330602 

Interesting. Which build?

If we can reproduce and do a write-up we should submit to WSL.

**Comment by patrick330602** [comment]
@sirredbeard on 18277. I have to execute multiple times of `code` to start it on this build, and I initially thought this is due to the issue in `code` itself until I realized sublime text have similar issue on this build(I have to execute `subl` 2-3 times until it launches).

**Comment by kbrock84** [comment]
I'm not running the insider build. I'm on 17134. Looks like I do have an update though.

**Comment by kbrock84** [comment]
Another note. I had to go back and <code>source /etc/profile</code> again before running <code>wlinux setup</code> so maybe that was the issue for me. Looks like the DISPLAY variable is set there.

**Comment by AceHack** [comment]
I get that keyboard already exist and XMODIFIERS issue a lot, I figured out how to fix it every time.

1) make sure X410 and WLinux are both closed.
2) open WLinux, (You will get errors because X410 is not open)
3) open X410
4) close WLinux
5) open WLinux and you will get no warnings and see "Fcitx is running correctly."

Now code and other UIs will open on first try.

**Comment by sandeberger** [comment]
> in x410 i click the vs code launch and nothing hapen; but the code command is useful
> ![image](https://user-images.githubusercontent.com/10149187/48328509-42c14e80-e67f-11e8-8631-0071cacf09d7.png)

I have exactly the same issue on my machine!

**Comment by sirredbeard** [comment]
Can you run `$ code --verbose` and post? Thank you.

**Comment by gustavoreynaldo** [comment]
@sirredbeard 
i am having the same problem, my $ code --verbose is:
(code:2291): Gtk-WARNING **: 16:40:18.841: cannot open display: 127.0.0.1:0.0

**Comment by gustavoreynaldo** [comment]
nevermind! I didn't have any GUI server installed, worked as a charm with vsXsrv (used this one because x410 isn't free)

**Comment by liujiaxing325** [comment]
code --verbose  ERROR:bus.cc(395)] Failed to connect to the bus: Failed to connect to socket /host/run/dbus/system_bus_socket: No such file or directory
