### ISSUE TITLE
Add kernel options for "iotop" compatibilty.

### ISSUE THREAD

**Issue by carloshmm** [WhitewaterFoundry/WLinux#167]
**Is your feature request related to a problem? Please describe.**
The utility called [iotop](https://www.systutorials.com/docs/linux/man/8-iotop/) requires some kernel build parameters to be enabled in order to work:
CONFIG_TASK_DELAY_ACCT, CONFIG_TASK_IO_ACCOUNTING, CONFIG_TASKSTATS and CONFIG_VM_EVENT_COUNTERS
These are currently not present on the default kernel available on wlinux.

**Describe the solution you'd like**
Build the kernel with these options enabled.

**Describe alternatives you've considered**
Make it available additional custom kernels on the repository with these build parameters available so that people can install them instead of the default kernel.

**Additional context**
I don't know if WSL is capable of compatibility with these parameters so if I'm requesting something impossible just tell me and I will close this feature request.

**Comment by sirredbeard** [comment]
There is no Linux kernel in WLinux or other WSL distros.

WSL is a translation layer which translates the Linux kernel syscalls to Windows kernel syscalls.

Modifications to the underlying WSL, including support for certain parameters, must be implemented by Microsoft.

There is an outstanding request for this [here](https://github.com/Microsoft/WSL/issues/1989).

Implementing those is beyond our scope.
