### ISSUE TITLE
wlinux-setup does not call sudo apt-get update

### ISSUE THREAD

**Issue by RoboMarth** [WhitewaterFoundry/WLinux#168]
## Describe the Bug
When using wlinux-setup to install packages, the list of available packages is not updated beforehand, resulting in 404 Not Found errors:

```
After this operation, 304 MB of additional disk space will be used.
Err:1 https://cdn-aws.deb.debian.org/debian testing/main amd64 libtext-iconv-perl amd64 1.7-5+b6
  404  Not Found
Err:2 https://cdn-aws.deb.debian.org/debian testing/main amd64 libtext-charwidth-perl amd64 0.04-7.1
  404  Not Found
Err:3 https://cdn-aws.deb.debian.org/debian testing/main amd64 libgdbm6 amd64 1.18-2
  404  Not Found
.
.
.
E: Failed to fetch https://cdn-aws.deb.debian.org/debian/pool/main/m/msgpack-c/libmsgpackc2_3.0.1-1_amd64.deb  404  Not Found
E: Failed to fetch https://cdn-aws.deb.debian.org/debian/pool/main/libu/libuv1/libuv1_1.23.1-1_amd64.deb  404  Not Found
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

## To Reproduce
1. Use the wlinux-setup script to install Neovim on a fresh install of WLinux.

## Expected Behavior
Expected Neovim to be successfully installed.

## Workaround
Run sudo apt-get update before using wlinux-setup. Then wlinux-setup works as expected.

### WLinux Version
1.1.23.0

### Windows Build
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17134 N/A Build 17134
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              LENOVO N1QET77W (1.52 ), 7/4/2018

**Comment by sirredbeard** [comment]
Thank you. Fixed in #170. Also found a few other places to handle that better.
