### ISSUE TITLE
mtr  issue

### ISSUE THREAD

**Issue by Chanvin974** [WhitewaterFoundry/WLinux#169]
**Describe the bug**
wlinux launch with administors rights to get raw socket with mtr,
but the commands mtr  shows nothing...

**To Reproduce**
1.   apt-get install mtr-tiny
2.   mtr  www.lemonde.fr

**Expected behavior**
mtr shows traceroute to destination with latency

**Screenshots**
                                                 My traceroute  [v0.87]
GVRJC (0.0.0.0)                                                                                Mon Nov 12 21:37:37 2018
Keys:  Help   Display mode   Restart statistics   Order of fields   quit
                                                                               Packets               Pings
 Host                                                                        Loss%   Snt   Last   Avg  Best  Wrst StDev

**Additional context**
does not work even with -a <ip-address>.  parameter

**Comment by sirredbeard** [comment]
This is a [limitation of WSL](https://github.com/Microsoft/WSL/issues/717). I am sorry this isn't going to work for you on any WSL distro. If that is a deal breaker and you would like a refund of WLinux, please forward your purchase confirmation e-mail from Microsoft to contact@whitewaterfoundry.com with your preferred PayPal e-mail and I will get that promptly refunded.

**Comment by Chanvin974** [comment]
Hello

ok. i ve just forward my confirmation mail for a refund. my Microsoft store email is vincent.chantrel@rez.re

Regards

Vincent



Le 12 nov. 2018 à 22:20, à 22:20, Hayden <notifications@github.com> a écrit:
