### ISSUE TITLE
dpkg vendor setting

### ISSUE THREAD

**Issue by marsman2020** [WhitewaterFoundry/WLinux#17]
**Describe the bug**
dpkg vendor setting needs to be changed from 'debian' per https://wiki.debian.org/Derivatives/Guidelines

**To Reproduce**
1. Install from Microsoft Store
2. cat /etc/dpkg/origins/default

```
Vendor: Debian
Vendor-URL: http://www.debian.org/
Bugs: debbugs://bugs.debian.org
```

**Expected behavior**
Expected behavior is that the Vendor strings are properly set.  Per the Debian derivative guidelines:
> dpkg has the concept of a 'vendor', derivative distributions should set the dpkg vendor to something other than Debian. To change the vendor you can install a file to /etc/dpkg/origins/example and ensure the /etc/dpkg/origins/default symlinks points to example. Please ensure that the Parent field of your dpkg origins file is set to Debian. For more information about the dpkg vendor concept and implementation please read the 5/deb-origin and 1/dpkg-vendor manual pages. 

Ref: https://wiki.debian.org/Derivatives/Guidelines

**Comment by sirredbeard** [comment]
Fixed by #18.

Thank you so much for pointing that out.
