### ISSUE TITLE
Can't login to Azure with VSCode

### ISSUE THREAD

**Issue by AceHack** [WhitewaterFoundry/WLinux#174]
**Describe the bug**
Install any VSCode extension that requires login to Azure.  i.e. "Azure Tools" extension.  Although it happens with any VSCode extension that tried to login into Azure.

**To Reproduce**
1. Install VSCode
2. Install Azure Tools Extension
3. Try to login to Azure using new Tab
4. Looks like everything works but nothing happens

**Expected behavior**
To see my Azure resources in VSCode

**WLinux Version**
1.1.23.0

**Windows Build**
OS Name:                   Microsoft Windows 10 Pro Insider Preview
OS Version:                10.0.18277 N/A Build 18277
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              American Megatrends Inc. 1002, 7/2/2018

**Comment by sirredbeard** [comment]
I am closing this issue here, for now, and have [opened an issue with Azure](https://github.com/Microsoft/vscode-azure-account/issues/109).

If it is later determined to be an issue with WLinux I will of course re-open and address.

Thank you for this report.

**Comment by devcircus** [comment]
A note for anyone that comes across this. This is a problem in every distro really. You do need to install gnome-keyring and then run these lines when opening an app that requires keyring access, I just put them in my .zshrc at the bottom:
```bash
eval $(dbus-launch --sh-syntax);
eval $(echo -n "" | /usr/bin/gnome-keyring-daemon --login);
eval $(/usr/bin/gnome-keyring-daemon --components=secrets --start);
```
it will notify you if you are missing any other required packages. 

Shutdown your distro and start it back up, open vscode and you should be able to login to Azure, Github, etc.

**Comment by crramirez** [comment]
Excellent thank you for sharing

**Comment by devcircus** [comment]
A couple of things to keep in mind:

(1) vscode may need to spawn a browser as part of the login workflow so you need to be sure to have one installed and working.

(2) if vscode doesn't handle the redirect from the browser with the login code, you'll need to copy the code, return to vscode, click "signing in to github/Microsoft" at the bottom, then paste the code(ensuring there are no spaces on either end of the pasted code) and finally, hit enter.
