### ISSUE TITLE
Typo in setup intro prompt

### ISSUE THREAD

**Issue by kbrock84** [WhitewaterFoundry/WLinux#179]
There is an issue with the text wrapping and spaces coming from the setup script.

![image](https://user-images.githubusercontent.com/31415142/48393598-1b8d7000-e6c5-11e8-9c57-04704d051ee6.png)

As you can see "allowsyou" is written as one word.

Looks like this is easy to miss in the [setup script](https://github.com/WhitewaterFoundry/WLinux/blob/master/linux_files/setup) lines 15 and 16
```bash
WLinux comes with a core set of packages installed. wlinux-setup allows \
you to install curated selections for WLinux and configure optional settings. \
```

Maybe just change to something like this for clarity or add a <code>\n</code> somewhere.
```bash
WLinux comes with a core set of packages installed. wlinux-setup allows you to install curated selections for WLinux and configure optional settings. \
```

**Comment by sirredbeard** [comment]
This was patched between 1.1.23 and the upcoming 1.1.25. If you update wlinux-setup you will get the updated version. 

![capture](https://user-images.githubusercontent.com/33820650/48413147-d7c25700-e714-11e8-8c7a-110e2dee56e4.PNG)
