### ISSUE TITLE
Please allow url handling by default windows browser

### ISSUE THREAD

**Issue by AceHack** [WhitewaterFoundry/WLinux#180]
Would it be possible when I click links or an application tries to open a link, it uses the default windows browser?  Thanks.

**Comment by patrick330602** [comment]
`wslview` should already handle the website url right now(http/https should open your default browser). If there is a issue with is utility, you should open a issue at <https://github.com/wslutilities/wslu>. meanwhile I will start investigating the issue.

**Comment by AceHack** [comment]
Where I experienced the issue was in code.  When you go to sign into Azure it has a button that says Copy and Open.  This button works on windows and opens the default browser, in WSL it does not.

![azuresignin](https://user-images.githubusercontent.com/578953/48424988-deab9280-e731-11e8-9d5f-eb815c9fced1.jpg)


https://github.com/WhitewaterFoundry/WLinux/issues/174

**Comment by sirredbeard** [comment]
As @patrick330602 pointed out, we have already implemented this.

Code calls xdg-open (part of xdg-utils) which calls /usr/bin/x-www-browser which has been patched by wslview (part of wslu) to do exactly what you are requesting.

This works well in other apps and other parts of Code just fine.

This appears to be a bug in how the Azure extension for Code calls xdg-utils.

Please file a bug report in the [appropriate venue](https://github.com/Microsoft/vscode-azure-account/issues).
