### ISSUE TITLE
Can't install MySQL server

### ISSUE THREAD

**Issue by mabdelfattah** [WhitewaterFoundry/WLinux#186]
**Describe the bug**
I'm trying to install MySql using the following commands
```
wget http://repo.mysql.com/mysql-apt-config_0.8.9-1_all.deb
sudo dpkg -i mysql-apt-config_0.8.9-1_all.deb
```
The UI appears, I select MySQL version, the following output come , then nothing
```
dpkg: warning: downgrading mysql-apt-config from 0.8.10-1 to 0.8.9-1
(Reading database ... 53240 files and directories currently installed.)
Preparing to unpack mysql-apt-config_0.8.9-1_all.deb ...
Unpacking mysql-apt-config (0.8.9-1) over (0.8.10-1) ...
Setting up mysql-apt-config (0.8.9-1) ...
Warning: apt-key should not be used in scripts (called from postinst maintainerscript of the package mysql-apt-config)
key 8C718D3B5072E1F5:
75 signatures not checked due to missing keys
OK
```

**Expected behavior**
Get MySQL server installed

**Additional context**
When I try `sudo apt-get install mysql-server`, I get the following error:
```
dpkg: warning: downgrading mysql-apt-config from 0.8.10-1 to 0.8.9-1
(Reading database ... 53240 files and directories currently installed.)
Preparing to unpack mysql-apt-config_0.8.9-1_all.deb ...
Unpacking mysql-apt-config (0.8.9-1) over (0.8.10-1) ...
Setting up mysql-apt-config (0.8.9-1) ...
Warning: apt-key should not be used in scripts (called from postinst maintainerscript of the package mysql-apt-config)
key 8C718D3B5072E1F5:
75 signatures not checked due to missing keys
OK
```

**Basic Troubleshooting Checklist**

[X] I have confirmed WSL is enabled: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[X] I have searched Google for the error message.
[X] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[X] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[ ] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[X] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**WLinux Version**
1.1.23.0

**Windows Build**
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              Dell Inc. 1.12.1, 02-Oct-18

**Comment by ThatWeirdAndrew** [comment]
Have you tried installing the latest version from here: https://dev.mysql.com/get/mysql-apt-config_0.8.10-1_all.deb

**Comment by sirredbeard** [comment]
@mabdelfattah 

It appears mysql-apt-config 0.8.9 is not properly configuring apt keys when you select to install 5.6. 5.7 works though.

I tried mysql-apt-config 0.8.10 per @ThatWeirdAndrew's suggestion and was able to install both 5.6 and 5.7.

Can you give that a try?

**Comment by mabdelfattah** [comment]
@ThatWeirdAndrew, @sirredbeard  I just did and nothing changed, exactly the same behavior.

I even deleted all MySQL files in the system (using following commands) and tried to restart the whole process, but nothing works!
```
sudo rm /etc/apt/sources.list.d/mysql.list
sudo rm -rf /var/lib/apt/lists/repo.mysql.com*
sudo rm -rf /var/lib/apt/lists/repo.mysql.com*
```

**Comment by mabdelfattah** [comment]
@sirredbeard Just FYI, I did a complete re-install, and I have the same problem.

**Comment by mabdelfattah** [comment]
I did a fresh install, without any testing releases, but mysql-server package is still depending on MariaDB!
```
$ sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
[sudo] password for mahmoud:
(Reading database ... 14186 files and directories currently installed.)
Preparing to unpack mysql-apt-config_0.8.10-1_all.deb ...
Unpacking mysql-apt-config (0.8.10-1) over (0.8.10-1) ...
Setting up mysql-apt-config (0.8.10-1) ...
Warning: apt-key should not be used in scripts (called from postinst maintainerscript of the package mysql-apt-config)
OK


$ sudo apt-get update
Hit:1 http://repo.mysql.com/apt/debian stretch InRelease
Get:2 http://security.debian.org/debian-security stable/updates InRelease [94.3 kB]
Hit:6 https://apt.patrickwu.ml stable InRelease
Ign:3 https://cdn-aws.deb.debian.org/debian stable InRelease
Get:4 https://cdn-aws.deb.debian.org/debian stable-updates InRelease [91.0 kB]
Get:5 https://cdn-aws.deb.debian.org/debian stretch-backports InRelease [91.8 kB]
Hit:7 https://cdn-aws.deb.debian.org/debian stable Release
Fetched 277 kB in 13s (20.6 kB/s)
Reading package lists... Done


$ sudo apt-get install mysql-server
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  default-mysql-server galera-3 libaio1 libcgi-fast-perl libcgi-pm-perl libconfig-inifiles-perl libdbd-mysql-perl libdbi-perl libencode-locale-perl libfcgi-perl libhtml-parser-perl
  libhtml-tagset-perl libhtml-template-perl libhttp-date-perl libhttp-message-perl libio-html-perl libjemalloc1 liblwp-mediatypes-perl libmariadbclient18 libreadline5 libterm-readkey-perl
  libtimedate-perl liburi-perl lsof mariadb-client-10.1 mariadb-client-core-10.1 mariadb-common mariadb-server-10.1 mariadb-server-core-10.1 mysql-common socat
Suggested packages:
  libclone-perl libmldbm-perl libnet-daemon-perl libsql-statement-perl libdata-dump-perl libipc-sharedcache-perl libwww-perl mailx mariadb-test netcat-openbsd tinyca
The following NEW packages will be installed:
  default-mysql-server galera-3 libaio1 libcgi-fast-perl libcgi-pm-perl libconfig-inifiles-perl libdbd-mysql-perl libdbi-perl libencode-locale-perl libfcgi-perl libhtml-parser-perl
  libhtml-tagset-perl libhtml-template-perl libhttp-date-perl libhttp-message-perl libio-html-perl libjemalloc1 liblwp-mediatypes-perl libmariadbclient18 libreadline5 libterm-readkey-perl
  libtimedate-perl liburi-perl lsof mariadb-client-10.1 mariadb-client-core-10.1 mariadb-common mariadb-server-10.1 mariadb-server-core-10.1 mysql-common mysql-server socat
0 upgraded, 32 newly installed, 0 to remove and 19 not upgraded.
Need to get 22.5 MB/26.0 MB of archives.
After this operation, 191 MB of additional disk space will be used.
Do you want to continue? [Y/n]


$ sudo apt-get install mysql-community-server
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mysql-community-server : Depends: mysql-common (>= 8.0.13-1debian9)
                          Depends: mysql-client (= 8.0.13-1debian9) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by sirredbeard** [comment]
Does it look like it is installing some MySQL components from Debian and some from the MySQL database?

In which case we might need use apt pinning to prioritize certain packages.

**Comment by mabdelfattah** [comment]
Yes, that is what I did, I created `/etc/apt/preferences.d/00mysql.pref` with the following content
```
Package: *
Pin: origin "repo.mysql.com"
Pin-Priority: 1001
```

**Comment by abdkayali** [comment]
> Yes, that is what I did, I created `/etc/apt/preferences.d/00mysql.pref` with the following content
> 
> ```
> Package: *
> Pin: origin "repo.mysql.com"
> Pin-Priority: 1001
> ```

Does this solve the problem?

**Comment by crramirez** [comment]
Hello,

This issue is quite old. Are you experiencing the same problems with installing MySQL?

Regards

**Comment by AugustasV** [comment]
> Hello,
> 
> This issue is quite old. Are you experiencing the same problems with installing MySQL?
> 
> Regards

Experiencing same problem

**Comment by abdkayali** [comment]
> Hello,
> 
> This issue is quite old. Are you experiencing the same problems with installing MySQL?
> 
> Regards

Yes, I do.

After installing MySql using `sudo apt install mysql-server`, I get the warning:
`Warning: apt-key should not be used in scripts (called from postinst maintainerscript of the package mysql-apt-config)`

In addition to that, no service is installed, so I cannot do `sudo service mysql start` otherwise I will get `Unrecognized Service`.

I'm trying to install MySql 8.0 on Debian 10 (Buster) Distro that is installed on WSL.

I will prepare and paste the whole terminal log and mysql error.log content soon.

Thanks,

**Comment by crramirez** [comment]
One question. MariaDB is not an option for you?

**Comment by abdkayali** [comment]
> One question. MariaDB is not an option for you?

Well, I guess it could be an option, I need to get back to our company team to decide it. Bug it's still confusing for me why the issue with MySql 8.0 installation happens, and what is going wrong with it.

Anyways, Thanks for mentioning MariaDB as an option.

**Comment by crramirez** [comment]
pengwin-setup has an option called LAMP it installs MariaDB alongside apache and php that you can uninstall later.

**Comment by crramirez** [comment]
Hello,

Follow this and tell me if it works:

```language=bash
sudo apt remove mysql-apt-config
wget http://repo.mysql.com/mysql-apt-config_0.8.15-1_all.deb
sudo apt install ./mysql-apt-config_0.8.15-1_all.deb 

sudo sed -i  "s/jessie/buster/g" /etc/apt/sources.list.d/mysql.list
sudo apt update
sudo apt install mysql-server 
sudo service mysql start

```

**Comment by lattara** [comment]
> Hello,
> 
> Follow this and tell me if it works:
> 
> ```
> sudo apt remove mysql-apt-config
> wget http://repo.mysql.com/mysql-apt-config_0.8.15-1_all.deb
> sudo apt install ./mysql-apt-config_0.8.15-1_all.deb 
> 
> sudo sed -i  "s/jessie/buster/g" /etc/apt/sources.list.d/mysql.list
> sudo apt update
> sudo apt install mysql-server 
> sudo service mysql start
> ```

It works for me.

**Comment by ottoniel1** [comment]
> Hola
> 
> Sigue esto y dime si funciona:
> 
> ```
> sudo apt remove mysql-apt-config
> wget http://repo.mysql.com/mysql-apt-config_0.8.15-1_all.deb
> sudo apt install ./mysql-apt-config_0.8.15-1_all.deb 
> 
> sudo sed -i  "s/jessie/buster/g" /etc/apt/sources.list.d/mysql.list
> sudo apt update
> sudo apt install mysql-server 
> sudo service mysql start
> ```

Funciono para mi, Gracias
