### ISSUE TITLE
WSL's "Rename syscall broken for non-empty directories #163" remains in WLinux

### ISSUE THREAD

**Issue by mokjpn** [WhitewaterFoundry/WLinux#193]
I found "settings sync" vs code extension (  https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync ) cannot be installed on wLinux.
VSCode produced message that:

```
EACCES: permission denied, rename '/home/mokada/.vscode/extensions/.shan.code-settings-sync-3.2.0' -> '/home/mokada/.vscode/extensions/shan.code-settings-sync-3.2.0'
```

I googled the cause of this error, and found a issue in WSL issue:
Rename syscall broken for non-empty directories #163 

and found this is already resolved in 2016:
https://github.com/Microsoft/WSL/issues/163#issuecomment-209143015

But in wLinux,  I could confirm the issue:
```
mokada@Think:~$ mkdir -p test-case/a/b
mokada@Think:~$ touch test-case/a/b/awesomesauce.txt
mokada@Think:~$ mv test-case/a/b test-case/
mv: cannot move 'test-case/a/b' to 'test-case/b': Permission denied
mokada@Think:~$
```

In "Ubuntu" app that can be installed via Windows Store, there is no error:
```
mokada@Think:~$ mkdir -p test-case/a/b
mokada@Think:~$ touch test-case/a/b/awesomesauce.txt
mokada@Think:~$ mv test-case/a/b/awesomesauce.txt test-case/
mokada@Think:~$
```

Is there any version difference between wLinux and Ubuntu?

**Comment by patrick330602** [comment]
Thank you for the feedback! however, in local testing, I do not have such issue. Can you post your WLinux version and Windows version?

Also, please use template to submit bug report next time, it will make it easier for us to debug

**Comment by mokjpn** [comment]
Sorry missing template. 
WLinux version: 1.1.23.0
Windows 10 Pro Version 1809 build 17763.134

**Comment by patrick330602** [comment]
What is the shell you are using? I tested bash and zsh with and without `rename` but they worked exactly the same.

**Comment by mokjpn** [comment]
My shell is bash.
I tried to install wLinux on another machine. Then this problem does not occur on another machine.
So the cause might be my machine environment, Sorry for bothering, I will close this issue.
