### ISSUE TITLE
apt repos broken right away?

### ISSUE THREAD

**Issue by undeadindustries** [WhitewaterFoundry/WLinux#194]
Immediately after installing and setting up, if I run apt update, I get an error with 2 repos:

E: Failed to fetch https://deb.debian.org/debian/dists/stretch-backports/main/binary-amd64/PackagesIndex  Couldn't parse pdiff index
E: Failed to fetch https://deb.debian.org/debian/dists/testing/main/binary-amd64/PackagesIndex  Couldn't parse pdiff index

**Comment by sirredbeard** [comment]
If you use the bug report template there is a troubleshooting checklist:

[ ] I have searched Google for the error message.
[ ] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting.
[ ] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[ ] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[ ] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[ ] I have run Windows 10 updates and restarted.

Please complete the checklist. It will solve 90% of issues.

The error above is very commonly associated with use of a third-party antivirus, as discussed at step two of the troubleshooting documentation here: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting

**Comment by undeadindustries** [comment]
I did all of the above in the check list before submitting the issue.

However, how would anything but searching the wlinux issue page have anything to do with this specific bug?

**Comment by sirredbeard** [comment]
There are upstream bugs in WSL from time to time and a well-established set of common problems and answers in WSL issues that are relevant to all WSL distros. Almost all of the networking issues reported here have already been reported with solutions in WSL issues. There is also a wealth of Microsoft WSL documentation and other resources that been established for two+ years. It is going to take time to duplicate that level of documentation of knowledge here. In the mean time we want to help you solve your issue quickly.

Can you access the above URLs in your browser or their parent directory?

When you open the URL in your browser which mirror is deb.debian.org resolving to for you?

Can you please post results of:

 `$ cat /etc/resolv.conf`

`$ ipconfig.exe /all`

and try:

`$ ipconfig.exe /flushdns`

Finally, are you behind a VPN, proxy, firewall, or using third-party antivirus?

**Comment by sirredbeard** [comment]
Closed for lack of response. If you are still encountering issues, please reply and we can re-open.
