### ISSUE TITLE
Open With WLinux in Context Menu leads to error

### ISSUE THREAD

**Issue by bushidocodes** [WhitewaterFoundry/WLinux#195]
**Describe the bug**

When I right click on a folder in Explorer and select "Open With WLinux," I am presented with an "Application Not Found" error.

**To Reproduce**
1. Go to Explorer
2. Right click and select Open With WLinux
3. See error

**Expected behavior**

I expect the folder to open as the current directory in WLinux

**Screenshots**

![image](https://user-images.githubusercontent.com/8700322/48648507-9d2f1780-e9bd-11e8-89ff-01bb362858a1.png)

**Additional context**

**Basic Troubleshooting Checklist**

[X] I have confirmed WSL is enabled: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[X] I have searched Google for the error message.
[X] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[X] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[ ] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[ ] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**WLinux Version**

Find: Settings->Apps->Apps & features->WLinux->Advanced Options->Version.

Insert here:

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:

OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.16299 N/A Build 16299
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              HUAWEI 1.12, 7/16/2018

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by patrick330602** [comment]
Can you complete the following steps and paste the output here?
- open Powershell with Administrator;
- run `(Get-ItemProperty Registry::HKEY_CLASSES_ROOT\Directory\Background\shell\WLinux\command).'(default)'`

**Comment by hidenmind** [comment]
I have the same issue, here is the output:
wlinux.exe run "cd \"$(wslupath \"%V\")\" && $(getent passwd $LOGNAME | cut -d: -f7)"

**Comment by patrick330602** [comment]
@hidenmind if this happens, open `regedit` from search or `ctrl-R` and navigate to `HKEY_CLASSES_ROOT\Directory\Background\shell\WLinux\command`, and replace the `default` value to `wlinux.exe run "cd \"$(wslupath \"%V\")\" && $(getent passwd $LOGNAME | cut -d: -f7)"`

**Comment by hidenmind** [comment]
@patrick330602 Thanks for replying. This is exactly the value that is already in the key, and the feature continues not working
![registry](https://user-images.githubusercontent.com/24514115/48723099-df9a6380-ec0c-11e8-8efc-7a170fef6893.png)

**Comment by sirredbeard** [comment]
We have a fix inbound #247.

**Comment by sirredbeard** [comment]
Thank you, @patrick330602.
