### ISSUE TITLE
Cassandra script expects home mount to be /mnt/c - doesn't respect /etc/wsl.config or c: via mount

### ISSUE THREAD

**Issue by cicorias** [WhitewaterFoundry/WLinux#212]
During Cassandra install, the script part that creates the BAT file in the users Windows home path fails.

**To Reproduce**
1. Modify /etc/wsl.config so that mount is `/c` and not `/mnt/c` (this was advised [here](https://github.com/WhitewaterFoundry/WLinux/blob/master/linux_files/setup#L883) ).
2. run wlinux-setup and choose Cassandra

### Looks like `wslupath -H` is not reporting directly.  
see https://github.com/wslutilities/wslu/issues/40

```
cicorias@cicoria-razer:~$ wslupath -H
/mnt/c/Users/cicorias
cicorias@cicoria-razer:~$ cat /etc/wsl.conf
[automount]
root=/
enabled = true
options = "metadata,uid=1000,gid=1000,umask=22,fmask=11,case=off"
mountFsTab = true

[network]
generateHosts = true
generateResolvConf = true
```

**Expected behavior**
Should respect the mount of C: at /c or read wsl.config

**Screenshots**
![image](https://user-images.githubusercontent.com/1080406/48876254-1cac5480-edcb-11e8-942e-02424ef96c15.png)

[X] I have searched Google for the error message.
[ X I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[X] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[X] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[X] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[X] I have disabled and re-enabled WSL in Windows Features.
[X] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**WLinux Version**
`1.1.25.0`
**Windows Build**
```
systeminfo | findstr /C:"OS"
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17134 N/A Build 17134
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              American Megatrends Inc. 5.11, 2/23/2018
```

**Comment by sirredbeard** [comment]
Thanks for reporting. Still ironing bugs out in Cassandra.

**Comment by sirredbeard** [comment]
wslupath is being deprecated. #213 

We will need to apply these edits to the Cassandra script as well.

**Comment by sirredbeard** [comment]
Edits made in #223 and live on development branch.
