### ISSUE TITLE
Right Click <Open WLinux Here> in ConEmu

### ISSUE THREAD

**Issue by LittleNewton** [WhitewaterFoundry/WLinux#218]
I'm a Chinese user. Now days I want to use WLinux in the CLI just like **Open Terminal Here** in Ubuntu with one right click . I know it can be done with some wlinux-setups, but I want to use it in ConEmu. That is because the UI of the default WLinux CLI is very ugly, I could not even change the default font to my favorite Consolas.

Using ConEmu maybe a good BEAUTIFUL idea. But I don't know how to set task in setting menu of ConEmu.

Can you help me?

I want the task setting information for ConEmu. I cannot do that myself, because I have no idea of powershell programming.

Thanks!

**Comment by patrick330602** [comment]
Thank you for the suggestion but we will keep the original console. To change font in windows console, please right click titlebar-> properties->Font->Font to change fonts. for ConEmu, you should visit [here](https://conemu.github.io/en/BashOnWindows.html) and [here](https://conemu.github.io/en/SettingsIntegration.html) for reference.
