### ISSUE TITLE
Feature request: preinstall fish

### ISSUE THREAD

**Issue by int19h** [WhitewaterFoundry/WLinux#22]
The [fish shell](https://fishshell.com/) is becoming very popular for developers that are new to Linux,  because of its many convenience features, but also due to its philosophy of not sticking too much to the old and obscure design of the Bourne shell, making it easier to learn from scratch. It would be nice to have that out of the box.

**Comment by sirredbeard** [comment]
I like fish too. I didn't want to force my preferences though, wanted to wait and hear from community. First requests were for zsh, I think fish is next. I am going to leave this open for discussion for now but I think it's a no-brainer.

**Comment by sirredbeard** [comment]
Coming as a shell option in 1.1.20.
