### ISSUE TITLE
Enable Windows Explorer shell integration error

### ISSUE THREAD

**Issue by gao4263** [WhitewaterFoundry/WLinux#220]
**Describe the bug**
Starting wlinux-setup.
Applying Hotpatches
1: Applying temporary workaround for bug #199
alias clear="clear -x"
Selected: EXPLORER
EXPLORER
Enabling Windows Explorer shell integration.
Saving current directory as $CURDIR
Going to $TMPDIR: /tmp/tmp.xzqNbEsai0
cp: cannot create regular file '/mnt/c/Users/ThinkPad/AppData/Local/Temp'$'\r''/Install.reg': No such file or directory
ERROR: Error opening the file. There may be a disk or file system error.
Returning to /root
Cleaning up /tmp/tmp.xzqNbEsai0

**WLinux Version**
1.1.25.0

**Windows Build**
Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:
OS 名称:          Microsoft Windows 10 专业版
OS 版本:          10.0.17134 暂缺 Build 17134
OS 制造商:        Microsoft Corporation
OS 配置:          独立工作站
OS 构件类型:      Multiprocessor Free
BIOS 版本:        LENOVO R0FET44W (1.24 ), 2018/8/8

**Comment by patrick330602** [comment]
This is duplicate to #219. This bug is fixed and I am waiting for other member to check and approve.
