### ISSUE TITLE
Changing /mnt/c to /c cause computer ducuments lost

### ISSUE THREAD

**Issue by chenjuntong** [WhitewaterFoundry/WLinux#221]
**Describe the bug**
In the install process of docker bridge, when WLinux asking me to change /mnt/c to /c, I input OK and then it reported thousands of rm error, Permission denied, it seems the process search every directory in my computer to change /mnt/c to /c, I don't dare to stop it, and at the same time I found out that in my windows explorer most of my directories,most of my documents,most of my programs are disappeared! 

**To Reproduce**
1. Follow the wlinux-setup to install docker.
2. It will ask you to change /mnt/c to /c.
3. It reports thousands of rm error, Permission denied —— every directory in PC.
4. I have tried wlinux-setup for many times, but this is the first time I met this huge problem.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/10879155/48937235-6bcbc400-ef48-11e8-98c5-6439a6c18217.png)
![image](https://user-images.githubusercontent.com/10879155/48937269-82721b00-ef48-11e8-8e22-d315035580e0.png)

**WLinux Version**

![image](https://user-images.githubusercontent.com/10879155/48937340-c1a06c00-ef48-11e8-8fb2-f966f177d8d4.png)

version: 1.1.25.0

Insert here:

**Windows Build**

I couldn't even run systeminfo!
Windows10 1809

**Comment by chenjuntong** [comment]
@patrick330602 Please help! Is there a chance I can find my data back?

**Comment by patrick330602** [comment]
I am very sorry for the problem caused. I have changed in the master branch to prevent further destruction.

**Comment by grufwub** [comment]
I am very sorry for this issue, it was a fix that worked for my machine but must have been a solution only
for an anomalous / edge-case system.

'rm' only removes filesystem reference to files, but with minimal system usage the file will still remain.
If you follow this guide: https://www.digitalcitizen.life/how-recover-accidentally-deleted-files inputting
c:/ as the location to search you should be able to recover your files.

Again, sorry for the inconvenience.

**Comment by sirredbeard** [comment]
@chenjuntong 

I sincerely apologize this bug resulted in data loss. That is literally our worst case scenario. The issue has been patched. We are going to make structural changes to prevent this from happening again.

If you do not have backups I am glad to reimburse you up to $100 USD for the cost of data recovery software or services. Please submit a receipt to contact@whitewaterfoundry.com.
