### ISSUE TITLE
How can I transfer the current Windows-Explorer to wlinux.exe

### ISSUE THREAD

**Issue by LittleNewton** [WhitewaterFoundry/WLinux#224]
**Is your feature request related to a problem? Please describe.**
I was frastrated with the environment variables bewteen WSL and Windows. I want to know how to transfer the current directory's path to wlinux.exe so with that I will be able to create a new bash shell from the current path. And I found one more bug, if I open an default wlinux console and drag a file folder into it, it shows a Windows style PATH and this PATH value cannot be understood by UNIX/Linux OS directly. Just like below:

![default](https://user-images.githubusercontent.com/17793356/48963978-b8131480-efd9-11e8-91fd-33d85af6605a.png)

However, when I drag-and-drop on ConEmu, things are better:

![conemu](https://user-images.githubusercontent.com/17793356/48963980-bc3f3200-efd9-11e8-9427-fcabafc9e34c.png)

**Describe the solution you'd like**
- PLEASE fix the Drag&Drop bug
- PLEASE tell me how to transfer the current path to wlinux.exe
- If you can ,please tell me why you don't want to provide ConEmu support in details. I think ConEmu is a very elegant console emulator.

**Describe alternatives you've considered**
I have been working for find a method which can share the ENV_VARS between Windows and WSL and I really find [one](https://blogs.msdn.microsoft.com/commandline/2017/12/22/share-environment-vars-between-wsl-and-windows/)

**Additional context**
Please make Wlinux better. I spent some RMBs for it just want to make some donation for Open Source community.

**Comment by crramirez** [comment]
Also in Windows 1809 Press Shift key and right click any folder in explorer you will see Open with Linux without installing anything extra from wlinux-setup
