### ISSUE TITLE
Bug: zsh, neovim and python3.7 are not preinstalled

### ISSUE THREAD

**Issue by int19h** [WhitewaterFoundry/WLinux#23]
https://whitewaterfoundry.com/WLinux/ says:

> Popular development tools, including zsh shell, git, neovim, and python 3.7 pre-installed. 

Zsh and NeoVim are not actually installed out of the box.

Python 3 is installed, but the version is 3.5. Additionally, with the default sources.list, there's no way to install `python3.7` (it's in `testing`, but not in `stable`).

**Comment by int19h** [comment]
I'm confused - if the Store version is older than GitHub, does this mean that preinstalled apps were *removed* in upstream?

(the version that I'm running is installed from Store)

**Comment by int19h** [comment]
Oh, nevermind - you're saying that the main page lists features in upstream, rather than in Store?

**Comment by sirredbeard** [comment]
Yes, sorry, I needed to clarify.

To catch you up:

```
cd /etc/apt/
sudo cp sources.list sources.list.old
sudo rm sources.list
sudo wget https://raw.githubusercontent.com/WhitewaterFoundry/WLinux/master/linux_files/sources.list
sudo apt-get update
sudo apt-get install neovim zsh -y
sudo apt -t testing install python3.7 -y

```

**Comment by sirredbeard** [comment]
I have added a better explanation to the FAQ [here](https://github.com/WhitewaterFoundry/WLinux/wiki#why-didnt-the-store-version-come-with-x-feature-listed-on-the-GitHub).
