### ISSUE TITLE
WLinux wslfetch has errors when executed and has unexpected output

### ISSUE THREAD

**Issue by n3rd4i** [WhitewaterFoundry/WLinux#230]
**Describe the bug**
`wslfetch` produce unexpected output when called from command line.

**To Reproduce**
1. WLinux distribution installed
1. Run command: `wslfetch`
4. See error: 
	``` sh
	$ wslfetch
	/usr/bin/wslsys: line 82: /mnt/c/Windows/System32/reg.exe: No such file or directory
	/usr/bin/wslsys: line 82: /mnt/c/Windows/System32/reg.exe: No such file or directory
	/usr/bin/wslsys: line 82: /mnt/c/Windows/System32/reg.exe: No such file or directory
	/usr/bin/wslsys: line 82: /mnt/c/Windows/System32/reg.exe: No such file or directory
	/usr/bin/wslsys: line 82: /mnt/c/Windows/System32/reg.exe: No such file or directory
	/usr/bin/wslsys: line 82: /mnt/c/Windows/System32/reg.exe: No such file or directory
	```
1. Optional, see logo:
``` sh

         _,met$$$$$gg.               Windows 10 Linux Subsystem
      ,g$$$$$$$$$$$$$$$P.            [andrei@home]
    ,g$$P""       """Y$$.".          BUILD:     Build:
   ,$$P'              `$$$.          BRANCH:    Branch:
  ',$$P       ,ggs.     `$$b:        RELEASE:   Debian GNU/Linux 9 (stretch)
  `d$$'     ,$P"\'   .    $$$        KERNEL:    Linux 4.4.0-18282-Microsoft
   $$P      d$\'     ,    $$P        UPTIME:    0d 0h 20m
   $$:      $$.   -    ,d$$'         PACKAGES:  655
   $$\;      Y$b._   _,d$P'
   Y$$.    `.`"Y$$$$P"'
   `$$b      "-.__
    `Y$$
     `Y$$.
       `$$b.
         `Y$$b.
            `"Y$b._
                `""""
```

**Expected behavior**
`wslfetch` is expected to not produce errors when executed (preferably show **WLinux logo** instead of Debian logo)

**Basic Troubleshooting Checklist**

[x] I have searched Google for the error message.
[x] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[x] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[x] I have disabled and re-enabled WSL in Windows Features.
[x] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**WLinux Version**

Find: Settings->Apps->Apps & features->WLinux->Advanced Options->Version.

Insert here: `1.1.22.0`

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:

``` cmd
OS Name:                   Microsoft Windows 10 Pro Insider Preview
OS Version:                10.0.18282 N/A Build 18282
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              LENOVO*
```

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by sirredbeard** [comment]
Did you move your /mnt/c?

Please file a bug upstream with wslu.

**Comment by n3rd4i** [comment]
is it possible to transfer issue like in this link?
https://help.github.com/articles/transferring-an-issue-to-another-repository/#transferring-an-open-issue-to-another-repository

**Comment by jasoneckert** [comment]
Just add PATH=$PATH:/mnt/c/Windows/system32 to the top of the /usr/bin/wslfetch shell script to fix this issue.
