### ISSUE TITLE
WLinux screenfetch hangs when executed

### ISSUE THREAD

**Issue by n3rd4i** [WhitewaterFoundry/WLinux#231]
**Describe the bug**
`screenfetch` hangs when called from command line.

**To Reproduce**
1. WLinux distribution installed
1. Run command: `sudo apt install -y screenfetch`
1. Run command: `screenfetch`
4. See error: 
	``` sh
	$ screenfetch

	```
5. bash hangs here...

**Expected behavior**
`screenfetch` to work and output WLinux logo with the system information.

**Basic Troubleshooting Checklist**

[x] I have searched Google for the error message.
[x] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[x] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[x] I have disabled and re-enabled WSL in Windows Features.
[x] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**WLinux Version**

Find: Settings->Apps->Apps & features->WLinux->Advanced Options->Version.

Insert here: `1.1.22.0`

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:

``` cmd
OS Name:                   Microsoft Windows 10 Pro Insider Preview
OS Version:                10.0.18282 N/A Build 18282
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              LENOVO*
```

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by sirredbeard** [comment]
Please file an issue with the [upstream project](https://github.com/KittyKatt/screenFetch). Thank you.

**Comment by n3rd4i** [comment]
is it possible to transfer issue like in this link?
https://help.github.com/articles/transferring-an-issue-to-another-repository/#transferring-an-open-issue-to-another-repository

**Comment by fquinner** [comment]
Fwiw, it seems this is due to trying to use dysfunctional X tools which hang rather than fail (`xdpyinfo` etc). Easiest workaround for now is simply to run with this to unset your `DISPLAY` variable before running which stops it from checking  stuff.:

```
DISPLAY= ./screenfetch-dev
```

Sorry I know this is a stale issue but google brought me here so I'm leaving a beacon behind.
