### ISSUE TITLE
wlinux-setup missing and Backspace doesn't work

### ISSUE THREAD

**Issue by LittleNewton** [WhitewaterFoundry/WLinux#235]
It's enough! Holy shit!! software you have built.

when I open Wlinux, all bugs it echos.

![2018-11-29_122900](https://user-images.githubusercontent.com/17793356/49199360-5d5f2b80-f3d2-11e8-92af-507250d3db59.png)

Buying this software is one of the most foolish decision I have ever made.

**Comment by sirredbeard** [comment]
I have made many foolish decisions that cost much more than $10.

We should all be as lucky as you.

The issues you are having are very unusual.

It is unclear though if you have attempted any of the recommended troubleshooting.

Nonetheless please alliw me to offer a full refund by forwarding the Microsoft Store confirmation email to contact@whitewaterfoundry.com.

**Comment by LittleNewton** [comment]
It's not my fault that you don't understand Chinese. After all, you can't ask all users to be proficient in English. I really don't want to hurt developers, but your software is too disappointing.

Wlinux-setup has never been successful on my computer. I couldn't add a right-click menu before, but this time the GUI couldn't be loaded.

I had to use the word garbage to describe your bad work. I highly recommend that you test your code before releasing a new update.

Maybe you work hard and submit new code every day, but this is not a sufficient condition for a good work.

I hope that you will not be hurt by me. Adding new features is far less important than making existing programs more stable.

Also, $10 is also money, and if it is not necessary, $1 should not be wasted.

**Comment by LittleNewton** [comment]
I find the reason...just see the image.

![2018-11-29_165827](https://user-images.githubusercontent.com/17793356/49210483-27cd3900-f3f8-11e8-9ab9-509487317eba.png)

**Comment by sirredbeard** [comment]
I see normal console output.

Please allow me to offer a full refund by forwarding the Microsoft Store confirmation email to contact@whitewaterfoundry.com.

**Comment by crramirez** [comment]
Hello,

Older versions of WLinux don't come with wlinux-setup but they come with
/etc/setup. Please add the following to your /etc/profile

# alias wlinux helper apps


alias wlinux-setup='bash /etc/setup'


alias wlinux-help='bash /etc/helpme'

Regards

**Comment by DarthSpock** [comment]
Sorry but it was already in there! This is something else. Maybe /etc/profile isn't being processed completely through?
