### ISSUE TITLE
Feature request: set environment variables in /etc/environment where possible

### ISSUE THREAD

**Issue by int19h** [WhitewaterFoundry/WLinux#25]
`DISPLAY` and `LIBGL_ALWAYS_INDIRECT` are set in /etc/profile currently. This works with broadly Bourne-compatible shells like bash and zsh, but not with fish.

Debian has /etc/environment, which is not shell-specific. It would be nice to set any variables that do not require conditional setting, variable expansion etc there, so that they work as broadly as possible regardless of the choice of login shell.

**Comment by sirredbeard** [comment]
Docs say /etc/environment is not executed as a shell script, so would [this](https://github.com/WhitewaterFoundry/WLinux/pull/27) be sufficient to start?

**Comment by sirredbeard** [comment]
Added to /linux_files/ and image build script.

**Comment by sirredbeard** [comment]
This seems to be working. Has been packaged into 1.1.17rc.

Please comment and re-open if needed.

Thank you.
