### ISSUE TITLE
Cannot disable Explorer shell integration

### ISSUE THREAD

**Issue by dazjjackson** [WhitewaterFoundry/WLinux#252]
**Describe the bug**
Once shell integration has been enabled in wlinux it cannot be disabled

**To Reproduce**
1. Run wlinux-setup and enable Explorer shell extensions
2. Run wlinux-setup again and disable shell extensions

**Expected behavior**
Shell extensions should be disabled

**Actual Behaviour**
Error message:

Disabling Windows Explorer shell integration.
Saving current directory as $CURDIR
Going to $TMPDIR: /tmp/tmp.7MSa1pu27V
cp: cannot stat 'Install.reg': No such file or directory
ERROR: Error opening the file. There may be a disk or file system error.

**Solution**
As at release 1.1.27.0 is to edit:
linux_files\setup (line 735)
change:
cp Install.reg ...
To:
cp Uninstall.reg ...

**WLinux Version**

1.1.27.0

**Comment by crramirez** [comment]
If you want the credit for this fix you can submit a pull request

**Comment by crramirez** [comment]
You did it right. Thanks a lot

**Comment by sirredbeard** [comment]
Thank you @dazjjackson!
