### ISSUE TITLE
Mount hyper-v virtual disks in WLinux

### ISSUE THREAD

**Issue by davidwincent** [WhitewaterFoundry/WLinux#255]
**Is your feature request related to a problem? Please describe.**
File system performance in windows subsytem for linux is still a bit mediocre. As an example I tried running git checkout on a medium/large open source project. No download times are included in the tests.

**Describe the solution you'd like**
Virtual machine like file system performance

**Describe alternatives you've considered**
Checked options to mount virtual hard drives in WSL, did not find any.

**Additional context**

Steps to reproduce test:

`$ cd ~/`

`$ git clone git@github.com:umbraco/Umbraco-CMS.git`

`$ cd Umbraco-CMS`

`$ rm -rf *`

`$ rm .*`

`$ git checkout -b clean && git add . && git commit -m "clean"`

`$ time git checkout dev-v7`

**Results**
All tests where run on the same host machine. This is my output from running `$ time git checkout dev-v7` in the home folder on 3 different setups.

All setups had the following git config:

`$ git config --global core.preloadindex true`

`$ git config --global core.fscache true`

`$ git config --global gc.auto 256`

*Setup 1*
Ubuntu server 18.10 running under hyper-v with Linux filesystem on mounted .avhdx drive.
git version 2.19.1
```
real	0m0.373s
user	0m0.204s
sys	0m0.168s
```

*Setup 2*
Git for windows bash
git version 2.19.2.windows.1 (symlinks enabled)
```
real    0m3.437s
user    0m0.000s
sys     0m0.015s
```

*Setup 3*
WLinux
git version 2.19.2
```
real	0m41.530s
user	0m0.500s
sys	0m4.484s
```

**Comment by davidwincent** [comment]
Same issue is raised on Apr 11, 2016 in the Windows developer feedback form, https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/13386252-filesystem-slow-compared-with-native-ubuntu-system

Please vote if you want this to happen.

**Comment by sirredbeard** [comment]
It is possible to exclude WLinux from Windows Defender to improve performance. This is not recommended or supported but you can try it.

**Comment by crramirez** [comment]
I have done it and it improves a lot the performance. But it is still slow.

I don't know if something can be done from WLinux side, probably by using
FUSE.

But this is an issue for Microsoft and the WSL engine to support that.

Regards
