### ISSUE TITLE
Does WLinux has full support for network and devices?

### ISSUE THREAD

**Issue by lukaszog** [WhitewaterFoundry/WLinux#259]
I wonder if WLinux have full support for networking (iptables, arp) and devices  /dev, lsusb. Can anyone say something about it?

**Comment by DarthSpock** [comment]
Wlinux is unable to provide features that aren't inherited from WSL itself. If WSL supports it, then all the distros support it. See the appropriate WSL issues but there's limited support for iptables at this time and you're able to mount devices that use a supported file format but if you're looking for ext support, it doesn't exist currently. See the UserVoice for that. I personally have a removable hdd attached that I can navigate to via WSL and is auto-mounted via wsl.conf but PnP isn't supported in WSL as it is in Windows (you still have to manually mount it).
