### ISSUE TITLE
Proposal: WLinux OOBE

### ISSUE THREAD

**Issue by patrick330602** [WhitewaterFoundry/WLinux#26]
I hope to make a Out-Of-Box-Experience when people first start using WLinux, rather than pre-installing so many packages. I believe this will not be the first priority of this project now but I will leave this here for discussion.

**Comment by sirredbeard** [comment]
Were you thinking like 'flavors'?

**Comment by patrick330602** [comment]
@sirredbeard not technically flavors, mostly like choosing what shell to use, which editor you like to use, will you use GUI applications in WSL, etc., so that people can install only the packages they want. For instance, I personally preferred the original vim than neovim, so I actually uninstalled the package after updates. I think adding more pre-installed packages will make WLinux a bit bloated. two other ways can be done if possible:

- An alternative package installer(like `pkg` in Termux)
- A specific package server(for requested packages, not my own package server since it contains some packages of my other projects)

First method can be more easily done since they can also replace the installation scripts that is put in the `/opt/` folder.

**Comment by sirredbeard** [comment]
@patrick330602 

So are you thinking of a user onboarding script?

I think that is very doable.

We could set it to execute on first run in /etc/profile. 

We could even put it in /etc/profile.

Give people a choice of shells and dev tools and download/set them up as necessary*.

We could let users know if they wanted to run X apps they need an X client on Windows and use error codes to check to see if it is working.

* I also agree we need a uniform package sourcing strategy, before we overwhelm the build image with make scripts.

I think in terms of sourcing packages we should prioritize as follows:
-Debian stretch (apt)
-Debian testing (apt)
-Outside apt repo
and then maybe Linuxbrew?

**Comment by patrick330602** [comment]
@sirredbeard Yeah, kind like that, but I don't think using linuxbrew is a good idea... Homebrew is already so broken on my OS X machine

**Comment by sirredbeard** [comment]
@patrick330602 

According to Repology, https://repology.org/, the top repos ordered by the number of fresh packages include mostly apt-based repos, all of which we can easily tap, not to mention PPAs.

We are just going to have to find workaround for the tiny number of packages not available anywhere on PPAs, perhaps on a case-by-case basis.

**Comment by sirredbeard** [comment]
The onboarding script should check for an updated version of itself from the GitHub and download it if there is one.

That way every user installing from GitHub or Store (after the onboard script is pushed) will have access to latest packages listed.

See my comment [here](https://github.com/WhitewaterFoundry/WLinux/issues/32#issuecomment-424039512):

> one possibility is the onboarding script can check for updated versions of itself from GitHub, giving users the latest shell and dev tool options, regardless of which version they use, and address occasional feature mismatch between GitHub and Store version.
