### ISSUE TITLE
Is there a specific reason to mount C: to /c/ instead of /mnt/c/ ?

### ISSUE THREAD

**Issue by mabdelfattah** [WhitewaterFoundry/WLinux#261]
I'm using RubyMine, and I'm using WSL as a remote interpreter, the problem is RubyMine is looking for Ruby Gems in */mnt/c/* and the drive is mounted to */c/*

Honestly, I'm not sure who is wrong in this situation, but Microsoft says in their WSL documentation that it should be mounted to */mnt/c/*

https://docs.microsoft.com/en-us/windows/wsl/faq#how-do-i-access-my-c-drive

**Comment by patrick330602** [comment]
I believe this is RubyMine's fault. Current version of `wslpath` built-in in the WSL already converts Windows path dynamically into the mounted path.
