### ISSUE TITLE
Fix missing rbenv depdencies

### ISSUE THREAD

**Issue by IamYazen** [WhitewaterFoundry/WLinux#269]
**Is your feature request related to a problem? Please describe.**
After WLinux setup is complete I am recommended to use the wlinux-setup tool.
However, I run into issues while doing so.

**Describe the solution you'd like**
- Synchronize package index before running scripts
- If a wizard item requires a C compiler (i.e Ruby) then install one before attempting to compile Ruby...
- etc

**Comment by patrick330602** [comment]
Thank you telling us the issue. We will looking into it.

**Comment by IamYazen** [comment]
Thank you

Further observations:
After installing dependencies for Ruby I was able to complete the Ruby/rbenv wizard, but it did not add ~/.rbenv/shims to my PATH (I selected fish as my shell).

Not a huge deal since I have done this manually many times, but the little details are always appreciated.

**Comment by sirredbeard** [comment]
Almost all scripts that install packages via apt run apt update and apt upgrade first.

We should do a check just to be sure.

We should also make sure we are installing build-essential before installing Ruby.

We should also look into rbenv and fish.

**Comment by crramirez** [comment]
@IamYazen this is a fix for rbenv and fish: https://github.com/crramirez/WLinux/commit/efca47a586e49d0b0e3c73a0aca5d39e6ae2fb93

You can test it. It will be included in next release
