### ISSUE TITLE
Mount filesystem from diskimage / block device

### ISSUE THREAD

**Issue by davidwincent** [WhitewaterFoundry/WLinux#274]
**Is your feature request related to a problem? Please describe.**
Can not mount filesystem from diskimage / block device

**Describe the solution you'd like**
`> losetup /dev/loop0 <path to diskimage file> `
should mount storage device on /dev/loop0

**Describe alternatives you've considered**
Mounting virtual disk

**Additional context**
I tried to mount a ext4 diskimage to WLinux using the following steps:

`> sudo su -`
ok

`> dd if=/dev/zero of=/root/local-usr-misc bs=1M count=4096`
ok

`> mkfs.ext4 /root/local-usr-misc`
ok

`> mkdir /usr/local/misc`
ok

`> losetup /dev/loop0 /root/local-usr-misc`
fails with: `losetup: /dev/loop0: failed to set up loop device: No such file or directory`

**Comment by crramirez** [comment]
Hello,

This is not supported in the current version of Windows even FUSE is not
supported at this time.

Regards
