### ISSUE TITLE
Building for x64 is dependent on ARM64 and vice versa

### ISSUE THREAD

**Issue by ThatWeirdAndrew** [WhitewaterFoundry/WLinux#275]
**Describe the bug**
When you run build.bat for x64, it errors out because it can't find the ARM64 files, even though you only want to build for x64.

**To Reproduce**
1. Follow BUILDING.MD steps for building x64 up until running build.bat
2. Run build.bat and it gives the error.

**Expected behavior**
You should be able to build x64 or ARM64 without the install.tar.gz for the other platform.

**Screenshots**
![annotation 2018-12-22 202202](https://user-images.githubusercontent.com/14946103/50379975-d21b3380-0627-11e9-93b4-ae3004f68d91.jpg)

**Basic Troubleshooting Checklist**

[ ] I have searched Google for the error message.
[ ] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[ ] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[ ] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[ ] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[ ] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**WLinux Version**

1.1.27

Insert here:

**Windows Build**

Windows 10 Pro Insider Preview 10.0.18305 Build 18305

**Comment by sirredbeard** [comment]
We are still working on ARM64 building.

**Comment by Riccorl** [comment]
> We are still working on ARM64 building.

He says that he can't build x64 because it asks for ARM64 files.

**Comment by ThatWeirdAndrew** [comment]
> > We are still working on ARM64 building.
> 
> He says that he can't build x64 because it asks for ARM64 files.

Yes. That's what I mean. Even if I only want to build for x64, it forces me to create the ARM64 files as well.

**Comment by sirredbeard** [comment]
I see what you mean.

If you want to build just for x64 you will need to edit the .bat file.
