### ISSUE TITLE
Add ll alias

### ISSUE THREAD

**Issue by Xeonacid** [WhitewaterFoundry/WLinux#278]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
There is a common alias in other systems, the `ll`, standing for `ls -al` or sth similar. Could you add it into `~/.bash_aliases`?
**Describe alternatives you've considered**
`alias ll='ls -al'`
**Additional context**

**Comment by sirredbeard** [comment]
Is `ll` a common alias that other users use?

**Comment by sirredbeard** [comment]
Then let's include it.
