### ISSUE TITLE
Open with WLinux fails in top level directory

### ISSUE THREAD

**Issue by ogdenpm** [WhitewaterFoundry/WLinux#282]
**Describe the bug**
The Open with WLinux context menu fails if the root folder e.g. c:\ is selected. A command window appears very briefly and disappears.

**To Reproduce**
1. Open Explorer
2. Select drive C: in the folders pane
3. Right click on the background in the files pane and select Open with WLinux

**Expected behaviour**
Expect the command window to open in directory /mnt/c

**Additional context**
Shell is bash

**Basic Troubleshooting Checklist**

[X ] I have searched Google for the error message.
[X ] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[X ] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[X ] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[ ] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[ X] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?
Potentially an issue in expanding %V in the command line to a value ending in \

**WLinux Version**

1.1.27.0

**Windows Build**
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              American Megatrends Inc. 0602, 19/10/2018

**Comment by patrick330602** [comment]
Sorry for the waiting. This problem has been identified, and will be live in the next release.
