### ISSUE TITLE
Open with WLinux does not work again ...

### ISSUE THREAD

**Issue by michalkvasnicka** [WhitewaterFoundry/WLinux#286]
After last update the right click menu command "open with WLinux" does not work again (error message: APPLICATION NOT FOUND ).

**Comment by patrick330602** [comment]
could you describe what happened? like which folder you try to open, and the version of your WLinux. Methods of getting these information can be found in New Issue->Bug Report

**Comment by michalkvasnicka** [comment]
I am using latest version of WLinux. Problem occurs in any attempt to try open WLinux for any directory.

**Comment by sirredbeard** [comment]
I can confirm on 1.1.27 running updated wlinux-setup from GitHub.

**Comment by sirredbeard** [comment]
And running wlinux-setup from development branch with patch for #282 installed.

**Comment by patrick330602** [comment]
@sirredbeard @michalkvasnicka I think I know there the problem is... Could you show the output of your following commands in WLinux?
1. `whereis wlinux.exe`
2. `which wlinux.exe`
3. `where.exe wlinux.exe`

**Comment by michalkvasnicka** [comment]
whereis wlinux.exe :
wlinux: /mnt/c/Program Files/WindowsApps/WhitewaterFoundryLtd.Co.16571368D6CFF_1.1.27.0_x64__kd1vv0z0vy70w/wlinux.exe /mnt/c/Users/micha/AppData/Local/Microsoft/WindowsApps/wlinux.exe

which wlinux.exe:
/mnt/c/Users/micha/AppData/Local/Microsoft/WindowsApps/wlinux.exe

where.exe wlinux.exe:
C:\Program Files\WindowsApps\WhitewaterFoundryLtd.Co.16571368D6CFF_1.1.27.0_x64__kd1vv0z0vy70w\wlinu
x.exe
C:\Users\micha\AppData\Local\Microsoft\WindowsApps\wlinux.exe
