### ISSUE TITLE
Yarn repo GPG missing

### ISSUE THREAD

**Issue by patmolloy** [WhitewaterFoundry/WLinux#289]
Not sure if this is a real issue or not, but has worked previously.

patmolloy@XPS13-2018-LAPTOP:~$ sudo apt-get update
Hit:1 http://security.debian.org/debian-security stable/updates InRelease
Hit:7 https://apt.patrickwu.ml stable InRelease
Ign:3 https://cdn-aws.deb.debian.org/debian stable InRelease
Hit:4 https://cdn-aws.deb.debian.org/debian stable-updates InRelease
Hit:5 https://cdn-aws.deb.debian.org/debian stretch-backports InRelease
Hit:6 https://cdn-aws.deb.debian.org/debian testing InRelease
Hit:8 https://cdn-aws.deb.debian.org/debian stable Release
Err:2 https://dl.yarnpkg.com/debian stable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
W: Failed to fetch https://dl.yarnpkg.com/debian/dists/stable/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by sirredbeard** [comment]
It appears that the key for yarnpkg is not properly installed.

Try the following to re-install it:
```
curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
```

**Comment by patmolloy** [comment]
Thanks, this has done the trick!

------ Original Message ------

**Comment by rahulbshrestha** [comment]
Thanks!

**Comment by RuslanSkiraRaccoongang** [comment]
it is working for Mac?
