### ISSUE TITLE
I set filec in WLinux csh shell but it does not work using either tab or esc

### ISSUE THREAD

**Issue by oldcoder47** [WhitewaterFoundry/WLinux#294]
**Describe the bug**

After "set filec" is entered, one should be able to get filename completion by typing TAB.  Instead I just get a real TAB inserted instead

**To Reproduce**
see above

**Expected behavior**
see above

**Screenshots**

**Additional context**

**Basic Troubleshooting Checklist**

[x ] I have searched Google for the error message.
[ x] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[ x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[ x] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[ x] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[ x] I have disabled and re-enabled WSL in Windows Features.
[ x] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**WLinux Version**

Find: Settings->Apps->Apps & features->WLinux->Advanced Options->Version.

Insert here:

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by oldcoder47** [comment]
WLinux version is  1.1.27.0
OS Version:                10.0.17134 N/A Build 17134

**Comment by sirredbeard** [comment]
Is this reproducible on other WSL distros? I wonder if it a console issue.

**Comment by oldcoder47** [comment]
I don't have another distro on my machine.  However I put WSL/Ubuntu on my wife's machine some time ago.  filec works on her machine.
Her uname -a gives:
Linux FB 4.4.0-17134-Microsoft #523-Microsoft Mon Dec 31 17:49:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
My uname -a gives:
Linux DP1 4.4.0-17134-Microsoft #523-Microsoft Mon Dec 31 17:49:00 PST 2018 x86_64 GNU/Linux

My stty -a gives:
speed 38400 baud; rows 89; columns 197; line = 0;
intr = ^C; quit = ^Q; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = M-^?; swtch = M-^?; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; discard = ^O;
min = 1; time = 0;
-parenb -parodd -cmspar cs8 hupcl -cstopb cread -clocal -crtscts
-ignbrk brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc ixany imaxbel iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc

Her stty -a gives:
speed 38400 baud; rows 45; columns 182; line = 0;
intr = ^C; quit = ^Q; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = M-^?; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V;
discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 hupcl -cstopb cread -clocal -crtscts
-ignbrk brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc ixany imaxbel iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc

**Comment by oldcoder47** [comment]
This is not a problem with the whole distribution.  It does not happen in bash.  It only happens in csh.  In addition, when I press the up arrow to get to a previous command, csh only responds with ^[
If I go to bash directly and then type just "csh" I get to csh without invoking my .login file.  The same problems happen, so nothing in my .login file is causing this.

Are there alternate implementations of csh, and if so, how do I install them?

**Comment by oldcoder47** [comment]
I switched to Ubuntu1804 and that worked perfectly.  I am just giving up on WLinux.  It does not work right and neither does this support group.
