### ISSUE TITLE
Add logic to install correct platform Go binaries

### ISSUE THREAD

**Issue by sirredbeard** [WhitewaterFoundry/WLinux#306]
At https://github.com/WhitewaterFoundry/WLinux/blob/2d0f94b30f040a139ca8ecb1edba298e63f7ecbf/linux_files/setup#L666

and

https://github.com/WhitewaterFoundry/wlinux-setup/blob/cfc134e520f5e696fd7f3dc86131d7d0cb148337/wlinux-setup.d/go.sh#L10

Need to det3ct/install arm64 binaries on arm installation.

**Comment by sirredbeard** [comment]
![11892dd5-7558-4f19-8025-9b0ae7f76d64](https://user-images.githubusercontent.com/33820650/51442268-44c01300-1ca9-11e9-83ce-e29f13b8aae5.jpeg)

**Comment by crramirez** [comment]
Hello

What is the output of  `uname -m` in an ARM machine running WSL?

Thanks
