### ISSUE TITLE
Error 0x80070002 initializing WLinux distro

### ISSUE THREAD

**Issue by vancura** [WhitewaterFoundry/WLinux#31]
Previously filed on WSL: https://github.com/Microsoft/WSL/issues/3567. They claim it's not in WSL as both Kali and Ubuntu initialize without problems.

---

I am trying to install [WLinux distro](https://whitewaterfoundry.com/WLinux/), but so far it's failing for me due to old `0x80070002`. My console legacy mode is *off*.

* Your Windows build number: 10.0.18242.1000 (Insiders fast)

* What you're doing and what's happening: 
```
wlinux
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070002
Error: 0x80070002 The system cannot find the file specified.
```

* What's wrong / what should be happening instead:
Initialize [WLinux distro](https://whitewaterfoundry.com/WLinux/).

ETLs [here](http://vncr.in/0506d0ec3e3b).

Is there anything I can do to fix it? People recommend reinstallation of Windows, but that's an overkill for me now.

Thanks,
V.

**Comment by sirredbeard** [comment]
The fact WLinux doesn't even show up after wslconfig.exe list as described [here](https://github.com/Microsoft/WSL/issues/3567#issuecomment-423844953) leads me to believe that it is in fact the issue or related to the issue described by Ben [here](https://github.com/Microsoft/WSL/issues/3499#issuecomment-415482073).

WLinux isn't even being initiated, so I do not believe it is not a WLinux "repo" issue. 

WLinux also uses the exact same wrapper code as the Debian and Kali distro, so there is nothing there "extra" to break.

Can you try:

1. `wslconfig /list /all` and post results?

2. `wslconfig /unregister <all the distros listed by above>`

3. Reinstalling WLinux from Store.

3. Then, only if that doesn't work, disabling WSL in Features, rebooting, and then re-enabling, an re-installing WLinux?

**Comment by vancura** [comment]
```
C:\Users\vacla>wslconfig /list /all
Windows Subsystem for Linux Distributions:
Debian (Default)
kali-linux
```

```
C:\Users\vacla>wslconfig /unregister Debian
Unregistering...

C:\Users\vacla>wslconfig /unregister kali-linux
Unregistering...

C:\Users\vacla>wslconfig /list /all
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
```

(Uninstalled everything, Debian, Kali, and WLinux → install WLinux from Store)

```
C:\Users\vacla>wslconfig /list /all
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore

C:\Users\vacla>wlinux
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070002
Error: 0x80070002 The system cannot find the file specified.

Press any key to continue...
```

Disabling WSL, rebooting and re-installing: I tried the exactly same yesterday, but I'll do it today later after work again. Let's see...

**Comment by sirredbeard** [comment]
I want to keep working on this. If for some reason this still doesn't work for you after above troubleshooting, I would be glad to issue you a full refund (just forward your Store e-mail to hayden at whitewaterfoundry.com or screenshot and DM to twitter WLinuxApp with details and your PayPal or Zelle information) or, alternatively, I can provide you access to a sideload build to try while we work through this issue. Thank you for your patience and for helping us debug this,

**Comment by patrick330602** [comment]
I am also on 18242.1000, but I cannot reproduce that on my machine, and after checking, it seems that there is a continuous failure in your Windows kernel during installation. I believe it is the issue of the instability of lxcore.sys in this build, since I also had GSOD on lxcore.sys in this build days ago.

**Comment by vancura** [comment]
Thanks for the refund offer, but I'd rather keep WLinux, I'll reinstall this machine sooner or later anyway, I tend to break stuff so it's always a good idea to start fresh :)

**Comment by vancura** [comment]
> Then, only if that doesn't work, disabling WSL in Features, rebooting, and then re-enabling, and re-installing WLinux?

Didn't work :(

Nm, I'll reinstall the machine eventually.

**Comment by vancura** [comment]
Rollback to pre-insiders? I am afraid I can't, it's way long ago :(

**Comment by sirredbeard** [comment]
No, just the previous build, not out of insiders.

Under Settings, Update & Security, Recovery, does it give you "Go back to the previous version of Windows 10" with a "Get Started" button?

**Comment by vancura** [comment]
Yup, I'll try that.

**Comment by sirredbeard** [comment]
Also see: https://github.com/Microsoft/WSL/issues/2967#issuecomment-390489270

**Comment by vancura** [comment]
FYI:

![image](https://user-images.githubusercontent.com/4982/46559580-0caae500-c8f1-11e8-8d1c-13945b59c691.png)

They fixed it :)

**Comment by sirredbeard** [comment]
Yay!

**Comment by vancura** [comment]
Well, there's something else, but I really don't have any idea where this one could be...

![image](https://user-images.githubusercontent.com/4982/46560597-a45e0280-c8f4-11e8-8064-75fb8f29ce07.png)

**Comment by sirredbeard** [comment]
Sigh.

I just saw another report of this here: https://twitter.com/_p9tr/status/1048020436892573696

This is before any specific WLinux code kicks in.

In that case it looks like he had a legacy WSL install that didn't migrate properly.

Did you have WSL prior to Fall Creators Update, or as it was known then "Bash for Windows from Ubuntu"?

**Comment by vancura** [comment]
To be honest, I don't remember, sorry. I think I installed Fall Creators from ISO this spring, so later than it was released.

**Comment by vancura** [comment]
Status update: FINALLY!

![image](https://user-images.githubusercontent.com/4982/47138883-d4c17b80-d2ba-11e8-84e0-515a827fcd14.png)

Thanks!

**Comment by dexter-dz** [comment]
in future just try 
`wsl --set-default-version 2` in powershell and install the wsl2 kerrnel from[WSL 2 Kernel]( https://aka.ms/wsl2kernel) and rreboot.
