### ISSUE TITLE
wlinux-setup .wget-hsts update error

### ISSUE THREAD

**Issue by bushidocodes** [WhitewaterFoundry/WLinux#312]
**Describe the bug**

On a fresh installation, it seems like wlinux-setup generates a .wget-hsts file that it is later able to modify

**To Reproduce**
1. On a fresh install, run `wlinux-setup` and say yes to update
2. This generates a .wget-hsts file with `-rw-rw-rw- 1 sean sean`
3. Quit 
4. Run `wlinux-setup` and say yes to update
5. setup seems to fail to update silently saying that it can't update .wget-hsts

**Expected behavior**

**Screenshots**

**Additional context**

**Basic Troubleshooting Checklist**
I was able to get around this by changing the .wget-hsts file to 755 permissions. Here is a before and after comparison:
-rwxr-xr-x 1 sean sean  215 Jan 23 11:16 .wget-hsts
-rw-rw-rw- 1 sean sean  215 Jan 22 20:44 wget-hsts-old

[X] I have searched Google for the error message.
[X] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[X] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[X] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[X] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[X] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**WLinux Version**

Find: Settings->Apps->Apps & features->WLinux->Advanced Options->Version.

Insert here:
![image](https://user-images.githubusercontent.com/8700322/51624763-8949e980-1f09-11e9-9ac0-e681acfa817f.png)

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:
Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:

C:\Users\Sean>systeminfo | findstr /C:"OS"
OS Name: Microsoft Windows 10 Pro
OS Version: 10.0.17763 N/A Build 17763
OS Manufacturer: Microsoft Corporation
OS Configuration: Standalone Workstation
OS Build Type: Multiprocessor Free
BIOS Version: LENOVO JBET71WW (1.35 ), 9/14/2018

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by ThatWeirdAndrew** [comment]
Tested it and this seems to fix the problem.
