### ISSUE TITLE
VSCode doesn't launch on WLinux Terminal in WSL

### ISSUE THREAD

**Issue by EfstathiadisDimitris** [WhitewaterFoundry/WLinux#313]
I am running Windows 10 Home, latest Build, `Version	10.0.17763 Build 17763`. I have downloaded and installed WLinux, as my WSL Distro. I have VSCode in both Windows and WSL installed. But my problem is the following:

If I type  `code .` as usual, I get nothing. If I type `Code .` , I have VSCode from Windows side opened in system32 directory.

I am using the following setting for VSCode
```
    "terminal.external.windowsExec": "C:\\Windows\\System32\\wsl.exe",
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\wsl.exe",
```
Also the WSL terminal is stuck in that process forever. I need to abort the process and VSCode closes as well at that point. This seems like a bug. Either that, or I am doing something wrong.

I can open the file with vim, on wsl, but I cannot find my wsl directory from Windows to open it from there, neither initiate VSCode from my terminal directly.

Can you please confirm, and if this isn't a bug tell me how to fix it. Basically open my WSL files, in which I have set git/ssh/more, with VSCode if I type `code .`, like I normally do. Thank you!!

**Comment by crramirez** [comment]
Hello,

I recommend installing Visual Studio Code again from wlinux-setup and make sure you tell wlinux-setup to update itself to the latests version. We recently made a patch to downgrade two packages that were causing problems.

Why you put a dot after code?

Regards

**Comment by EfstathiadisDimitris** [comment]
@crramirez I put the dot, after the code, because I want to open VSCode in that specific directory. That's how I do it in pure Linux and Windows and Mac. Maybe I don't need it here.

As far the solution is concerned, it worked, but I had the same behavior after I closed the terminal. Had to reinstall VSCode through `wlinux-setup`. You can close this, if you feel, this is not a bug, but it clearly worked after I updated and reinstalled. After I close the terminal I have to reinstall VSCode every time.

**Comment by crramirez** [comment]
Hello,

This is not the expected behaviour and you shouldn't need to run wlinux-setup everytime you open the terminal. Maybe it is a path issue. Resetting and reinstalling is a good approach. 

When I say upgrade wlinux-setup to the latest version I am talking about the installer. Wlinux-setup ask everytime it starts if you want to run with the latest, be sure you answer yes.

When you run apt-get upgrade after installing code it should say something about udev and libudev are being kept on hold, this is what prevents code from stop working. 

Regards

**Comment by HowardEdidin** [comment]
I am having a similar issue.  I just typer in `code`
I am getting the following.

> You are trying to start vscode as a super user which is not recommended. If you really want to, you must specify an alternate user data directory using the --user-data-dir argument.

How do I configure this?

**Comment by crramirez** [comment]
Hello @howardedidin

You are starting code from the root user. Just close WLinux and type code again. 

Regards

**Comment by alexsmartens** [comment]
@HowardEdidin,
I'm running `Ubuntu 18.04` inside a docker container and seeing the same error message. VScode doesn't startup with specifying --user-data-dir flag too.
How have you solved your problem?
