### ISSUE TITLE
No zsh

### ISSUE THREAD

**Issue by nkhdo** [WhitewaterFoundry/WLinux#32]
**Describe the bug**
No zsh on fresh installation

**To Reproduce**
1. Buy Wlinux from Windows store
2. Start it

**Expected behavior**
I think it should use `zsh` by default. However I get a bash prompt and have to install zsh by myself

**Info**
Windows Build: 17134.285

**Comment by sirredbeard** [comment]
See my comment [here](https://github.com/WhitewaterFoundry/WLinux/issues/23#issuecomment-423859593).

**Comment by sirredbeard** [comment]
I added an entry to the FAQ section of the Wiki [here ](url
![image](https://user-images.githubusercontent.com/33820650/45963790-fdbf5b00-bff1-11e8-96d7-7a522b64998b.png)
)because this has come up twice now.

**Comment by nkhdo** [comment]
Thanks for the info!

**Comment by sirredbeard** [comment]
Sorry for the confusion. If you feel like you were duped in any way I apologize and will gladly refund you upon request, just forward the store purchase confirmation e-mail to hayden @ whitewaterfoundry.com with your preferred e-payment method. Thank you for purchasing the app though and taking a bet on us.

**Comment by nkhdo** [comment]
No problem, I bought it just to support your efforts. Keep up the good work!

**Comment by sirredbeard** [comment]
@nkhdo It is not just me but @patrick330602 too with some commits and testing from others.

We usually do not touch existing installations, in keeping with existing WSL distro practice, although you will get updates to wslu through @patrick330602's apt server.

So generally yes, you will have to do a fresh install to get latest features pre-configured, for now.

We are discussing the possibility of an onboarding process here #26 and one possibility is the onboarding script can check for updated versions of itself from GitHub, giving users the latest shell and dev tool options, regardless of which version they use, and address occasional feature mismatch between GitHub and Store version.

For now I recommend you backup your dotfiles to something like c:\user\nkhdo\dotfiles\ and you can simply copy them back over or ln -s them after your fresh install. To do so you can go into Settings, Apps, Apps & features, WLinux, Advanced options, Reset to do a quick fresh install.

**Comment by nkhdo** [comment]
Thanks alot!
