### ISSUE TITLE
fish shell doesn't work on WLinux

### ISSUE THREAD

**Issue by bbhopesh** [WhitewaterFoundry/WLinux#321]
fish shell is not working for me in Wlinux on WSL. There is some `waitpid in process_mark_finished_children: Invalid argument` message which is printed infinitely.

Windows Version 1709 (OS Build 16299.125)

**Comment by sirredbeard** [comment]
When is it occurring? During install or whenever launched from the shell?

**Comment by bbhopesh** [comment]
Whenever shell is launched.

**Comment by Fulg** [comment]
FWIW, version 2.2.0 (installed via `apt install fish` in WSL) works fine. Latest release (3.0.1) suffers from the bug reported above. After launching the shell, you never reach an interactive prompt.

This is likely an issue with WSL on 1709.

![image](https://user-images.githubusercontent.com/3320405/52639438-46dd5200-2ea2-11e9-9264-c8240c2ef108.png)

**Comment by bbhopesh** [comment]
I get fish 3.0.0 using apt!!

**Comment by crramirez** [comment]
Thank you @Fulg. I couldn't find a machine with 1709 for testing.

@bbhopesh meanwhile you can upgrade your Windows version, please run the following script to get fish 2.4

```
echo 'deb https://deb.debian.org/debian stretch main' | sudo tee /etc/apt/sources.list.d/stretch.list
sudo apt-get update
sudo apt-get install -y --allow-downgrades -t stable fish=2.4.0-1 fish-common=2.4.0-1 
sudo apt-mark hold fish fish-common
```

**Comment by Fulg** [comment]
Since I am also stuck with 1709 at work, I found that fish 2.7.1 works fine over there. Fish 3.0 (either from `apt` or self-compiled from source) has that `waitpid` issue.

At home my machine is updated to 1803, where I can run the latest fish (3.0.1) without issues.

**Comment by bbhopesh** [comment]
Thanks everyone for help. I upgraded to 1803 and fish is working fine now.

**Comment by crramirez** [comment]
You are welcome
