### ISSUE TITLE
Certificate verification failed

### ISSUE THREAD

**Issue by jeremy-breidenbach** [WhitewaterFoundry/WLinux#323]
**Describe the bug**
With a fresh install of WLinux, attempted to run wlinux-setup. When the setup tool runs I see numerous errors stating, `Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification.` I am unsure if this is due to my workplace network or if an issue in WLinux. 

**To Reproduce**
1. Download WLinux
2. Run wlinux-setup

**Expected behavior**
Expect that WLinux is able to download packages and install software without certificate errors. 

**Additional context**
WSL Ubuntu is installed on my system and works correctly. Only experiencing the errors in WLinux. 

**Basic Troubleshooting Checklist**

[X] I have searched Google for the error message.
[X] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[X] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[X] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[X] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
  - Did not attempt this as WSL Ubuntu does work correctly. 
[ ] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**WLinux Version**
WLinux version not found in Advanced Settings. WLinux downloaded from Windows Store on 02/11/2019. 

Insert here:

**Windows Build**
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.16299 N/A Build 16299

**Comment by crramirez** [comment]
Hello,

Could you try issuing a sudo apt update && sudo apt upgrade ? Probably the
root certificates are old. I assume it happens when you choose to update
wlinux-setup to the latest version.

If this doesn't solve you the problem, could you run wlinux-setup --debug
and send the output?

Regards
