### ISSUE TITLE
Use windows remote desktop connection

### ISSUE THREAD

**Issue by mayankmetha** [WhitewaterFoundry/WLinux#33]
Make use of windows remote desktop connection to run gui based linux apps on windows

**Comment by sirredbeard** [comment]
Could you elaborate a bit more on what you had in mind?

People are already doing things with xrdp and WSL: https://www.youtube.com/watch?v=JcmGaGS2Gpc

**Comment by sirredbeard** [comment]
Closing as a duplicate of #19.
