### ISSUE TITLE
libssl that ships with WLinux too new for VSCode python language server

### ISSUE THREAD

**Issue by adampiskorski** [WhitewaterFoundry/WLinux#330]
**Describe the bug**
When the Python Extention of VSCode uses the Python Language Server, you get the error `No usable version of the libssl was found`. The workaround is straight forward, but since Python 3.7 and VScode are first class citizens in WLinux, I think that they should work together out of the box. 

**To Reproduce**
1. Open VScode
2. Install the Python
2. In settings set `"python.jediEnabled": false,` to use the Python Language Server
3. Reload the window (ctrl + shitf + p then type in Reload Window then enter)
3. Open any Python file
4. Look at the Output tab for Python and observe the 5 attempts at connecting to the Python Language server with each attempt giving the error.

**Expected behavior**
In the output field for Python, you should see `Microsoft Python Language Server version 0.1.78.0` or similar version.

**Screenshots**
![libssl_python_error png](https://user-images.githubusercontent.com/7703045/52868857-0f460280-314d-11e9-9b56-3d43c1b4c789.jpg)

**Additional context**
I am running the latest version of WLinux by updating it with the WLinux utility

**Basic Troubleshooting Checklist**

[X] I have searched Google for the error message.
[X] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[X] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[X] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[ ] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[ ] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

I have found a workaround by just installing an older version with `sudo apt install libssl1.0.2`

**WLinux Version**

Find: Settings->Apps->Apps & features->WLinux->Advanced Options->Version.

1.1.28.0

**Windows Build**

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              American Megatrends Inc. 1.80, 11/17/2017

**Comment by ThatWeirdAndrew** [comment]
Tested it and it fixes the problem.
