### ISSUE TITLE
boot WLinux as standard linux distro on boot 

### ISSUE THREAD

**Issue by hltdev8642** [WhitewaterFoundry/WLinux#332]
Hello,

Is it possible to boot the Wlinux filesystem natively instead from the windows bootmanager (or refind grub etc)?

Like a dual boot system, but be able to either boot in at start, or access the linux system via wsl.

For reference I have a surface pro 5, and I know that its neccesary to disable secure boot ...etc. More curious of whether this can be done or not, and if so is there a particular way to do it succesfully ?

Thanks

**Comment by Biswa96** [comment]
You can use it in chroot jail or as a container in docker, kubernetes etc. But to boot using WLinux is different. You need a booloader, kernel, init (system, sysV, upstart etc.) etc. WLinux just adds some packages and files on top of Debian.

**Comment by sirredbeard** [comment]
No.

The closest you can get is launching VcXsrv and booting into a Linux desktop after logging into Windows, see https://github.com/NathanCastle/BootShellCredentialProvider.

This requires extensive and advanced customization of Windows.
