### ISSUE TITLE
dotnet install via wlinux-setup doesn't find command

### ISSUE THREAD

**Issue by jtourlamain** [WhitewaterFoundry/WLinux#337]
**Describe the bug**
I used the wlinux-setup command to install dotnet and NuGet. After installing dotnet core I would expect to be able to run
`dotnet new`
The only thing I get is "zsh: command not found: dotnet"

**To Reproduce**
1. Go to wlinux-setup
2. Click on dotnet and also install the NuGet package
3. close wlinux-setup after installation
4. run "dotnet new" 
5. result: zsh: command not found: dotnet

**Expected behavior**
command should work and I can create a new dotnet project

**Additional context**
I used a fresh installed WLinux.

Installing dotnet on wsl ubuntu (via [MS docs](https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install)) dotnet could be found in /usr/bin/dotnet. I looked in the wlinux distro after installing dotnet via wlinux-setup but couldn't find it there. So, what was installed when running the command and where was it installed?

**Basic Troubleshooting Checklist**

[x] I have searched Google for the error message.
[x] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[ ] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[x] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[x] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**WLinux Version**

Find: Settings->Apps->Apps & features->WLinux->Advanced Options->Version.

Insert here: 1.1.28

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              HP N75 Ver. 01.20, 28/11/2017

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by crramirez** [comment]
Hello,

As I understand you use ZSH. We will check it and give you an answer soon.

Regards

**Comment by jtourlamain** [comment]
Yes, I use ZSH. The only things I installed were installed via the wlinux-setup. ZSH was one of them.
