### ISSUE TITLE
Bounty: Help debug quirks with Chrome 69+ on WSL ($50 USD)

### ISSUE THREAD

**Issue by sirredbeard** [WhitewaterFoundry/WLinux#37]
**Describe the bug**

The new Google Chrome is acting strangely in X clients on WSL.

On VcSrvX it is triggering a core dump: https://twitter.com/ueyasu/status/1044583330912526337

On X410 this is happening:  
![capture4](https://user-images.githubusercontent.com/33820650/46019234-9ebd1d00-c0a9-11e8-875b-7b16cc77ac28.PNG)

This is somewhat erratic, even across other WSL distros, I do not think it is isolated to WLinux.

Commenting out ALWAYS_LIBGL_INDIRECT=0 in /etc/profile sometimes appears to make a difference, _but not consistently_.

**To Reproduce**

1. Install WLinux or other Debian-based WSL distro.
2. `$ wget https://github.com/WhitewaterFoundry/WLinux/blob/master/linux_files/installchrome.sh`
3. `$ bash installchrome.sh`
4. Accept install.
5. `$ google-chrome`

**Expected behavior**

Chrome works.

**Info**

X410 1.7.3
Windows Build 17134

**Additional context**

Because Chrome has announced more logging and tracking of users, I am generally amenably pulling it and shipping a separate browser for people to try on WSL, like Falkon or Epiphany.

**Workaround**

Comment out ALWAYS_LIBGL_INDIRECT=0 in /etc/profile and restart WLinux or use an alternate browser.

**Comment by patrick330602** [comment]
Interesting. On build 18242.1000 chrome directly crashed with following error:
```
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Permission denied
[1]    2100 trace trap (core dumped)  google-chrome
```
It might be the reason that some features required in chrome is not implemented well on WSL

**Comment by sirredbeard** [comment]
One suggestion from Twitter: chrome --disable-gpu [link](https://twitter.com/coswata/status/1044898062190010368)

**Comment by patrick330602** [comment]
`chrome --disable-gpu` actually still not working properly in 18242.1000

**Comment by sirredbeard** [comment]
I am converting this to a public bounty. Help WLinux make Chrome 69+ more stable on WSL by (1) submitting a workaround for WSL distros or (2) help us isolate the issue and submit a bug report upstream to Google. Currently $50 USD.

**Comment by sirredbeard** [comment]
Bug bounty is cancelled.

**Comment by kochandra** [comment]
Not sure if anyone is till finding this as an issue but below works...
Just Open WSL as Admin and run "$ google-chrome" :) not sure why it needs to be as such

**Comment by Johnlon** [comment]
Using wsl2 opening wsl bash as admin opens and entirely different environment than the one I'm using in my user account.

**Comment by sunyinqi0508** [comment]
You may want to try the following flags
google-chrome --no-sandbox  --disable-gpu --disable-features=VizDisplayCompositor
