### ISSUE TITLE
Purchase outside of Windows store 

### ISSUE THREAD

**Issue by frmz** [WhitewaterFoundry/WLinux#40]
I would love to support this project but my laptop doesn't have access to the store due to company policy restrictions. Normally I install wsl distros through chocolatey, is there any alternative to get it outside of official store?

**Comment by sirredbeard** [comment]
That is a great question. Not to my knowledge _at the present time_. We do not have, nor do we want, to implement a second web store or more restrictive DRM. Even if we could release on a separate store once we provided the .appx it could be duplicated. There are date-limited certificates _possibly_ as a solution. I still prefer people either build the actual source or buy the releases though.

I did okay enterprise and educational licenses, so if your employer was so inclined they could buy an enterprise license through the Store and deploy it to your machine, but if your employer is like most probably not.

As a possible workaround though if you bought the app from your personal Store account and forward me the e-mail confirmation at hayden at whitewaterfoundry.com, I can send you a link to a test build I distribute among the regular contributors.

**Comment by itadder** [comment]
Can I buy it on a none work device and copy to work device ? I donot want to do anything illegal? Just legit ownership?

**Comment by itadder** [comment]
Does chocolate offer a way to pay for downloads?

**Comment by frmz** [comment]
I have checked a few alternative installers and unfortunately i see no options outside of windows store, i think we can close this :(
