### ISSUE TITLE
Error 0x8007007b

### ISSUE THREAD

**Issue by sirredbeard** [WhitewaterFoundry/WLinux#45]
**Describe the bug**

Tracking this one-off WSL bug.

No current known issues or workarounds.

Error report comes back to a Windows activation problem.

Attempting troubleshooting.

If issue continues, we will follow [Microsoft](https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#starting-bash-gives-an-error-code) here and file issue upstream in WSL to collaborate with Microsoft and other distros on solution.

**To Reproduce**

Unknown at this time.

**Expected behavior**

WLinux registers.

**Screenshots**

![dobzwpyucaax5a5](https://user-images.githubusercontent.com/33820650/46082940-4bf96900-c16e-11e8-9efa-4d717bb5ae60.jpg)

**Info**
Windows Build:

![dobfalsv4aezjop](https://user-images.githubusercontent.com/33820650/46082961-561b6780-c16e-11e8-98c7-dfc258fd1604.jpg)

**Additional context**

Twitter thread: https://twitter.com/happou31/status/1044933383875248128

**Comment by Bean8128** [comment]
I also received a similar error, except mine read 

WslRegisterDistribution failed with error: 0x80070003 
Error: 0x80070003 The filename, directory name, or volume label syntax is incorrect.

And fixed it by moving the WLinux app from my secondary drive to my main drive (don't know why Windows store repeatedly installed it to my secondary drive by default when all my other apps and distros install to my main drive by default). 

Don't know if this is the same problem but hopefully this might help?

**Comment by spica021** [comment]
Bean8128, Thanks!
In my case, Error 0x8007007b occurred.
It was fixed by moving WLinux app from D drive to C drive.

**Comment by Joss** [comment]
I've faced with the same issue after full reinstall WLinux (W10 64, 1809). Fixed it also by moving WLinux app to system C: drive.
