### ISSUE TITLE
Support snaps by porting Ubuntu 14.04 systemd shim to WLinux

### ISSUE THREAD

**Issue by sirredbeard** [WhitewaterFoundry/WLinux#46]
snaps do not work well on WLinux because of a systemd dependency and systemd does not work well on WSL.

This is a placeholder for an idea to better support snaps by porting the systemd shim created by snap to backport snap to Ubuntu 14.04, which ran upstart not systemd.

https://blog.ubuntu.com/2017/03/30/snaps-are-now-available-for-ubuntu-14-04-lts-desktop-and-server

**Comment by sirredbeard** [comment]
We should consider and test snapd from Ubuntu trusty:

https://launchpad.net/ubuntu/trusty/+source/snapd

**Comment by ThatWeirdAndrew** [comment]
I found instructions on how to install snap packages on MX Linux which doesn't use systemd. Looking into it, however, it's not perfect.

[https://mxlinux.org/wiki/applications/snap-packages-mx-17](url)

**Comment by ThatWeirdAndrew** [comment]
We could look at implementing flatpak support as there is an experimental version of flatpak that works on WSL.

[https://github.com/flatpak/flatpak/tree/wip/WSL](url)

**Comment by sirredbeard** [comment]
I have played with flatpak support, it is on the ROADMAP.md.

I have also sort of gotten snapd to work on a 14.04 image but I can't 
get it to work downgrading a 16.04 image.

**Comment by Bodup** [comment]
> I have played with flatpak support, it is on the ROADMAP.md.

@sirredbeard The most recent version of flatpak on the repository is out of date. Installing applications usually results in a `needs a later flatpak version (0.10.0)` error. (currently 0.8.9)

**Comment by sirredbeard** [comment]
Closing this as out of scope for our project at this time.
