### ISSUE TITLE
Original Logo for WLinux Concepts Discussion

### ISSUE THREAD

**Issue by sirredbeard** [WhitewaterFoundry/WLinux#5]
WLinux needs an original logo. What we have right now is used under license but is not original.

Designers are encouraged to submit your rough concepts for a new original logo here. I am looking for something that fits the Windows 10 minimalistic aesthetic but clearly identifies WLinux _as_ Linux. Please include the best way to reach you, such as Telegram, e-mail, etc.

Users are invited to submit feedback on the concepts submitted. I will review the concepts and select one to be developed based on the feedback here. 

Bounty terms:
- If your logo concept is selected to be developed you must provide a color logo on a transparent background in SVG at least 400x400px, a white logo on a transparent background in SVG at least 400x400px, a color .ICO file, and the raw files (.PSD, .XCF, etc.) for inclusion in the project. 
- You agree to assign ownership of the logo and copyright to Whitewater Foundry, Ltd. Co. and for the files to be distributed under the MIT license.
- I will retain discretion over the selection of the logo and payment of the bounty.
- You agree to be paid electronically.

Please direct any questions regarding this bounty to hayden at whitewaterfoundry.com or at WLinuxApp on Twitter. This is not a binding contract or an offer of employment.

Edit: PNG->SVG (thank you @Biswa96) and Twitter contact details.

**Comment by Biswa96** [comment]
Don't convert PNG files. Use SVG file as source then convert them to PNG files. See wsltty.appx repository. When Visual Studio (or others) converts PNG to lower resolution PNG it makes the picture blurry.

**Comment by sirredbeard** [comment]
Thank you @Biswa96. I will make that change in the proposal.

**Comment by sirredbeard** [comment]
It has been proposed that the logo potentially pay homage to Xenix. I like that idea.

Here are some examples of that artwork:

![intro-back](https://user-images.githubusercontent.com/33820650/46027407-c9b06c80-c0bb-11e8-9664-2518b09421a2.jpg)
![microsoft-unix-xenix](https://user-images.githubusercontent.com/33820650/46027408-c9b06c80-c0bb-11e8-8194-9088bb98bd02.jpg)
![thw2nwfs3r](https://user-images.githubusercontent.com/33820650/46027409-c9b06c80-c0bb-11e8-8f16-09f3519c9864.jpg)

Maybe a transparent Tux or "W" with the some of the retro horizontal lines in the "O" from the old Microsoft logo?

**Comment by danlin** [comment]
Something Like this?
![wlinux](https://user-images.githubusercontent.com/363604/46075932-5a567d80-c18c-11e8-838d-550dd4d36da2.png)
![image](https://user-images.githubusercontent.com/363604/46075917-4ad73480-c18c-11e8-8585-8feea14f5877.png)

**Comment by PhMajerus** [comment]
How about two L's for Linux, combined to make an X for Un*X and reminiscent of X11, merged with a W for Windows, all in a mix of 80's and MDL/Metro styles ?
It even ends up looking like it was designed as part of the Visual Studio family, making it look nice next to your other dev tools.

![wlinux slanted](https://user-images.githubusercontent.com/25664275/46091637-889b8380-c1b3-11e8-910b-159985298f76.png)
![wlinux on start](https://user-images.githubusercontent.com/25664275/46091643-8b967400-c1b3-11e8-9292-d46b5ddeffd7.png)

**Comment by Biswa96** [comment]
@PhMajerus Wow! Your idea & explanation is great :ok_hand: But it looks more like Visual Studio or VSCode. Also some mixing with Tux or Windows logo will be great :thinking:

**Comment by Wulfre** [comment]
I agree that the lines can get a bit fuzzy when the size of the icon becomes too small. I went with another simple design, keeping the same font of the 1982 Microsoft logo, but adding a bit of flourish to go in the direction of a water theme that the company name inspired me with.

![wlinux](https://user-images.githubusercontent.com/6633817/46121081-1f7e3500-c1e0-11e8-90b6-07cc8fa1d453.png)

**Comment by Biswa96** [comment]
If I were the "big boss", I'll choose 1. The idea of mixing L, X, W from @PhMajerus 2. The Tux feet, the color scheme and the simplicity from @danlin's idea :heart_eyes:

**Comment by danlin** [comment]
Today i add a litte more Tux to the font ;)
![wlinuxbg](https://user-images.githubusercontent.com/363604/46140950-cf8c8600-c252-11e8-814c-717a59cd6981.png)
![image](https://user-images.githubusercontent.com/363604/46140960-d3b8a380-c252-11e8-9318-f2af1fcb4fbf.png)

**Comment by PhMajerus** [comment]
Some more Xenix for inspiration, basically the closest thing to a logotype I saw so far.
![xenix ad 1981](https://user-images.githubusercontent.com/25664275/46147104-d3290880-c264-11e8-9196-567d506710e8.jpg)
(from Computerworld 12 Oct 1981)

**Comment by sirredbeard** [comment]
So many good options.

I think we are going to keep the discussion going, keep these concepts up, and going to go ahead and split the current bounty between existing submitters.

If we later move forward with one of them we will work with (read: pay) the selected designer to polish and submit to app.

@danlin @Wulfre and @PhMajerus: Please DM me at WLinuxApp on Twitter or hayden at whitewaterfoundry.com with your PayPal details.

**Comment by PhMajerus** [comment]
Rough shadow icon inspired by the Xenix ad:
![wlinux shadow logo](https://user-images.githubusercontent.com/25664275/46148588-b5f63900-c268-11e8-804c-ebbbc7c00036.png)

**Comment by sirredbeard** [comment]
We should also consider our options the option of keeping the existing Tux. It is [libre licensed](https://github.com/WhitewaterFoundry/WLinux/blob/master/LICENSE.md#artwork) and I have not heard many complaints about it.

The designers name is Erik Ragnar Eliasson and his work is featured [here](https://www.iconfinder.com/Sennerstad).

Tux is also [freely licensed](http://isc.tamu.edu/~lewing/linux/) and was actually part of a tutorial for GIMP.

**Comment by PhMajerus** [comment]
At least give Tux a 🐱‍👤 ninja cat red headband, and maybe a Microsoft flag :p
![ninjacat](https://user-images.githubusercontent.com/25664275/46174164-9252e300-c2a8-11e8-985a-86afc96c1b88.jpg)

**Comment by danlin** [comment]
only Tux better sizing and color:

![wlinux](https://user-images.githubusercontent.com/363604/46205447-e8fc0380-c320-11e8-9f29-f632fbd716bb.png)
![image](https://user-images.githubusercontent.com/363604/46205355-90c50180-c320-11e8-8ad1-bd10edfe13c4.png)

![wlinuxc](https://user-images.githubusercontent.com/363604/46205451-eac5c700-c320-11e8-94ae-c89ca0e8ee9d.png)
![image](https://user-images.githubusercontent.com/363604/46205405-c538bd80-c320-11e8-9fe9-66430f55c459.png)
