### ISSUE TITLE
Error resolving cdn-aws.deb.debian.org on sudo apt update

### ISSUE THREAD

**Issue by matsbror** [WhitewaterFoundry/WLinux#50]
**Describe the bug**

This is from a clean install of WLinux bought on Windows 10 Store. After insstall, I want to make a `sudo apt-get  update` 

**To Reproduce**
1. Install WLinux from store
2. Start WLinux
3. `sudo apt-get update`

```
Hit:1 http://security.debian.org/debian-security stable/updates InRelease
Hit:4 https://apt.patrickwu.ml stable InRelease
Err:2 https://cdn-aws.deb.debian.org/debian stable InRelease
  Could not resolve host: cdn-aws.deb.debian.org
Err:3 https://cdn-aws.deb.debian.org/debian stable-updates InRelease
  Could not resolve host: cdn-aws.deb.debian.org
```

**Expected behavior**

I would have expected an update to take place. 

**Info**
Windows Build: Version	10.0.17134 Build 17134

**Comment by sirredbeard** [comment]
My apt was able to resolve cdn-aws.deb.debian.org briefly but then packages were 404ing, so something was amiss over on AWS.

It seems to be working for me now, this is a brand new store install after a couple apt-update.

![capture](https://user-images.githubusercontent.com/33820650/46104487-73b5f480-c1a1-11e8-8aa9-34c6e09cb959.PNG)

We certainly don't do anything to apt server selection or DNS that would cause this issue.

If it continues, please report back.

**Comment by matsbror** [comment]
This is still an issue for me. I Installed also the Debian distribution on WSL and there I had no problems updating, so it seems not to be connected to Debian.
