### ISSUE TITLE
ValidateAppxPackage Failed while building WLinux

### ISSUE THREAD

**Issue by ThatWeirdAndrew** [WhitewaterFoundry/WLinux#53]
I am trying to build WLinux, but every time that i run build.bat, I get the error:

       "C:\Users\andre\Downloads\WLinux-master\DistroLauncher.sln" (Build target) (1) ->
       "C:\Users\andre\Downloads\WLinux-master\DistroLauncher-Appx\DistroLauncher-Appx.vcxproj.metaproj" (default targe
       t) (3) ->
       "C:\Users\andre\Downloads\WLinux-master\DistroLauncher-Appx\DistroLauncher-Appx.vcxproj" (default target) (4) ->
       (_ValidateAppxManifest target) ->
         C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPack
       age\Microsoft.AppXPackage.Targets(2624,5): warning : This project uses the 'runFullTrust' capability.  You shoul
       d use the Windows Application Packaging Project to produce the store and sideload packages. See https://go.micro
       soft.com/fwlink/?linkid=871803 for more information. [C:\Users\andre\Downloads\WLinux-master\DistroLauncher-Appx
       \DistroLauncher-Appx.vcxproj]

       "C:\Users\andre\Downloads\WLinux-master\DistroLauncher.sln" (Build target) (1) ->
       "C:\Users\andre\Downloads\WLinux-master\DistroLauncher-Appx\DistroLauncher-Appx.vcxproj.metaproj" (default targe
       t) (3) ->
       "C:\Users\andre\Downloads\WLinux-master\DistroLauncher-Appx\DistroLauncher-Appx.vcxproj" (default target) (4) ->
       (_ValidateAppxPackage target) ->
         C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPack
       age\Microsoft.AppXPackage.Targets(3132,5): error APPX0002: Task 'ValidateAppxPackage' failed. Could not find fil
       e 'C:\Users\andre\Downloads\WLinux-master\DistroLauncher-Appx\Package.StoreAssociation.xml'. [C:\Users\andre\Dow
       nloads\WLinux-master\DistroLauncher-Appx\DistroLauncher-Appx.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackag
       e\Microsoft.AppXPackage.Targets(3132,5): error APPX0002:  [C:\Users\andre\Downloads\WLinux-master\DistroLauncher
       -Appx\DistroLauncher-Appx.vcxproj]

I have tried rebuilding the solution but the same thing happens.

**Comment by patrick330602** [comment]
exclude `Package.StoreAssociation.xml` from project in Visual Studio then you can build it.

**Comment by sirredbeard** [comment]
Let me know if that worked for you @ThatWeirdAndrew. If not we can re-open and look again.

Thank you again for contributing to the project and supporting open source.

**Comment by xXDavidx** [comment]
for me it worked but now i have an error while building : 
![image](https://user-images.githubusercontent.com/43365173/46171411-b27ea400-c2a0-11e8-8393-3f9b44192ab4.png) P.S. sorry if i'm italian but it says that it can't access "C:\Users\hayden\Documents\Builds\DistroLauncher-Appx_1.1.17.0_Debug_Test" even if hayden is not my username and C:\Users\ isn't my users directory it's I:\

**Comment by sirredbeard** [comment]
Huh. Must be a path hard set somewhere in VS. I am going to re-open for others who are more familiar with the VS process to look into.

**Comment by xXDavidx** [comment]
well i found a file called _pkginfo.txt with that directory i will try an build it with that directory changed tomorrow

**Comment by ThatWeirdAndrew** [comment]
I have noticed that there is a file called Package.StoreAssociation.xml in the Solution but it can't find the file in the source code.

![help](https://user-images.githubusercontent.com/14946103/46182591-da6b0900-c29a-11e8-8578-144433f44c37.PNG)
![help1](https://user-images.githubusercontent.com/14946103/46182592-db039f80-c29a-11e8-8e75-5f82f6a8387c.PNG)

**Comment by ThatWeirdAndrew** [comment]
I also get the error: Payload file 'C:\Users\andre\WLinux\x64\Debug\DistroLauncher-Appx\wlinux.exe' does not exist.

I just copy wlinux.exe from \WLinux\x64\Debug to \WLinux\x64\Debug\DistroLauncher-Appx\ and that seems to work, but i'm not sure.

**Comment by patrick330602** [comment]
@ThatWeirdAndrew I believe you can exclude `Package.StoreAssociation.xml` as local build do not need it

**Comment by ThatWeirdAndrew** [comment]
Following @patrick330602's instructions, I was able to successfully build WLinux. However, I was unable to install it due to a certificate issue.

`Either a new certificate must be installed for this app package or you need a new app package with trusted certificates. Your system administrator or the app developer can help. A certificate chain was processed but terminated in a root certificate that isn't trusted (0x800B0109)`

**Comment by patrick330602** [comment]
@ThatWeirdAndrew Have you generated a new test certificate?

**Comment by Plics0** [comment]
For those with "hayden" folder trouble, execute the "Developer Command Prompt for VS 2017" as Admin. Then, run build.bat. It worked for me.

**Comment by xXDavidx** [comment]
hmm interesting now i think it builded but i can't find the certificate

**Comment by KrazySoft** [comment]
I'm having the same issue as @xXDavidx I've managed to build the project with no errors I've installed both the certificate found in the C:\Users\hayden\Documents\Builds\DistroLauncher-Appx_1.1.20.0_Debug_Test folder aswell as the DistroLauncher-Appx_TemporaryKey.pfx certificate found at WLinux\DistroLauncher-Appx even after installing both I am not able to install either the appx package found at  C:\Users\hayden\Documents\Builds\DistroLauncher-Appx_1.1.20.0_Debug_Test or at WLinux\x64\Debug\DistroLauncher-Appx

**Comment by ThatWeirdAndrew** [comment]
I was finally able to install by installing the DistroLauncher-Appx_1.1.17.0_x64_Debug.cer certificate and then installing the DistroLauncher-Appx_1.1.17.0_x64_Debug.appxbundle file.

**Comment by KrazySoft** [comment]
For anyone unable to find the certificate I found a work around
The first answer here:
https://stackoverflow.com/questions/23812471/installing-appx-without-trusted-certificate
describes how to find the certificate of an app package and install it, after following those steps I managed to install it

**Comment by xXDavidx** [comment]
@KrazySoft thanks for the work around anyways it worked

**Comment by sirredbeard** [comment]
@KrazySoft 

Thank you so much. I just wanted to warn everyone building from source that 1.1.20 is a tad buggy, you may want to download the 1.1.17 release final if you don't want to help debug.

@xXDavidx 

Are you trying to run it from a non-C:\ drive, by chance?

https://github.com/Microsoft/WSL/issues/3232
https://github.com/Microsoft/WSL/issues/3324

**Comment by sirredbeard** [comment]
@xXDavidx 

I am closing this thread because a workaround has been posted for the primary issue.

If you continue to have problems after reviewing the threads above, please open a new issue.

We now have a dedicated issue template for bash errors such as these with troubleshoot steps: https://github.com/WhitewaterFoundry/WLinux/issues/new/choose

**Comment by xXDavidx** [comment]
well yeah it worked, i don't know what to say i thinked the apps on the I:\ drive were disabled but i was wrong well thanks again @sirredbeard
