### ISSUE TITLE
api-ms-win-core-l2-2-0.dll was not found

### ISSUE THREAD

**Issue by sirredbeard** [WhitewaterFoundry/WLinux#57]
Appears to be an issue with Debian-based WSL distros and Visual Studio:

https://github.com/Microsoft/WSL/issues/3456#issuecomment-413006625

Debian released a patch for this by tweaking Visual Studio settings:

https://salsa.debian.org/rhaist-guest/WSL/commit/48efd0d70cc21982652a91bafd5b00fb44009f8e

We should have incorporated that patch but I need to go take a second look and make sure we are reflecting those changes.

In the mean time, enter "$ wslconfig.exe /s WLinux" and "bash.exe" to start WLinux.

**Comment by sirredbeard** [comment]
Need to rebase back to 16299.

**Comment by mmoossen** [comment]
Having the same problem with Open SUSE Leap 15 and Windows 10.0.16299
