### ISSUE TITLE
code execution cannot proceed because api-ms-win-core-console-l2-2-0.dll was not found

### ISSUE THREAD

**Issue by ket000** [WhitewaterFoundry/WLinux#60]
**Error Code**

---------------------------
wlinux.exe - System Error
---------------------------
The code execution cannot proceed because api-ms-win-core-console-l2-2-0.dll was not found. Reinstalling the program may fix this problem. 
---------------------------
OK   
---------------------------

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:

OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.16299 N/A Build 16299
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              HP N75 Ver. 01.16, 6/8/2017

**WSL Debug Data**

[etl.zip](https://github.com/WhitewaterFoundry/WLinux/files/2429868/etl.zip)

**Comment by sirredbeard** [comment]
This is likely the known issue with 1.1.15 on 16299, which also appeared in Debian and Ubuntu.

We patched it in 1.1.17.

Can you try uninstalling WLinux and re-installing version 1.1.17 from the Microsoft Store?

Thanks,

Hayden

**Comment by ket000** [comment]
I just installed wlinux today on Sept 29 after purchasing it from microsoft store. Are you saying you pushed a new version on microsoft store. Please let me know. When I installed this on windows 1803 it worked fine. 

Ketan

**Comment by patrick330602** [comment]
@ket000 yes, it is just released today. Uninstalling WLinux and re-installing version 1.1.17 should solve your problem.

**Comment by ket000** [comment]
Ok. I will try that. On my 1803 machine installing wlinux for a while and when I cancelled it, it started fine but with root user. Do you have instructions for adding normal user.

**Comment by patrick330602** [comment]
@ket000 this is due to the reason that the installation is completed but you accidentally skipped steps of user setup. You can solve this by following steps:
## creating a new user and set password
in your wlinux with root account:
```sh
useradd -m <yourname>
passwd <yourname>
usermod -a -G sudo <yourname>
```

## change default user:
in command prompt or powershell:
```cmd
wlinux.exe config --default-user <yourname>
```

**Comment by ket000** [comment]
Thanks. I found another tip to reset wlinux app which removes all settings
and start the install process again. It worked and added the default user.
Thanks for the prompt response.

Thanks

**Comment by ket000** [comment]
I am still getting this error, even after uninstalling and reinstalling wlinux on 1709. On 1803 it works fine. Please test this on a pc where 1709 is installed.

**Comment by ket000** [comment]
Please ignore. For some reason it was not getting updated version. Once I got the updated version, issue is resolved.
