### ISSUE TITLE
WLinux not visible in JetBrains products

### ISSUE THREAD

**Issue by mikart143** [WhitewaterFoundry/WLinux#64]
WLinux is not visible in wsl toolchain in JetBrains products

1. Open any JetBrains products with wsl toolchain

**Expected behavior**
Should be visible in HetBrains products

**Basic Troubleshooting Checklist**

[*] I have confirmed WSL is enabled: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[*] I have searched Google for the error message.
[*] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[*] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[*] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[*] I have disabled and re-enabled WSL in Windows Features.
[*] I have run Windows 10 updates and restarted.

**Comment by sirredbeard** [comment]
Huh. I wonder who we get in touch with over there to get added. As far as I know it is manual at this point. We have also asked to be listed on the WSL distro page on the Microsoft Store.

**Comment by mikart143** [comment]
Okay I understand. So I have to wait and use different distro at this time :/ I will wait for new updates

**Comment by crramirez** [comment]
Hello, 

If you configure WLinux as the default one via `wslconfig /s WLinux` you will see in wsl toolchain **Ubuntu (Legacy) bash.exe** it will use your environment in WLinux

Regards

**Comment by mikart143** [comment]
On my PC I have Kali linux and Wlinux. I Executed this command in PowerShell with admin. I could not find any other wsl then kali linux in jetbrains wsl toolchain in CLion

**Comment by sirredbeard** [comment]
We have reached out to Jet Brains and are working with their various teams to get WLinux included in the WSL bridge.
