### ISSUE TITLE
Hard coded path in project file

### ISSUE THREAD

**Issue by YellowGarbageBag** [WhitewaterFoundry/WLinux#70]
I tried to build the WLinux app with Visual Studio and there is a build error after launch the build.bat file.

`C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(4967,5): error MSB6003: Die angegebene ausführbare Datei der Aufgabe "MakeAppx.exe" konnte nicht ausgeführt werden. Der Zugriff auf den Pfad "C:\Users\hayden\Documents\Builds\DistroLauncher-Appx_1.1.20.0_Debug_Test" wurde verweigert. [D:\WLinux\DistroLauncher-Appx\DistroLauncher-Appx.vcxproj]`

I found out, that in your "DistroLauncher-Appx.vcxproj" is a hard coded path on line 85:
`<AppxPackageDir>C:\Users\hayden\Documents\Builds\</AppxPackageDir>`

**Comment by patrick330602** [comment]
try to run it with elevated prompt, this is a known issue in building.

**Comment by Biswa96** [comment]
@patrick330602 Try to use this to configure environment:
```bat
@echo off
::Set Environments for X86_64 build
cd %~dp0
call "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
where cl.exe link.exe msbuild.exe makeappx.exe
```
change `x64` according to your desired CPU architecture.

**Comment by ThatWeirdAndrew** [comment]
Try changing `C:\Users\hayden\Documents\Builds\` to `C:\Builds` and running it with an elevated prompt.

**Comment by ThatWeirdAndrew** [comment]
Tested it and it works fine with an elevated prompt.
