### ISSUE TITLE
Cannot open display when opening gedit example

### ISSUE THREAD

**Issue by DamionGans** [WhitewaterFoundry/WLinux#75]
I am wanting to use WLinux for running Linux apps on Windows 10 using the X410 software.
I am using latest updated versions of WLinux and X410 and am using the Windows 10 October update (build 1809).

At first I updated and upgraded all packages using apt update && apt upgrade.
I installed gnome-shell and gedit and am running x410 software.

When I run gedit I get the following message:

Unable to init server: Could not connect: Connection refused

(gedit:7): Gtk-WARNING **: cannot open display:

Am I doing something wrong? Thanks

**Comment by aborruso** [comment]
It's the same for me!

**Comment by sirredbeard** [comment]
That is odd.

I am having trouble reproducing:
![capture](https://user-images.githubusercontent.com/33820650/46263241-a8e08080-c4da-11e8-9668-b07c51931be1.PNG)

What shell are you running?

**Comment by aborruso** [comment]
@sirredbeard I'm using zsh

**Comment by sirredbeard** [comment]
Weird.

![capture](https://user-images.githubusercontent.com/33820650/46263409-cb739900-c4dc-11e8-9a3a-3b49551d381f.PNG)

**Comment by bheynemand** [comment]
In this commit, you copy the file "/linux_files/environment" to "/etc/profile".

https://github.com/WhitewaterFoundry/WLinux/commit/9e8eb9c9253ca9bf7041c81ba95312ad1c611f77
