### ISSUE TITLE
Just installed it and I have no python

### ISSUE THREAD

**Issue by aborruso** [WhitewaterFoundry/WLinux#76]
Hi,
I have Just installed WLinux and I have no python: `-bash: python: command not found`

**WLinux Version**

Find: Settings->Apps->Apps & features->WLinux->Advanced Options->Version.

Insert here: 1.1.17.0

**Windows Build**

10.0.17134.285

**Comment by sirredbeard** [comment]
You can run python 3.7 with `$ python3`.

If you install python 2, it will be `$ python2`.

**Comment by aborruso** [comment]
Hi,
I have just installed 1.1.20 and using python3 I have "command not found".
Is it normal, do I must install it?

I had understood that it was already installed.

Thank you

![image](https://user-images.githubusercontent.com/30607/46304191-4d7fc280-c5ae-11e8-97fe-8d32fb3a66e4.png)

**Comment by sirredbeard** [comment]
It is now installed by script.

Run $ bash /etc/setup and it will prompt you to install python and pip.

**Comment by Kilo59** [comment]
@sirredbeard Does the `/etc/setup` also add python and pip to the PATH?

**Comment by sirredbeard** [comment]
Yes. https://github.com/WhitewaterFoundry/WLinux/blob/master/linux_files/setup#L475

**Comment by bluermind** [comment]
I have no /etc/setup directory. I am using Pengwin Enterprise shell

**Comment by crramirez** [comment]
Hello @bluermind ,

Pengwin Enterprise doesn't come with /etc/setup or pengwin-setup, and doesn't come with pyhtion preisntalled. Please install it using the usual way for RHEL, CentOS or Scientific Linux.

Regards
