### ISSUE TITLE
Building on different drive fails (except C:\, e.g. D:\)

### ISSUE THREAD

**Issue by n3rd4i** [WhitewaterFoundry/WLinux#78]
**Describe the bug**
Trying to build on different-than-C:\-drive fails, with:
- stdafx.h could not be found, while the file exists!

**To Reproduce**
1. clone repo on **different-than-C:\-drive**
2. try to build with VS
3. Build fails with "[...]stdafx.h could not be found[...]"

**Expected behavior**
build should be sucessfull

**Screenshots**

**Additional context**

**Basic Troubleshooting Checklist**

[X] I have confirmed WSL is enabled: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[X] I have searched Google for the error message.
[X] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[X] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[X] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[X] I have disabled and re-enabled WSL in Windows Features.
[X] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**1.1.20**

Find: Settings->Apps->Apps & features->WLinux->Advanced Options->Version.

Insert here:

**Microsoft Windows [Version 10.0.17134.285]**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17134 N/A Build 17134

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by sirredbeard** [comment]
Not much about WSL works on drives other than C:\ in my experience.

**Comment by bheynemand** [comment]
Try to clone repo with Windows version of git instead of linux version.

**Comment by sirredbeard** [comment]
Also, does editing/using build.bat from the VS command line make a difference?

**Comment by n3rd4i** [comment]
>           Also, does editing/using build.bat from the VS command line make a difference?

I was trying that I got the same error.

But I would suggest to close this issue because it seems to be related to just one machine.
On different machine the `stdafx.h` was found successfully (building on different drive).

In case I would find a way to reproduce this later (on another machine) I could easily ask to reopen this issue or open new one then.

**Comment by sirredbeard** [comment]
Thank you. Let me know. I want to make sure it is easily buildable. If anything so people will learn how to make WSL distros and make them all better.
