### ISSUE TITLE
Partially OT: where to read in the store the WLinux version available?

### ISSUE THREAD

**Issue by aborruso** [WhitewaterFoundry/WLinux#80]
Hi,
I have seen that it has been published a [new release](https://github.com/WhitewaterFoundry/WLinux/releases) and I would like to install it from the store.

But I'm not sure that the version in the store is already 1.1.20, because I do not find the release number in the store. Is it right?

Thank you

**Comment by sirredbeard** [comment]
It has been pushed to the Microsoft Store. It should be available in 12-24 hours.

**Comment by aborruso** [comment]
@sirredbeard thank you. 

Do you know if there is a way to read in the Microsoft store? Is it there this information?

**Comment by sirredbeard** [comment]
The features listed on the Store will be updated to reflect new features when the new release is posted.

I will make a note at the bottom of the app notes about the version number.

You can also see the release date on the Store and match that to the release dates on GitHub.

**Comment by aborruso** [comment]
Ok, the Microsoft store does not contain the release info of the apps. It's incredible!
Thank you

I have written a tweet https://twitter.com/aborruso/status/1046716324850929665
