### ISSUE TITLE
bash /etc/setup goes in loop

### ISSUE THREAD

**Issue by aborruso** [WhitewaterFoundry/WLinux#82]
Look at this video :(

https://www.youtube.com/watch?v=zhZuIbE21-E&feature=youtu.be&hd=1

How to solve it?

**WLinux Version**

Find: Settings->Apps->Apps & features->WLinux->Advanced Options->Version.

Insert here: 1.1.20

**Windows Build**

10.0.17134.285

**Comment by sirredbeard** [comment]
I do not know why taskkill.exe is not working on your device.

Are you in a corporate environment?

**Comment by sirredbeard** [comment]
To fix for now, `$ touch ~/.firstrun`

**Comment by aborruso** [comment]
@sirredbeard after 3 times it has stopped to loop.

But if I run python3 I have always command not found.

I'm not in a corporate environment.

After running `$ touch ~/.firstrun`, do I must run again `bash /etc/setup`?

**Comment by sirredbeard** [comment]
Did you install python via the install script? You can also `$ apt-get install python3.7 -t testing`.

No, touching .firstrun should halt /etc/setup.

Something is buggy with your exiting of that script, I am going to take a look at that part in a day or two to see if I can't clean it up.

**Comment by sirredbeard** [comment]
It was only ever apt, with some nice pieces around it, we try not to reinvent too much.

Thank you for your support.

**Comment by aborruso** [comment]
@sirredbeard I can not explain weel I try again.

I think this is really a great product and idea, for this reason I bought it.
I also bought it for its bells and whistles, as `explorerintegration`, `azurecliinstall`, ecc.. I have bought it and I cannot use it in a in a direct way.

Thank you
