### ISSUE TITLE
Python not found after installing it via apt

### ISSUE THREAD

**Issue by aborruso** [WhitewaterFoundry/WLinux#83]
Hi,
I have installed it via `sudo apt-get install python3.7 -t testing`, but when I run python3 (or python) I have `-bash: python3: command not found`.

What's wrong?

**WLinux Version**

Find: Settings->Apps->Apps & features->WLinux->Advanced Options->Version.

Insert here: 1.1.20

**Windows Build**

10.0.17134.285

**Comment by aborruso** [comment]
A note.

If I run `$PATH`  I have at the end `No such file or directory`:

    /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program: No such file or directory

**Comment by sirredbeard** [comment]
It's `$ python3.7` if you installed python3.7.

**Comment by sirredbeard** [comment]
If you prefer python or python3 you can alias it in your shell of choice.

Here are the steps for bash: https://www.cyberciti.biz/faq/create-permanent-bash-alias-linux-unix/
