### ISSUE TITLE
Add support out of the box to Docker

### ISSUE THREAD

**Issue by crramirez** [WhitewaterFoundry/WLinux#85]
Hello

I am a user of WSL and Docker and I made this guide:

https://serverfault.com/questions/767994/can-you-run-docker-natively-on-the-new-windows-10-ubuntu-bash-userspace/790806#790806

Now I am a user of your distribution and I recommend including this setup inside Wlinux. Specially the Volumes part mounting C in /c instead of /mnt/c or both

Regards

**Comment by sirredbeard** [comment]
There is way now to connect docker without leaving 2375 open. Have you seen it? 

See https://blogs.msdn.microsoft.com/commandline/2017/12/08/cross-post-wsl-interoperability-with-docker/

What are your thoughts on that method?

**Comment by crramirez** [comment]
Yes I saw it, even I left a note in the answer in stackoverflow, but
leaving the port 2375 open is a lot simpler. If we are not in a public
accessible Windows Server I think we can afford the risk of leaving it open.

**Comment by crramirez** [comment]
Thinking it better if all this stuff could be preconfigured in WLinux, well
I would prefer that method

**Comment by sirredbeard** [comment]
There are a couple ways to get there. All a bit hacky. Setting your default user to root, running those scripts from .bashrc, and then spawning a shell into a less privileged user may be one approach:

`wlinux.exe config -default-user root`

or reset and install WLinux as root:

`wlinux.exe install --root`

**Comment by sirredbeard** [comment]
Being implemented.
