### ISSUE TITLE
/etc/apt/sources.list is getting overwritten

### ISSUE THREAD

**Issue by ket000** [WhitewaterFoundry/WLinux#86]
**Describe the bug**
If we select Y: Would you like to enable the non-free and contrib Debian package repos?  it overwrites 

then it runs below and overwrites the default list file.
sudo sh -c 'echo "deb https://deb.debian.org/debian/ stable non-free contrib" > /etc/apt/sources.list'

if you want to restore the original file, run the below command

cd /etc/apt
sudo cp sources.list sources.list.bak
sudo wget https://raw.githubusercontent.com/WhitewaterFoundry/WLinux/master/linux_files/sources.list

To fix
change it to
sudo sh -c 'echo "deb https://deb.debian.org/debian/ stable non-free contrib" >> /etc/apt/sources.list'

**To Reproduce**
Run bash /etc/setup

**Expected behavior**

**Screenshots**

**Additional context**

**Basic Troubleshooting Checklist**

[ ] I have confirmed WSL is enabled: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[ ] I have searched Google for the error message.
[ ] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[ ] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[ ] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[ ] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**WLinux Version**

Find: Settings->Apps->Apps & features->WLinux->Advanced Options->Version.

Insert here:

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by sirredbeard** [comment]
I issued an emergency patch to /etc/setup.

Please update /etc/setup.

Thank you for bringing this to my attention.

**Comment by ket000** [comment]
Thanks. I will update the script.
