### ISSUE TITLE
windows shell integration does not work properly

### ISSUE THREAD

**Issue by aborruso** [WhitewaterFoundry/WLinux#88]
Hi,
I have used these commands (

```
cp /opt/ShellIntegration/Install.reg /mnt/c/Temp/Install.reg
cmd.exe /C 'Reg import C:\Temp\Install.reg'
cmd.exe /C 'del C:\Temp\Install.reg'
```

and now I have shell WLinux shell integration. But when I right click on a folder and choose "Open with WLinux", a WLinux window opens and then closes immediately.

Thank you

WLinux Version

1.1.20

Windows Build

10.0.17134.285

**Comment by patrick330602** [comment]
Can you check the following?
- run `reg query "HKEY_CURRENT_USER\Software\Classes\Directory\Background\shell\WLinux\command" /ve` from command prompt
  this should return something similar to the following:
  ```
  HKEY_CURRENT_USER\Software\Classes\Directory\Background\shell\WLinux\command
    (Default)    REG_SZ    wlinux.exe run "cd $(wslupath '%V') && $(getent passwd $LOGNAME | cut -d: -f7)"
  ```
- run `wlinux run wslfetch`  from command prompt
  this should return a screenfetch-like prompt printing imformation

**Comment by aborruso** [comment]
Hi @patrick330602 

> - run reg query "HKEY_CURRENT_USER\Software\Classes\Directory\Background\shell\WLinux\command" /ve from command prompt

I have

```
HKEY_CURRENT_USER\Software\Classes\Directory\Background\shell\WLinux\command
    (Predefinito)    REG_SZ    wlinux.exe run "cd $(wslupath '%V') && $(getent passwd $LOGNAME | cut -d: -f7)"
```

> - run wlinux run wslfetch from command prompt this should return a screenfetch-like prompt printing imformation

I have 

![image](https://user-images.githubusercontent.com/30607/46412638-6065d480-c71f-11e8-9d31-d28d02bc064b.png)

Thank you

**Comment by patrick330602** [comment]
Hmm, this is weird... Your installation is actually correct. Do you have this problem for all folders? 
Also is running `wlinux.exe run "cd $(wslupath 'C:\') && $(getent passwd $LOGNAME | cut -d: -f7)"` returning any error?

**Comment by aborruso** [comment]
Hi,
if I run `wlinux.exe run "cd $(wslupath 'C:\') && $(getent passwd $LOGNAME | cut -d: -f7)"` in windows prompt I have

![image](https://user-images.githubusercontent.com/30607/46415192-05cf7700-c725-11e8-9ada-cf71014576b1.png)

I have restarted windows and not the integration works.

**Comment by patrick330602** [comment]
Okay, at least you solve the problem 🤔

**Comment by aborruso** [comment]
@patrick330602 I do not know if I must open another issue but I have too many weird things.

I would like in example to install `pip3` but when I use:

    sudo apt -t testing install build-essential python3.7 python3.7-distutils idle-python3.7 -y

I have `E: The value 'testing' is invalid for APT::Default-Release as such a release is not available in the sources`

If I run without `-testing` is ok.

Then I run

```
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3 get-pip.py --user --no-warn-script-location
export PATH="$PATH:/home/~/.local/bin"
pip3 install -U pip
```

But if I run `pip3 install csvkit`, I have `bash: pip3: command not found`.

Why??  :(
