### ISSUE TITLE
"taskkill.exe /IM WLinux.exe" fails when Ubuntu is installed first

### ISSUE THREAD

**Issue by crramirez** [WhitewaterFoundry/WLinux#89]
**Describe the bug**
When running /etc/setup if I choose update the scripts, it updates it and stops with the following error:

`ERROR: The process "WLinux.exe" not found.`

The problem is this line: `taskkill.exe /IM WLinux.exe`

**To Reproduce**
1. Run /etc/setup
2. Choose Y to update it
3. `ERROR: The process "WLinux.exe" not found.`

**Expected behavior**
Show the options to configure the environment

**Additional context**
I don't have any process running called WLinux.exe when wlinux is running, I only see bash. I installed Ubuntu before WLinux, after installing WLinux I set it as the default with wslconfig

**Basic Troubleshooting Checklist**

[ Y] I have confirmed WSL is enabled: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[N ] I have searched Google for the error message.
[N ] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[Y ] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[N ] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[N ] I have disabled and re-enabled WSL in Windows Features.
[N ] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

If I choose not to update it works

Insert here:

**1.1.20.0**

Find: Settings->Apps->Apps & features->WLinux->Advanced Options->Version.

Insert here:

**17134**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:

OS Name:                   Microsoft Windows 10 Professionnel
OS Version:                10.0.17134 N/A Build 17134
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              Dell Inc. 1.3.8, 2018-08-08

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by sirredbeard** [comment]
This will be deprecated in 1.1.21.
