### ISSUE TITLE
ssh preinstalled

### ISSUE THREAD

**Issue by Morgy93** [WhitewaterFoundry/WLinux#9]
**Is your feature request related to a problem? Please describe.**
I can hardly think of anyone not wanting ssh to be preinstalled.

**Describe the solution you'd like**
ssh preinstalled 

**Describe alternatives you've considered**
There is no alternative to ssh 😎

**Additional context**
Well, `sudo apt install ssh` of course works just fine, but I assume that it's even possible to tweak it if it comes preinstalled.

**Comment by sirredbeard** [comment]
Thanks for that. I think it makes sense for that to be in the base install. I have already added ssh and will be including that in the second release on the store. Thank you again.
