### ISSUE TITLE
sed: can't read /etc/dbus-1/session.conf: No such file or directory

### ISSUE THREAD

**Issue by ket000** [WhitewaterFoundry/WLinux#91]
**Describe the bug**
When running the /etc/setup script, and trying to say Y for 

Would you like to download and install a base set of libraries for GUI packages? [y/N]

It installs the required packages. However it fails when trying to run the sed script for /etc/dbus-1/session.conf.

This file is not there and therefore sed script fails with the below error message.

ketan@PGH-L7200K3F:/etc/dbus-1$ sudo sed -i 's$<listen>.*</listen>$<listen>tcp:host=localhost,port=0</listen>$' /etc/dbus-1/session.conf
sed: can't read /etc/dbus-1/session.conf: No such file or directory
ketan@PGH-L7200K3F:/etc/dbus-1$ sudo sed -i 's$<auth>EXTERNAL</auth>$<auth>ANONYMOUS</auth>$' /etc/dbus-1/session.conf
sed: can't read /etc/dbus-1/session.conf: No such file or directory
ketan@PGH-L7200K3F:/etc/dbus-1$ sudo sed -i 's$</busconfig>$<allow_anonymous/></busconfig>$' /etc/dbus-1/session.conf
sed: can't read /etc/dbus-1/session.conf: No such file or directory

**Comment by sirredbeard** [comment]
I saw that in my testing of 1.1.21 last night. We are working on getting the new GUI created and then will look at that. Thank you for reporting.

**Comment by sirredbeard** [comment]
Added some warning language about the error messages in 1.1.21 if dbus isn't already installed.
