### ISSUE TITLE
Support installation of xfce4 window manager and configure xrdp

### ISSUE THREAD

**Issue by ket000** [WhitewaterFoundry/WLinux#92]
Currently when trying to install xfce4 it does not work correctly. Please add support for installing xfce4. It is possible to add this to Kali Linux. Please see below. 

https://token2shell.com/howto/x410/running-xfce-desktop-on-kali-linux-wsl/

**Comment by sirredbeard** [comment]
"it does not work correctly."

It should work fine. 

Kali and WLinux have the same base image.

But we can't help without more details.

**Comment by sirredbeard** [comment]
Weird. Nothing we do to Debian environment should make something that runs on Ubuntu, Debian, or Kali on WSL not run on WLinux.

**Comment by ket000** [comment]
Getting the following message. Please note I use Bluezonex X window server.

Setup xfce4


https://token2shell.com/howto/x410/customizing-xfce-desktop-for-ubuntu-wsl/

sudo apt install xfce4 xfce4-terminal

Getting the below error when trying to run the install command

invoke-rc.d: could not determine current runlevel
[....] Reloading system message bus config...Failed to open connection to "system" message bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
invoke-rc.d: initscript dbus, action "reload" failed.

Running xfce4-session; gives the following error. 
(xfwm4:9971): xfwm4-WARNING **: Could not find a screen to manage, exiting



(xfce4-session:9957): xfce4-session-WARNING **: gpg-agent returned no PID in the variables

(xfce4-session:9957): xfce4-session-WARNING **: xfsm_manager_load_session: Something wrong with /home/ketan/.cache/sessions/xfce4-session-localhost:0, Does it exist? Permissions issue?

(xfsettingsd:9981): libupower-glib-WARNING **: Couldn't connect to proxy: Could not connect: No such file or directory

(xfsettingsd:9981): libupower-glib-CRITICAL **: up_client_get_lid_is_closed: assertion 'UP_IS_CLIENT (client)' failed

(xfsettingsd:9981): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(xfsettingsd:9981): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(xfwm4:9971): xfwm4-WARNING **: Could not find a screen to manage, exiting
shared memfd open() failed: Function not implemented

(xfsettingsd:9981): GLib-CRITICAL **: g_str_has_prefix: assertion 'prefix != NULL' failed

(xfsettingsd:9981): GLib-GObject-CRITICAL **: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(xfsettingsd:9981): GLib-GObject-CRITICAL **: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed
Connection failure: Connection refused
pa_context_connect() failed: Connection refused

(xfdesktop:9979): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(xfdesktop:9979): GVFS-RemoteVolumeMonitor-WARNING **: remote volume monitor with dbus name org.gtk.vfs.UDisks2VolumeMonitor is not supported
xfsettingsd: No window manager registered on screen 0.

(xfsettingsd:9981): xfsettingsd-WARNING **: Failed to get the _NET_NUMBER_OF_DESKTOPS property.
xfce4-panel: No window manager registered on screen 0. To start the panel without this check, run with --disable-wm-check.

(xfce4-session:9957): xfce4-session-WARNING **: failed to run script: Failed to execute child process "/usr/bin/pm-is-supported" (No such file or directory)

(xfce4-session:9957): xfce4-session-WARNING **: failed to run script: Failed to execute child process "/usr/bin/pm-is-supported" (No such file or directory)

(xfce4-panel:9975): Wnck-CRITICAL **: wnck_workspace_is_virtual: assertion 'WNCK_IS_WORKSPACE (space)' failed

**Comment by ket000** [comment]
https://token2shell.com/howto/x410/customizing-xfce-desktop-for-ubuntu-wsl/

(Followed the above direction)

sudo apt install xfce4 xfce4-terminal
Getting the below error when trying to run the install command

invoke-rc.d: could not determine current runlevel
[....] Reloading system message bus config...Failed to open connection to
"system" message bus: Failed to connect to socket
/var/run/dbus/system_bus_socket: No such file or directory
invoke-rc.d: initscript dbus, action "reload" failed.

Running xfce4-session; gives the following error.


(xfce4-session:9957): xfce4-session-WARNING **: gpg-agent returned no PID
in the variables

(xfce4-session:9957): xfce4-session-WARNING **: xfsm_manager_load_session:
Something wrong with /home/ketan/.cache/sessions/xfce4-session-localhost:0,
Does it exist? Permissions issue?

(xfsettingsd:9981): libupower-glib-WARNING **: Couldn't connect to proxy:
Could not connect: No such file or directory

(xfsettingsd:9981): libupower-glib-CRITICAL **:
up_client_get_lid_is_closed: assertion 'UP_IS_CLIENT (client)' failed

(xfsettingsd:9981): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(xfsettingsd:9981): GLib-GObject-CRITICAL **: g_signal_connect_data:
assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(xfwm4:9971): xfwm4-WARNING **: Could not find a screen to manage, exiting
shared memfd open() failed: Function not implemented

(xfsettingsd:9981): GLib-CRITICAL **: g_str_has_prefix: assertion 'prefix
!= NULL' failed

(xfsettingsd:9981): GLib-GObject-CRITICAL **: g_value_get_string: assertion
'G_VALUE_HOLDS_STRING (value)' failed

(xfsettingsd:9981): GLib-GObject-CRITICAL **: g_value_get_string: assertion
'G_VALUE_HOLDS_STRING (value)' failed
Connection failure: Connection refused
pa_context_connect() failed: Connection refused

(xfdesktop:9979): GLib-GObject-CRITICAL **: g_object_unref: assertion
'G_IS_OBJECT (object)' failed

(xfdesktop:9979): GVFS-RemoteVolumeMonitor-WARNING **: remote volume
monitor with dbus name org.gtk.vfs.UDisks2VolumeMonitor is not supported
xfsettingsd: No window manager registered on screen 0.

(xfsettingsd:9981): xfsettingsd-WARNING **: Failed to get the
_NET_NUMBER_OF_DESKTOPS property.
xfce4-panel: No window manager registered on screen 0. To start the panel
without this check, run with --disable-wm-check.

(xfce4-session:9957): xfce4-session-WARNING **: failed to run script:
Failed to execute child process "/usr/bin/pm-is-supported" (No such file or
directory)

(xfce4-session:9957): xfce4-session-WARNING **: failed to run script:
Failed to execute child process "/usr/bin/pm-is-supported" (No such file or
directory)

(xfce4-panel:9975): Wnck-CRITICAL **: wnck_workspace_is_virtual: assertion
'WNCK_IS_WORKSPACE (space)' failed

**Comment by patrick330602** [comment]
you need to run `sudo apt install xfce4-session` and start using `xfce4-session`

**Comment by ket000** [comment]
I did that and xfce4-session fails. It only starts panels but no main desktop. Please see the errors. Can you try to do that in your copy and see if it works.

**Comment by patrick330602** [comment]
Can you check your settings for your X server, e.g., VcXsrv or X410 that they are set to Full Desktop/One Window? it works for me
![image](https://user-images.githubusercontent.com/15316889/46518727-4c99aa00-c8a8-11e8-8a28-dafdded8f4f1.png)
