### ISSUE TITLE
Root user shouldn't run by default

### ISSUE THREAD

**Issue by benys** [WhitewaterFoundry/WLinux#94]
Many programs require to run without root permissions. So, in my opinion, the terminal should start with a specific user.

For example, Ubuntu WSL distribution ask about user account during setup time.

**Comment by sirredbeard** [comment]
Normally WLinux works the same way. It should prompt you to create a non-root default user at launch that gets added to wheel so you can sudo tasks as needed.

**Comment by sirredbeard** [comment]
Closed due to lack of response.
