### ISSUE TITLE
Improve WLinux Documentation

### ISSUE THREAD

**Issue by garytyler** [WhitewaterFoundry/WLinux#96]
**Is your feature request related to a problem? Please describe.**
Lack of documentation.

**Describe the solution you'd like**
Details of what it does and how to use it.

**Describe alternatives you've considered**
Debian, Ubuntu, Fedora, CentOS, openSUSE, Mageia, Oracle, Alpine, CRUX, Clear

**Comment by garytyler** [comment]
One item could be a line about using `/etc/setup` to run the setup script. I can't tell if you intend for it to run on load, but if that's the case, it doesn't. It also doesn't run after updating and re-opening as per the message "WLinux will now close. Please re-open and the updated script will begin.".

It's unclear, but I'm contextually gathering this setup script is the core, or at least the interface, of what you're providing. That could also be explained. Again, I could very well be wrong but am left to assume given the lack of info provided. So, doing my best.

Some info about what the latest setup script includes would be nice. I expect this has potential to change on each release (?) and, as it stands, the only way to discover the current items is to run it and select `n` then `[ENTER]` until it's over. A regular list would help, even if in the beginning of the setup script.

For an example on elaboration of these items that would help, zsh setup also installs oh-my-zsh. I was never asked if I wanted that, or notified I was installing it. What else is there? As it stands, I have to read the code.

**Comment by Kilo59** [comment]
I could open a separate issue for this, but under the **obtaining support** section, the [link for opening an issue ](https://github.com/sirredbeard/WLinux/issues/new) give a 404 Error.
![image](https://user-images.githubusercontent.com/13108583/46583245-98bc2a00-ca21-11e8-8aa3-1333fd7e343c.png)

**Comment by Kilo59** [comment]
The documenation has this series of bullet points about WLinux

> - A new out-of-the-box experience for users to get started on the Linux terminal.
> - Choice of terminal shells: bash, csh, zsh (with oh-my-zsh), and fish (with oh-my-fish).
> - Choice of editors: emacs, neovim, nano, and Visual Studio Code.
> - Choice of development environments: nodejs (with n, npm, and/or yarn), python 3.7 (and pip), ruby (via rbenv), and go.

What does that mean exactly?
I took it to mean that all these tools were "pre-installed" and/or I would be prompted about installing them in my initial setup. Neither of which seem to be true.

I assume it means more than "_You can install python, go etc. using `apt-get` if you want_".

**Comment by sirredbeard** [comment]
@Kilo59 

> Under the obtaining support section, the link for opening an issue gives a 404 Error.

Fixed the broken link. Thank you.

> I took it to mean that all these tools were "pre-installed"

It was originally all pre-installed, then the size got to be 1GB+ which affected people in low-bandwidth countries, so we wrote a lengthy hand-crafted onboarding script that optionally installed these things that ran when you first ran WLinux (1.1.20), then people complained about the tool auto-running so we wrote it into a separate tool called wlinux-setup that is merely mentioned on the first run but otherwise gets out of people's way (1.1.21).

I would recommend giving clean install of 1.1.21 a shot when it is released on the store later today or tomorrow.

**Comment by Kilo59** [comment]
@sirredbeard That all makes sense. I just ran the `/etc/setup` manually after my last comment. That was exactly the kind of thing I was expecting, nice job.

>I would recommend giving clean install of 1.1.21 a shot when it is released on the store later today or tomorrow.

Thanks for the tip, looking forward to it.

**Comment by garytyler** [comment]
@Kilo59 the X410 site gives a good overview of setting up an environment for running the graphical apps. I recommend just using that.

**Comment by frankang** [comment]
I installed zsh and ruby via wlinux-setup, however, ruby is not in the $PATH if started with zsh (wsl.exe or wlinux.exe).
