### ISSUE TITLE
Modest feature list

### ISSUE THREAD

**Issue by garytyler** [WhitewaterFoundry/WLinux#97]
**Is your feature request related to a problem? Please describe.**
Apt packages in an install script aren't features, and many of these packages have [numerous limitations in WSL](https://github.com/ethanhs/WSL-Programs). Your current language implies some level of support. Since you're asking $15 for a Linux distro, I think it's important to be concise about what support you are providing. The pull request tab doesn't really suffice here.

"out-of-the-box experience for users to get started on the Linux terminal."
After installing, bash is the only item listed below that is available "out-of-the-box". 

"Choice of terminal shells: bash, csh, zsh (with oh-my-zsh), and fish (with oh-my-fish)."
Available without WLinux. zsh and fish have the same cli bugs on my system that persist in Ubuntu. No difference.

"Choice of development environments: nodejs, python 3.7, and go."
Available without WLinux.

"Choice of cloud and administration tools: PowerShell and Azure-cli."
Available without WLinux.

**Describe the solution you'd like**
At least a CHANGELOG, but I think a list of supported features and supporting documentation is important.

**Describe alternatives you've considered**
Debian, Ubuntu, Fedora, CentOS, openSUSE, Mageia, Oracle, Alpine, CRUX, Clear

**Comment by sirredbeard** [comment]
I am sorry you do not think our project is up to your standards. If you would like a refund, please forward a copy of your Microsoft Store confirmation e-mail to hayden @ whitewaterfoundry.com and I will personally refund your $15.

**Comment by sirredbeard** [comment]
Also see [ROADMAP.md](https://github.com/WhitewaterFoundry/WLinux/blob/master/ROADMAP.md) in the documentation.
