### ISSUE TITLE
NodeJS cannot be installed correctly

### ISSUE THREAD

**Issue by khuongduybui** [WhitewaterFoundry/WLinux#99]
**Describe the bug**
NodeJS cannot be installed correctly

**To Reproduce**
1. Install via the built-in setup script and select NOTHING but NodeJS
2. which node => /usr/bin/node
3. node --version => version 8 (even though version 10 is in /etc/apt/source.list.d/nodesource.list)
4. which npm => nothing
5. sudo apt install npm => fail

**Expected behavior**
NodeJS v10 and npm should have been installed.

**WLinux Version**
1.1.20.0

**Windows Build**
18252

**Comment by sirredbeard** [comment]
Thank you for reporting this. I will take a look at it.

**Comment by sirredbeard** [comment]
For now n is available in our repo. `$ sudo apt install n`

I think going forward n is going to be best way to manage installation of nodejs and path issues.

I am going to make the changes in 1.1.21 our upcoming release.

**Comment by sirredbeard** [comment]
Will you please take a look at this commit? https://github.com/WhitewaterFoundry/WLinux/commit/d35214fc990033ac27b3ddca13c27bb4382d9ebe

**Comment by khuongduybui** [comment]
I just tested it; no issues found. One minor thing I already noted on the PR.
